package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph"
	"go2fix-backend/internal/graph/model"
	"go2fix-backend/internal/storage"
	"log"
	"math"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/jackc/pgx/v5/pgtype"
)

// Category is the resolver for the category field.
func (r *bookingResolver) Category(ctx context.Context, obj *model.Booking) (*model.ServiceCategory, error) {
	if obj.CategoryID == nil || *obj.CategoryID == "" {
		return nil, nil
	}
	catUUID := stringToUUID(*obj.CategoryID)
	if !catUUID.Valid {
		return nil, nil
	}
	cat, err := r.Queries.GetServiceCategoryByID(ctx, catUUID)
	if err != nil {
		return nil, nil // gracefully return nil if category not found
	}
	return dbServiceCatToGQL(cat), nil
}

// CreateBookingRequest is the resolver for the createBookingRequest field.
func (r *mutationResolver) CreateBookingRequest(ctx context.Context, input model.CreateBookingInput) (*model.Booking, error) {
	var userID pgtype.UUID

	claims := auth.GetUserFromContext(ctx)
	if claims != nil {
		userID = stringToUUID(claims.UserID)
	} else {
		// Guest booking: require guest contact fields.
		if input.GuestEmail == nil || input.GuestName == nil || input.GuestPhone == nil {
			return nil, fmt.Errorf("guest bookings require guestEmail, guestName, and guestPhone")
		}

		// Find or create a guest user by email.
		existingUser, err := r.Queries.GetUserByEmail(ctx, *input.GuestEmail)
		if err == nil {
			userID = existingUser.ID
		} else {
			newUser, createErr := r.Queries.CreateUser(ctx, db.CreateUserParams{
				Email:             *input.GuestEmail,
				FullName:          *input.GuestName,
				Phone:             pgtype.Text{String: *input.GuestPhone, Valid: true},
				Role:              db.UserRoleClient,
				Status:            db.UserStatusActive,
				PreferredLanguage: pgtype.Text{String: "ro", Valid: true},
			})
			if createErr != nil {
				return nil, fmt.Errorf("failed to create guest user: %w", createErr)
			}
			userID = newUser.ID
		}
	}

	// Resolve address: reuse existing or create new.
	var addressID pgtype.UUID
	if input.AddressID != nil {
		// Reuse an existing saved address.
		addrUUID := stringToUUID(*input.AddressID)
		existing, err := r.Queries.GetAddressByID(ctx, addrUUID)
		if err != nil {
			return nil, fmt.Errorf("address not found: %w", err)
		}
		// Verify the address belongs to this user.
		if existing.UserID != userID {
			return nil, fmt.Errorf("address does not belong to this user")
		}
		addressID = existing.ID
	} else if input.Address != nil {
		// Create a new address from inline input.
		addr, err := r.Queries.CreateAddress(ctx, db.CreateAddressParams{
			UserID:        userID,
			Label:         stringToText(input.Address.Label),
			StreetAddress: input.Address.StreetAddress,
			City:          input.Address.City,
			County:        input.Address.County,
			PostalCode:    stringToText(input.Address.PostalCode),
			Floor:         stringToText(input.Address.Floor),
			Apartment:     stringToText(input.Address.Apartment),
			EntryCode:     stringToText(input.Address.EntryCode),
			Latitude:      float64PtrToFloat8(input.Address.Latitude),
			Longitude:     float64PtrToFloat8(input.Address.Longitude),
			Notes:         stringToText(input.Address.Notes),
			IsDefault:     pgtype.Bool{Bool: false, Valid: true},
		})
		if err != nil {
			return nil, fmt.Errorf("failed to create address: %w", err)
		}
		addressID = addr.ID
	} else {
		return nil, fmt.Errorf("either addressId or address input is required")
	}

	// Validate city is supported (enabled and active) and get pricing multiplier.
	var addrCity string
	cityMultiplier := 1.0
	if input.AddressID != nil {
		addr, _ := r.Queries.GetAddressByID(ctx, addressID)
		addrCity = addr.City
	} else if input.Address != nil {
		addrCity = input.Address.City
	}
	if addrCity != "" {
		city, cityErr := r.Queries.GetCityByName(ctx, strings.TrimSpace(addrCity))
		if cityErr != nil {
			return nil, fmt.Errorf("ne pare rau, nu suntem inca activi in %s", addrCity)
		}
		if m := numericToFloat(city.PricingMultiplier); m > 0 {
			cityMultiplier = m
		}
	}

	// Look up service definition for pricing.
	dbServiceType := gqlServiceTypeToDb(input.ServiceType)
	serviceDef, err := r.Queries.GetServiceByType(ctx, dbServiceType)
	if err != nil {
		return nil, fmt.Errorf("service type not found: %w", err)
	}

	hourlyRate := numericToFloat(serviceDef.BasePricePerHour) * cityMultiplier

	// Fetch extras for duration and pricing.
	var extrasDuration []struct {
		DurationMinutes int32
		Quantity        int
	}
	extrasTotal := 0.0
	if input.Extras != nil {
		for _, extraInput := range input.Extras {
			extra, err := r.Queries.GetExtraByID(ctx, stringToUUID(extraInput.ExtraID))
			if err != nil {
				return nil, fmt.Errorf("extra not found: %w", err)
			}
			extrasTotal += numericToFloat(extra.Price) * float64(extraInput.Quantity)
			extrasDuration = append(extrasDuration, struct {
				DurationMinutes int32
				Quantity        int
			}{DurationMinutes: extra.DurationMinutes, Quantity: extraInput.Quantity})
		}
	}

	// Estimate duration using DB-driven parameters.
	estimatedHours := estimateDuration(serviceDef, input.NumRooms, input.NumBathrooms, input.AreaSqm, input.PropertyType, input.HasPets, extrasDuration)

	subtotal := hourlyRate * estimatedHours

	// Pets surcharge (flat fee).
	petsSurcharge := 0.0
	if input.HasPets != nil && *input.HasPets {
		petsSurcharge = 15.0
	}

	estimatedTotal := subtotal + extrasTotal + petsSurcharge

	// Resolve scheduled date/time from timeSlots or legacy fields.
	var scheduledDate time.Time
	var scheduledTime time.Time

	if input.TimeSlots != nil && len(input.TimeSlots) > 0 {
		// Use first time slot.
		scheduledDate, err = time.Parse("2006-01-02", input.TimeSlots[0].Date)
		if err != nil {
			return nil, fmt.Errorf("invalid time slot date format: %w", err)
		}
		scheduledTime, err = time.Parse("15:04", input.TimeSlots[0].StartTime)
		if err != nil {
			return nil, fmt.Errorf("invalid time slot start time format: %w", err)
		}
	} else if input.ScheduledDate != nil && input.ScheduledStartTime != nil {
		// Legacy single date/time.
		scheduledDate, err = time.Parse("2006-01-02", *input.ScheduledDate)
		if err != nil {
			return nil, fmt.Errorf("invalid scheduled date format: %w", err)
		}
		scheduledTime, err = time.Parse("15:04", *input.ScheduledStartTime)
		if err != nil {
			return nil, fmt.Errorf("invalid scheduled start time format: %w", err)
		}
	} else {
		return nil, fmt.Errorf("either timeSlots or scheduledDate+scheduledStartTime is required")
	}

	// Override with system-optimized start time from matchmaking if provided.
	if input.SuggestedStartTime != nil && *input.SuggestedStartTime != "" {
		suggested, parseErr := time.Parse("15:04", *input.SuggestedStartTime)
		if parseErr == nil {
			scheduledTime = suggested
		}
	}

	referenceCode := fmt.Sprintf("G2F-%d", time.Now().UnixNano()%1000000)

	// Resolve commission rate: company override -> category commission -> platform default -> 25% fallback.
	commissionPct := 25.0 // hardcoded fallback
	commissionResolved := false
	if input.PreferredWorkerID != nil && *input.PreferredWorkerID != "" {
		workerUUID := stringToUUID(*input.PreferredWorkerID)
		if w, wErr := r.Queries.GetWorkerByID(ctx, workerUUID); wErr == nil {
			if company, cErr := r.Queries.GetCompanyByID(ctx, w.CompanyID); cErr == nil && company.CommissionOverridePct.Valid {
				commissionPct = numericToFloat(company.CommissionOverridePct)
				commissionResolved = true
			}
		}
	}
	if !commissionResolved && serviceDef.CategoryID.Valid {
		if cat, catErr := r.Queries.GetServiceCategoryByID(ctx, serviceDef.CategoryID); catErr == nil && cat.CommissionPct.Valid {
			commissionPct = numericToFloat(cat.CommissionPct)
			commissionResolved = true
		}
	}
	if !commissionResolved {
		if setting, sErr := r.Queries.GetPlatformSetting(ctx, "platform_commission_pct"); sErr == nil {
			if v := numericFromString(setting.Value); v > 0 {
				commissionPct = v
			}
		}
	}

	// Resolve category_id: prefer explicit input, fall back to service definition's category.
	var bookingCategoryID pgtype.UUID
	if input.CategoryID != nil && *input.CategoryID != "" {
		bookingCategoryID = stringToUUID(*input.CategoryID)
	} else if serviceDef.CategoryID.Valid {
		bookingCategoryID = serviceDef.CategoryID
	}

	var customFieldsBytes []byte
	if input.CustomFields != nil {
		customFieldsBytes = []byte(*input.CustomFields)
	}

	booking, err := r.Queries.CreateBooking(ctx, db.CreateBookingParams{
		ReferenceCode: referenceCode,
		ClientUserID:  userID,
		AddressID:     addressID,
		ServiceType:   dbServiceType,
		ScheduledDate: pgtype.Date{
			Time:  scheduledDate,
			Valid: true,
		},
		ScheduledStartTime: pgtype.Time{
			Microseconds: int64(scheduledTime.Hour())*3_600_000_000 + int64(scheduledTime.Minute())*60_000_000,
			Valid:        true,
		},
		EstimatedDurationHours: float64ToNumeric(estimatedHours),
		PropertyType:           stringToText(input.PropertyType),
		NumRooms:               intToInt4Val(input.NumRooms),
		NumBathrooms:           intToInt4Val(input.NumBathrooms),
		AreaSqm:                intToInt4(input.AreaSqm),
		HasPets:                boolToPgBool(input.HasPets),
		SpecialInstructions:    stringToText(input.SpecialInstructions),
		HourlyRate:             float64ToNumeric(hourlyRate),
		EstimatedTotal:         float64ToNumeric(estimatedTotal),
		RecurringGroupID:       pgtype.UUID{},
		OccurrenceNumber:       pgtype.Int4{},
		PlatformCommissionPct:  float64ToNumeric(commissionPct),
		CityPricingMultiplier:  float64ToNumeric(cityMultiplier),
		PricingModel:           db.NullPricingModel{PricingModel: serviceDef.PricingModel, Valid: true},
		CategoryID:             bookingCategoryID,
		CustomFields:           customFieldsBytes,
		CityAreaID: func() pgtype.UUID {
			if input.CityAreaID == nil {
				return pgtype.UUID{}
			}
			return stringToUUID(*input.CityAreaID)
		}(),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create booking: %w", err)
	}

	// Insert time slots if provided.
	if input.TimeSlots != nil && len(input.TimeSlots) > 0 {
		for i, slot := range input.TimeSlots {
			slotDate, _ := time.Parse("2006-01-02", slot.Date)
			slotStartTime := parseHHMMToTime(slot.StartTime)
			slotEndTime := parseHHMMToTime(slot.EndTime)

			_, tsErr := r.Queries.CreateBookingTimeSlot(ctx, db.CreateBookingTimeSlotParams{
				BookingID:  booking.ID,
				SlotDate:   pgtype.Date{Time: slotDate, Valid: true},
				StartTime:  slotStartTime,
				EndTime:    slotEndTime,
				IsSelected: i == 0,
			})
			if tsErr != nil {
				log.Printf("failed to create time slot %d: %v", i, tsErr)
			}
		}
	}

	// If preferred worker was selected, set company_id and worker_id.
	if input.PreferredWorkerID != nil && *input.PreferredWorkerID != "" {
		workerUUID := stringToUUID(*input.PreferredWorkerID)
		worker, err := r.Queries.GetWorkerByID(ctx, workerUUID)
		if err == nil {
			booking, _ = r.Queries.SetBookingPreferredWorker(ctx, db.SetBookingPreferredWorkerParams{
				ID:        booking.ID,
				CompanyID: worker.CompanyID,
				WorkerID:  workerUUID,
			})
		}
	}

	gqlBooking := dbBookingToGQL(booking)
	r.enrichBooking(ctx, booking, gqlBooking)

	// Notify client (booking confirmed) and company admin (new request), if applicable.
	r.dispatchBookingCreatedNotifications(ctx, booking)

	return gqlBooking, nil
}

// CancelBooking is the resolver for the cancelBooking field.
func (r *mutationResolver) CancelBooking(ctx context.Context, id string, reason *string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// ✅ SECURITY: Check authorization before canceling booking (Phase 3)
	bookingID := stringToUUID(id)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bookingID); err != nil {
		return nil, err
	}

	// Determine cancel status based on the user's role.
	var cancelStatus db.BookingStatus
	switch claims.Role {
	case "company_admin":
		cancelStatus = db.BookingStatusCancelledByCompany
	case "global_admin":
		cancelStatus = db.BookingStatusCancelledByAdmin
	default:
		cancelStatus = db.BookingStatusCancelledByClient
	}

	// Validate status transition.
	current, err := r.Queries.GetBookingByID(ctx, stringToUUID(id))
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}
	if err := validateStatusTransition(current.Status, cancelStatus); err != nil {
		return nil, err
	}

	var reasonText string
	if reason != nil {
		reasonText = *reason
	}

	booking, err := r.Queries.CancelBookingWithReason(ctx, db.CancelBookingWithReasonParams{
		ID:                 stringToUUID(id),
		Status:             cancelStatus,
		CancellationReason: pgtype.Text{String: reasonText, Valid: reasonText != ""},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to cancel booking: %w", err)
	}

	// If this booking had a reserved referral discount, release it back to available.
	if current.ReferralDiscountID.Valid {
		if _, err := r.Queries.ReleaseReferralDiscount(ctx, current.ReferralDiscountID); err != nil {
			log.Printf("referral: failed to release discount %s on booking cancellation: %v", uuidToString(current.ReferralDiscountID), err)
		}
		if err := r.Queries.ClearBookingReferralDiscount(ctx, current.ID); err != nil {
			log.Printf("referral: failed to clear referral_discount_id on booking %s: %v", uuidToString(current.ID), err)
		}
	}

	// Issue Stripe refund (partial for late client cancellations, full otherwise).
	r.issueCancellationRefund(ctx, current, cancelStatus)

	// Handle invoice storno and penalty creation (non-blocking).
	go func() {
		bgCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		r.issueCancellationInvoiceActions(bgCtx, current, cancelStatus)
	}()

	// Notify relevant parties based on who cancelled.
	if cancelStatus == db.BookingStatusCancelledByClient {
		r.dispatchBookingCancelledByClient(ctx, booking, reasonText)
	} else if cancelStatus == db.BookingStatusCancelledByAdmin {
		r.dispatchBookingCancelledByAdmin(ctx, booking, reasonText)
	}

	return dbBookingToGQL(booking), nil
}

// AssignWorkerToBooking is the resolver for the assignWorkerToBooking field.
func (r *mutationResolver) AssignWorkerToBooking(ctx context.Context, bookingID string, workerID string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "company_admin" && claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	// Look up worker to get their company ID.
	wID := stringToUUID(workerID)
	worker, err := r.Queries.GetWorkerByID(ctx, wID)
	if err != nil {
		return nil, fmt.Errorf("worker not found: %w", err)
	}

	// Company admin can only assign workers from their own company.
	if claims.Role == "company_admin" {
		company, cErr := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
		if cErr != nil {
			return nil, fmt.Errorf("company not found for user")
		}
		if uuidToString(worker.CompanyID) != uuidToString(company.ID) {
			return nil, fmt.Errorf("worker does not belong to your company")
		}
	}

	// Validate worker has the booking's category.
	existingBooking, err := r.Queries.GetBookingByID(ctx, stringToUUID(bookingID))
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}
	if existingBooking.CategoryID.Valid {
		hasCategory, catErr := r.Queries.WorkerHasCategory(ctx, db.WorkerHasCategoryParams{
			WorkerID:   wID,
			CategoryID: existingBooking.CategoryID,
		})
		if catErr != nil {
			return nil, fmt.Errorf("failed to verify worker category: %w", catErr)
		}
		if !hasCategory {
			return nil, fmt.Errorf("worker is not qualified for this booking's service category")
		}
	}

	// Check worker's daily booking limit before assigning.
	if worker.MaxDailyBookings.Valid {
		count, countErr := r.Queries.CountWorkerBookingsForDate(ctx, db.CountWorkerBookingsForDateParams{
			WorkerID:      wID,
			ScheduledDate: existingBooking.ScheduledDate,
		})
		if countErr == nil && count >= int64(worker.MaxDailyBookings.Int32) {
			return nil, fmt.Errorf("worker has reached their daily booking limit of %d for %s",
				worker.MaxDailyBookings.Int32, existingBooking.ScheduledDate.Time.Format("2006-01-02"))
		}
	}

	booking, err := r.Queries.AssignWorkerToBooking(ctx, db.AssignWorkerToBookingParams{
		ID:        stringToUUID(bookingID),
		CompanyID: worker.CompanyID,
		WorkerID:  wID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to assign worker: %w", err)
	}

	// Notify client and assigned worker (non-blocking).
	r.dispatchWorkerAssignedNotifications(ctx, booking)

	gqlBooking := dbBookingToGQL(booking)
	r.enrichBooking(ctx, booking, gqlBooking)
	return gqlBooking, nil
}

// ConfirmBooking is the resolver for the confirmBooking field.
func (r *mutationResolver) ConfirmBooking(ctx context.Context, id string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// ✅ SECURITY: Check authorization before confirming booking (Phase 3)
	bookingID := stringToUUID(id)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bookingID); err != nil {
		return nil, err
	}

	current, err := r.Queries.GetBookingByID(ctx, bookingID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	// Idempotent: if already confirmed (e.g., auto-confirmed on payment), return as-is.
	if current.Status == db.BookingStatusConfirmed {
		gqlBooking := dbBookingToGQL(current)
		r.enrichBooking(ctx, current, gqlBooking)
		return gqlBooking, nil
	}

	if err := validateStatusTransition(current.Status, db.BookingStatusConfirmed); err != nil {
		return nil, err
	}

	booking, err := r.Queries.UpdateBookingStatus(ctx, db.UpdateBookingStatusParams{
		ID:     stringToUUID(id),
		Status: db.BookingStatusConfirmed,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to confirm booking: %w", err)
	}

	// Notify client that the company confirmed the booking.
	if booking.ClientUserID.Valid {
		body := fmt.Sprintf("Comanda %s a fost confirmată. Ne vedem în curând!", booking.ReferenceCode)
		data := []byte(fmt.Sprintf(`{"bookingId":"%s"}`, uuidToString(booking.ID)))
		go func() {
			bgCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			if _, err := r.Queries.CreateNotification(bgCtx, db.CreateNotificationParams{
				UserID: booking.ClientUserID,
				Type:   db.NotificationTypeBookingConfirmed,
				Title:  "Comandă confirmată",
				Body:   body,
				Data:   data,
			}); err != nil {
				log.Printf("confirmBooking: failed to notify client: %v", err)
			}
		}()
	}

	return dbBookingToGQL(booking), nil
}

// StartJob is the resolver for the startJob field.
func (r *mutationResolver) StartJob(ctx context.Context, id string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// ✅ SECURITY: Check authorization before starting job (Phase 3)
	bookingID := stringToUUID(id)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bookingID); err != nil {
		return nil, err
	}

	// Validate status transition.
	current, err := r.Queries.GetBookingByID(ctx, bookingID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}
	if err := validateStatusTransition(current.Status, db.BookingStatusInProgress); err != nil {
		return nil, err
	}

	// Enforce: worker cannot start more than 1 hour before scheduled time.
	if hoursUntilBooking(current.ScheduledDate, current.ScheduledStartTime) > 1.0 {
		return nil, fmt.Errorf("nu poți începe lucrarea cu mai mult de 1 oră înainte de ora programată")
	}

	booking, err := r.Queries.StartBooking(ctx, stringToUUID(id))
	if err != nil {
		return nil, fmt.Errorf("failed to start job: %w", err)
	}

	// Notify client that the worker has arrived and started the job.
	if booking.ClientUserID.Valid {
		body := fmt.Sprintf("Echipa ta a ajuns și a început lucrul pentru comanda %s.", booking.ReferenceCode)
		data := []byte(fmt.Sprintf(`{"bookingId":"%s"}`, uuidToString(booking.ID)))
		go func() {
			bgCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
			defer cancel()
			if _, err := r.Queries.CreateNotification(bgCtx, db.CreateNotificationParams{
				UserID: booking.ClientUserID,
				Type:   db.NotificationTypeBookingStarted,
				Title:  "Curățenia a început",
				Body:   body,
				Data:   data,
			}); err != nil {
				log.Printf("startJob: failed to notify client: %v", err)
			}
		}()
	}

	// Send email and WhatsApp notifications (non-blocking).
	r.dispatchJobStartedEmail(ctx, booking)

	return dbBookingToGQL(booking), nil
}

// CompleteJob is the resolver for the completeJob field.
func (r *mutationResolver) CompleteJob(ctx context.Context, id string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// ✅ SECURITY: Check authorization before completing job (Phase 3)
	bookingID := stringToUUID(id)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bookingID); err != nil {
		return nil, err
	}

	// Validate status transition.
	current, err := r.Queries.GetBookingByID(ctx, stringToUUID(id))
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}
	if err := validateStatusTransition(current.Status, db.BookingStatusCompleted); err != nil {
		return nil, err
	}

	booking, err := r.Queries.CompleteBooking(ctx, stringToUUID(id))
	if err != nil {
		return nil, fmt.Errorf("failed to complete job: %w", err)
	}

	// Calculate final total and platform commission.
	estimatedTotal := numericToFloat(booking.EstimatedTotal)
	commissionPct := numericToFloat(booking.PlatformCommissionPct)
	commissionAmount := estimatedTotal * (commissionPct / 100.0)

	booking, err = r.Queries.SetBookingFinalTotal(ctx, db.SetBookingFinalTotalParams{
		ID:                       booking.ID,
		FinalTotal:               float64ToNumeric(estimatedTotal),
		PlatformCommissionAmount: float64ToNumeric(commissionAmount),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to set final total: %w", err)
	}

	// Process referral tracking synchronously.
	// Must run before invoice generation so that if the referrer also applies a
	// discount on a future booking, the commission is already correct.
	r.processReferralAtBookingComplete(ctx, booking)

	// Also: if this booking itself had a referral discount applied, confirm it as used.
	if booking.ReferralDiscountID.Valid {
		if _, err := r.Queries.ConfirmReferralDiscountUsed(ctx, booking.ReferralDiscountID); err != nil {
			log.Printf("referral: failed to confirm discount %s as used: %v", uuidToString(booking.ReferralDiscountID), err)
		}
	}

	// Auto-generate invoices after job completion.
	// Both final_total and platform_commission_amount are now set on the booking.
	if !booking.CompanyID.Valid {
		log.Printf("invoice: booking %s has no company, skipping invoice generation", booking.ReferenceCode)
	} else {
		company, compErr := r.Queries.GetCompanyByID(ctx, booking.CompanyID)
		if compErr != nil {
			log.Printf("invoice: failed to load company for completed booking %s: %v", booking.ReferenceCode, compErr)
		} else {
			// ① Client service invoice: company → client, for the full service amount.
			if _, invErr := r.InvoiceService.GenerateClientServiceInvoice(ctx, booking, company, booking.ClientUserID); invErr != nil {
				log.Printf("invoice: client service invoice failed for booking %s: %v", booking.ReferenceCode, invErr)
			}

			// ② Platform commission invoice: platform → company, for the commission amount.
			commissionBani := int32(math.Round(numericToFloat(booking.PlatformCommissionAmount) * 100))
			if commissionBani > 0 {
				if _, invErr := r.InvoiceService.GenerateCommissionInvoice(
					ctx,
					booking.CompanyID,
					commissionBani,
					1,
					booking.ReferenceCode,
					booking.ReferenceCode,
				); invErr != nil {
					log.Printf("invoice: commission invoice failed for booking %s: %v", booking.ReferenceCode, invErr)
				}
			}
		}
	}

	// Notify client that job is complete (non-blocking).
	r.dispatchBookingCompletedNotification(ctx, booking)

	return dbBookingToGQL(booking), nil
}

// SelectBookingTimeSlot is the resolver for the selectBookingTimeSlot field.
func (r *mutationResolver) SelectBookingTimeSlot(ctx context.Context, bookingID string, timeSlotID string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bID := stringToUUID(bookingID)

	// Deselect all slots first.
	if err := r.Queries.DeselectAllBookingTimeSlots(ctx, bID); err != nil {
		return nil, fmt.Errorf("failed to deselect slots: %w", err)
	}

	// Select the chosen slot.
	slot, err := r.Queries.SelectBookingTimeSlot(ctx, stringToUUID(timeSlotID))
	if err != nil {
		return nil, fmt.Errorf("failed to select slot: %w", err)
	}

	// Update booking's scheduled_date and scheduled_start_time to match.
	_, err = r.Queries.UpdateBookingSchedule(ctx, db.UpdateBookingScheduleParams{
		ID:                 bID,
		ScheduledDate:      slot.SlotDate,
		ScheduledStartTime: slot.StartTime,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update booking schedule: %w", err)
	}

	booking, err := r.Queries.GetBookingByID(ctx, bID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	result := dbBookingToGQL(booking)
	r.enrichBooking(ctx, booking, result)
	return result, nil
}

// RescheduleBooking is the resolver for the rescheduleBooking field.
func (r *mutationResolver) RescheduleBooking(ctx context.Context, id string, scheduledDate string, scheduledStartTime string, reason *string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bookingID := stringToUUID(id)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bookingID); err != nil {
		return nil, err
	}

	current, err := r.Queries.GetBookingByID(ctx, bookingID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	// Only ASSIGNED or CONFIRMED can be rescheduled.
	if current.Status != db.BookingStatusAssigned && current.Status != db.BookingStatusConfirmed {
		return nil, fmt.Errorf("nu se poate reprograma o comanda cu statusul %s", current.Status)
	}

	// Admin bypasses reschedule count limit.
	isAdmin := claims.Role == "global_admin"
	policy := loadBookingPolicy(ctx, r.Queries)
	if !isAdmin {
		if int(current.RescheduleCount) >= policy.RescheduleMaxPerBooking {
			return nil, fmt.Errorf("ai atins limita maxima de %d reprogramari pentru aceasta comanda", policy.RescheduleMaxPerBooking)
		}
	}

	// Enforce minimum reschedule window (admin bypasses).
	if !isAdmin {
		hoursLeft := hoursUntilBooking(current.ScheduledDate, current.ScheduledStartTime)
		if hoursLeft < float64(policy.RescheduleFreeHoursBefore) {
			return nil, fmt.Errorf("reprogramarea trebuie efectuată cu cel puțin %d ore înainte de serviciu", policy.RescheduleFreeHoursBefore)
		}
	}

	// Parse and validate new date/time.
	newDate, err := time.Parse("2006-01-02", scheduledDate)
	if err != nil {
		return nil, fmt.Errorf("format data invalid: %w", err)
	}
	if newDate.Before(time.Now().Truncate(24 * time.Hour)) {
		return nil, fmt.Errorf("nu se poate programa in trecut")
	}
	newTime, err := time.Parse("15:04", scheduledStartTime)
	if err != nil {
		return nil, fmt.Errorf("format ora invalid: %w", err)
	}

	newDatePg := pgtype.Date{Time: newDate, Valid: true}
	newTimePg := pgtype.Time{
		Microseconds: int64(newTime.Hour())*3_600_000_000 + int64(newTime.Minute())*60_000_000,
		Valid:        true,
	}

	booking, err := r.Queries.RescheduleBooking(ctx, db.RescheduleBookingParams{
		ID:                 bookingID,
		ScheduledDate:      newDatePg,
		ScheduledStartTime: newTimePg,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to reschedule booking: %w", err)
	}

	// Notify all parties asynchronously.
	go func() {
		bgCtx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
		defer cancel()
		r.sendRescheduleNotifications(bgCtx, booking, scheduledDate, scheduledStartTime)
	}()

	result := dbBookingToGQL(booking)
	r.enrichBooking(ctx, booking, result)
	return result, nil
}

// UploadJobPhoto is the resolver for the uploadJobPhoto field.
func (r *mutationResolver) UploadJobPhoto(ctx context.Context, bookingID string, file graphql.Upload, phase string) (*model.BookingJobPhoto, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Validate phase value
	if phase != "before" && phase != "after" && phase != "during" {
		return nil, fmt.Errorf("phase must be 'before', 'after', or 'during'")
	}

	bID := stringToUUID(bookingID)
	booking, err := r.Queries.GetBookingByID(ctx, bID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	// Only the assigned worker or company admin / global admin can upload photos
	switch claims.Role {
	case "worker":
		wID := stringToUUID(claims.UserID)
		w, wErr := r.Queries.GetWorkerByUserID(ctx, wID)
		if wErr != nil || uuidToString(w.ID) != uuidToString(booking.WorkerID) {
			return nil, fmt.Errorf("not authorized: you are not assigned to this booking")
		}
	case "company_admin", "global_admin":
		// allowed
	default:
		return nil, fmt.Errorf("not authorized")
	}

	// Upload to cloud storage with public access (photos are shared with the client)
	path := fmt.Sprintf("uploads/bookings/%s/job-photos", bookingID)
	photoURL, uploadErr := r.Storage.Upload(ctx, path, file.Filename, file.File, storage.StorageTypePublic)
	if uploadErr != nil {
		return nil, fmt.Errorf("failed to upload photo: %w", uploadErr)
	}

	userID := stringToUUID(claims.UserID)
	photo, err := r.Queries.CreateJobPhoto(ctx, db.CreateJobPhotoParams{
		BookingID:  bID,
		UploadedBy: userID,
		PhotoUrl:   photoURL,
		Phase:      phase,
		SortOrder:  0,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to save photo: %w", err)
	}
	return dbJobPhotoToGQL(photo), nil
}

// DeleteJobPhoto is the resolver for the deleteJobPhoto field.
func (r *mutationResolver) DeleteJobPhoto(ctx context.Context, id string) (bool, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return false, fmt.Errorf("not authenticated")
	}

	photo, err := r.Queries.GetJobPhoto(ctx, stringToUUID(id))
	if err != nil {
		return false, fmt.Errorf("photo not found: %w", err)
	}

	// Only the original uploader, company admin, or global admin can delete
	if claims.Role != "company_admin" && claims.Role != "global_admin" {
		if uuidToString(photo.UploadedBy) != claims.UserID {
			return false, fmt.Errorf("not authorized")
		}
	}

	if err := r.Queries.DeleteJobPhoto(ctx, photo.ID); err != nil {
		return false, fmt.Errorf("failed to delete photo: %w", err)
	}
	return true, nil
}

// MyBookings is the resolver for the myBookings field.
func (r *queryResolver) MyBookings(ctx context.Context, status *model.BookingStatus, first *int, after *string) (*model.BookingConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}
	offset := int32(0)
	if after != nil {
		fmt.Sscanf(*after, "%d", &offset)
	}

	clientUID := stringToUUID(claims.UserID)

	var bookings []db.Booking
	var totalCount int64
	var err error
	if status != nil {
		dbStatus := gqlBookingStatusToDb(*status)
		bookings, err = r.Queries.ListBookingsByClientAndStatus(ctx, db.ListBookingsByClientAndStatusParams{
			ClientUserID: clientUID,
			Status:       dbStatus,
			Limit:        limit + 1,
			Offset:       offset,
		})
		if err == nil {
			totalCount, _ = r.Queries.CountBookingsByClientAndStatus(ctx, db.CountBookingsByClientAndStatusParams{
				ClientUserID: clientUID,
				Status:       dbStatus,
			})
		}
	} else {
		bookings, err = r.Queries.ListBookingsByClient(ctx, db.ListBookingsByClientParams{
			ClientUserID: clientUID,
			Limit:        limit + 1,
			Offset:       offset,
		})
		if err == nil {
			totalCount, _ = r.Queries.CountBookingsByClient(ctx, clientUID)
		}
	}
	if err != nil {
		return nil, fmt.Errorf("failed to list bookings: %w", err)
	}

	hasNext := len(bookings) > int(limit)
	if hasNext {
		bookings = bookings[:limit]
	}

	// Build service name map with a single query instead of N queries.
	serviceNameMap := map[string]string{}
	if services, sErr := r.Queries.ListActiveServices(ctx); sErr == nil {
		for _, s := range services {
			serviceNameMap[string(s.ServiceType)] = s.NameRo
		}
	}

	edges := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		gqlBooking := dbBookingToGQL(b)
		if name, ok := serviceNameMap[string(b.ServiceType)]; ok {
			gqlBooking.ServiceName = name
		}
		edges[i] = gqlBooking
	}

	var endCursor *string
	if len(bookings) > 0 {
		c := fmt.Sprintf("%d", offset+limit)
		endCursor = &c
	}

	return &model.BookingConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
		TotalCount: int(totalCount),
	}, nil
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, id string) (*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bookingID := stringToUUID(id)

	// ✅ SECURITY: Check authorization before accessing booking (Phase 3)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bookingID); err != nil {
		return nil, err
	}

	booking, err := r.Queries.GetBookingByID(ctx, bookingID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	result := dbBookingToGQL(booking)
	r.enrichBooking(ctx, booking, result)

	return result, nil
}

// CompanyBookings is the resolver for the companyBookings field.
func (r *queryResolver) CompanyBookings(ctx context.Context, status *model.BookingStatus, first *int, after *string) (*model.BookingConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Look up the company for the current user.
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}
	offset := int32(0)
	if after != nil {
		fmt.Sscanf(*after, "%d", &offset)
	}

	var bookings []db.Booking
	var totalCount int64
	if status != nil {
		dbStatus := gqlBookingStatusToDb(*status)
		bookings, err = r.Queries.ListBookingsByCompanyAndStatus(ctx, db.ListBookingsByCompanyAndStatusParams{
			CompanyID: company.ID,
			Status:    dbStatus,
			Limit:     limit + 1,
			Offset:    offset,
		})
		if err == nil {
			totalCount, _ = r.Queries.CountBookingsByCompanyAndStatus(ctx, db.CountBookingsByCompanyAndStatusParams{
				CompanyID: company.ID,
				Status:    dbStatus,
			})
		}
	} else {
		bookings, err = r.Queries.ListBookingsByCompany(ctx, db.ListBookingsByCompanyParams{
			CompanyID: company.ID,
			Limit:     limit + 1,
			Offset:    offset,
		})
		if err == nil {
			totalCount, _ = r.Queries.CountBookingsByCompany(ctx, company.ID)
		}
	}
	if err != nil {
		return nil, fmt.Errorf("failed to list company bookings: %w", err)
	}

	hasNext := len(bookings) > int(limit)
	if hasNext {
		bookings = bookings[:limit]
	}

	// Build service name map with a single query instead of N queries.
	serviceNameMap := map[string]string{}
	if services, sErr := r.Queries.ListActiveServices(ctx); sErr == nil {
		for _, s := range services {
			serviceNameMap[string(s.ServiceType)] = s.NameRo
		}
	}

	// Collect unique IDs for batch-style lookups.
	clientIDs := map[string]bool{}
	workerIDs := map[string]bool{}
	addressIDs := map[string]bool{}
	for _, b := range bookings {
		if b.ClientUserID.Valid {
			clientIDs[uuidToString(b.ClientUserID)] = true
		}
		if b.WorkerID.Valid {
			workerIDs[uuidToString(b.WorkerID)] = true
		}
		if b.AddressID.Valid {
			addressIDs[uuidToString(b.AddressID)] = true
		}
	}

	// Load unique clients.
	clientMap := map[string]*model.User{}
	for id := range clientIDs {
		if u, uErr := r.Queries.GetUserByID(ctx, stringToUUID(id)); uErr == nil {
			clientMap[id] = dbUserToGQL(u)
		}
	}

	// Load unique workers (lightweight: worker + user for fullName).
	workerMap := map[string]*model.WorkerProfile{}
	for id := range workerIDs {
		if w, wErr := r.Queries.GetWorkerByID(ctx, stringToUUID(id)); wErr == nil {
			if u, uErr := r.Queries.GetUserByID(ctx, w.UserID); uErr == nil {
				workerMap[id] = dbWorkerToGQL(w, &u)
			}
		}
	}

	// Load unique addresses.
	addressMap := map[string]*model.Address{}
	for id := range addressIDs {
		if a, aErr := r.Queries.GetAddressByID(ctx, stringToUUID(id)); aErr == nil {
			addressMap[id] = dbAddressToGQL(a)
		}
	}

	edges := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		gqlBooking := dbBookingToGQL(b)
		if name, ok := serviceNameMap[string(b.ServiceType)]; ok {
			gqlBooking.ServiceName = name
		}
		if b.ClientUserID.Valid {
			gqlBooking.Client = clientMap[uuidToString(b.ClientUserID)]
		}
		if b.WorkerID.Valid {
			gqlBooking.Worker = workerMap[uuidToString(b.WorkerID)]
		}
		if b.AddressID.Valid {
			gqlBooking.Address = addressMap[uuidToString(b.AddressID)]
		}
		edges[i] = gqlBooking
	}

	var endCursor *string
	if len(bookings) > 0 {
		c := fmt.Sprintf("%d", offset+limit)
		endCursor = &c
	}

	return &model.BookingConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
		TotalCount: int(totalCount),
	}, nil
}

// AllBookings is the resolver for the allBookings field.
func (r *queryResolver) AllBookings(ctx context.Context, status *model.BookingStatus, companyID *string, dateFrom *string, dateTo *string, first *int, after *string) (*model.BookingConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}
	offset := int32(0)
	if after != nil {
		fmt.Sscanf(*after, "%d", &offset)
	}

	var bookings []db.Booking
	var err error

	if status != nil {
		bookings, err = r.Queries.ListBookingsByStatus(ctx, db.ListBookingsByStatusParams{
			Status: gqlBookingStatusToDb(*status),
			Limit:  limit + 1,
			Offset: offset,
		})
	} else {
		bookings, err = r.Queries.ListAllBookings(ctx, db.ListAllBookingsParams{
			Limit:  limit + 1,
			Offset: offset,
		})
	}
	if err != nil {
		return nil, fmt.Errorf("failed to list all bookings: %w", err)
	}

	hasNext := len(bookings) > int(limit)
	if hasNext {
		bookings = bookings[:limit]
	}

	edges := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		edges[i] = dbBookingToGQL(b)
	}
	r.enrichBookingsBatch(ctx, bookings, edges)

	var endCursor *string
	if len(bookings) > 0 {
		c := fmt.Sprintf("%d", offset+limit)
		endCursor = &c
	}

	return &model.BookingConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
		TotalCount: len(edges),
	}, nil
}

// CompanyBookingsByDateRange is the resolver for the companyBookingsByDateRange field.
func (r *queryResolver) CompanyBookingsByDateRange(ctx context.Context, from string, to string) ([]*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	fromDate, err := time.Parse("2006-01-02", from)
	if err != nil {
		return nil, fmt.Errorf("invalid 'from' date: %w", err)
	}
	toDate, err := time.Parse("2006-01-02", to)
	if err != nil {
		return nil, fmt.Errorf("invalid 'to' date: %w", err)
	}

	bookings, err := r.Queries.ListBookingsByCompanyAndDateRange(ctx, db.ListBookingsByCompanyAndDateRangeParams{
		CompanyID: company.ID,
		DateFrom:  pgtype.Date{Time: fromDate, Valid: true},
		DateTo:    pgtype.Date{Time: toDate, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list bookings by date range: %w", err)
	}

	result := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		result[i] = dbBookingToGQL(b)
	}
	r.enrichBookingsBatch(ctx, bookings, result)

	return result, nil
}

// SearchCompanyBookings is the resolver for the searchCompanyBookings field.
func (r *queryResolver) SearchCompanyBookings(ctx context.Context, query *string, status *string, dateFrom *string, dateTo *string, limit *int, offset *int) (*model.BookingConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	qLimit := int32(20)
	if limit != nil {
		qLimit = int32(*limit)
	}
	qOffset := int32(0)
	if offset != nil {
		qOffset = int32(*offset)
	}

	var queryStr string
	if query != nil {
		queryStr = *query
	}
	var statusStr string
	if status != nil {
		statusStr = strings.ToLower(*status)
	}

	// Parse date filters — use zero date sentinel to skip filter in SQL.
	zeroDate := pgtype.Date{Time: time.Date(1, 1, 1, 0, 0, 0, 0, time.UTC), Valid: true}
	fromDate := zeroDate
	toDate := zeroDate
	if dateFrom != nil {
		if t, err := time.Parse("2006-01-02", *dateFrom); err == nil {
			fromDate = pgtype.Date{Time: t, Valid: true}
		}
	}
	if dateTo != nil {
		if t, err := time.Parse("2006-01-02", *dateTo); err == nil {
			toDate = pgtype.Date{Time: t, Valid: true}
		}
	}

	bookings, err := r.Queries.SearchCompanyBookings(ctx, db.SearchCompanyBookingsParams{
		CompanyID:    company.ID,
		Limit:        qLimit + 1,
		Offset:       qOffset,
		Query:        queryStr,
		StatusFilter: statusStr,
		DateFrom:     fromDate,
		DateTo:       toDate,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to search company bookings: %w", err)
	}

	hasNext := len(bookings) > int(qLimit)
	if hasNext {
		bookings = bookings[:qLimit]
	}

	// Build service name map (single query) for serviceName field.
	serviceNameMap := map[string]string{}
	if services, sErr := r.Queries.ListActiveServices(ctx); sErr == nil {
		for _, s := range services {
			serviceNameMap[string(s.ServiceType)] = s.NameRo
		}
	}

	edges := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		gqlBooking := dbBookingToGQL(b)
		if name, ok := serviceNameMap[string(b.ServiceType)]; ok {
			gqlBooking.ServiceName = name
		}
		edges[i] = gqlBooking
	}

	// Get total count.
	total, _ := r.Queries.CountSearchCompanyBookings(ctx, db.CountSearchCompanyBookingsParams{
		CompanyID:    company.ID,
		Query:        queryStr,
		StatusFilter: statusStr,
		DateFrom:     fromDate,
		DateTo:       toDate,
	})

	return &model.BookingConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
		},
		TotalCount: int(total),
	}, nil
}

// BookingPolicy is the resolver for the bookingPolicy field.
func (r *queryResolver) BookingPolicy(ctx context.Context) (*model.BookingPolicy, error) {
	p := loadBookingPolicy(ctx, r.Queries)
	return &model.BookingPolicy{
		CancelFreeHoursBefore:     p.CancelFreeHoursBefore,
		CancelLateRefundPct:       p.CancelLateRefundPct,
		CancelNoRefundHoursBefore: p.CancelNoRefundHoursBefore,
		RescheduleFreeHoursBefore: p.RescheduleFreeHoursBefore,
		RescheduleMaxPerBooking:   p.RescheduleMaxPerBooking,
	}, nil
}

// CheckWorkerAvailability is the resolver for the checkWorkerAvailability field.
func (r *queryResolver) CheckWorkerAvailability(ctx context.Context, bookingID string, date string, startTime string) (*model.WorkerAvailabilityCheck, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bID := stringToUUID(bookingID)
	if err := r.AuthzHelper.CanAccessBooking(ctx, bID); err != nil {
		return nil, err
	}

	booking, err := r.Queries.GetBookingByID(ctx, bID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	// If no worker assigned, nothing to check.
	if !booking.WorkerID.Valid {
		return &model.WorkerAvailabilityCheck{Available: true, Conflicts: []string{}}, nil
	}

	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		return nil, fmt.Errorf("invalid date format: %w", err)
	}

	parts := strings.Split(startTime, ":")
	if len(parts) < 2 {
		return nil, fmt.Errorf("invalid time format, expected HH:MM")
	}

	var reqHour, reqMin int
	fmt.Sscanf(parts[0], "%d", &reqHour)
	fmt.Sscanf(parts[1], "%d", &reqMin)
	reqMinutes := reqHour*60 + reqMin

	conflicts := []string{}
	pgDate := pgtype.Date{Time: parsedDate, Valid: true}
	dayOfWeek := int32(parsedDate.Weekday()) // 0=Sunday
	bookingDurationMin := int(numericToFloat(booking.EstimatedDurationHours) * 60)
	reqEnd := reqMinutes + bookingDurationMin

	// 1. Check company work schedule for the day.
	if booking.CompanyID.Valid {
		companySchedule, _ := r.Queries.ListCompanyWorkSchedule(ctx, booking.CompanyID)
		for _, cs := range companySchedule {
			if cs.DayOfWeek == dayOfWeek {
				if !cs.IsWorkDay {
					reason := "Partenerul selectat nu lucreaza in aceasta zi"
					return &model.WorkerAvailabilityCheck{Available: false, Reason: &reason, Conflicts: []string{reason}}, nil
				}
				csStart := int(cs.StartTime.Microseconds / 60_000_000)
				csEnd := int(cs.EndTime.Microseconds / 60_000_000)
				schedStr := fmt.Sprintf("%02d:%02d-%02d:%02d", csStart/60, csStart%60, csEnd/60, csEnd%60)
				if reqMinutes < csStart || reqMinutes >= csEnd {
					reason := fmt.Sprintf("Ora selectata este in afara programului (%s)", schedStr)
					return &model.WorkerAvailabilityCheck{Available: false, Reason: &reason, Conflicts: []string{reason}}, nil
				}
				if reqEnd > csEnd {
					reason := fmt.Sprintf("Comanda depaseste programul — sfarsit estimat %02d:%02d, partenerul inchide la %02d:%02d", reqEnd/60, reqEnd%60, csEnd/60, csEnd%60)
					return &model.WorkerAvailabilityCheck{Available: false, Reason: &reason, Conflicts: []string{reason}}, nil
				}
				break
			}
		}
	}

	// 2. Check worker date override (day off).
	override, err := r.Queries.GetWorkerDateOverride(ctx, db.GetWorkerDateOverrideParams{
		WorkerID:     booking.WorkerID,
		OverrideDate: pgDate,
	})
	if err == nil && !override.IsAvailable {
		reason := "Lucratorul nu este disponibil in aceasta zi (zi libera)"
		return &model.WorkerAvailabilityCheck{Available: false, Reason: &reason, Conflicts: []string{reason}}, nil
	}

	// 3. Check worker weekly availability for day of week.
	availSlots, _ := r.Queries.ListWorkerAvailability(ctx, booking.WorkerID)
	hasSlotForDay := false
	inSchedule := false
	for _, slot := range availSlots {
		if slot.DayOfWeek == dayOfWeek {
			hasSlotForDay = true
			if slot.IsAvailable.Valid && slot.IsAvailable.Bool {
				slotStart := int(slot.StartTime.Microseconds / 60_000_000)
				slotEnd := int(slot.EndTime.Microseconds / 60_000_000)
				if reqMinutes >= slotStart && reqEnd <= slotEnd {
					inSchedule = true
					break
				}
			}
		}
	}
	if hasSlotForDay && !inSchedule {
		reason := "Programarea nu se incadreaza in orarul lucratorului"
		conflicts = append(conflicts, reason)
		return &model.WorkerAvailabilityCheck{Available: false, Reason: &reason, Conflicts: conflicts}, nil
	}

	// 4. Check for conflicting bookings.
	existingBookings, _ := r.Queries.ListWorkerBookingsForDate(ctx, db.ListWorkerBookingsForDateParams{
		WorkerID:      booking.WorkerID,
		ScheduledDate: pgDate,
	})
	for _, eb := range existingBookings {
		// Skip the current booking (it's the one being rescheduled).
		if eb.ID == bID {
			continue
		}
		ebStart := int(eb.ScheduledStartTime.Microseconds / 60_000_000)
		ebDuration := int(numericToFloat(eb.EstimatedDurationHours) * 60)
		ebEnd := ebStart + ebDuration

		if reqMinutes < ebEnd && reqEnd > ebStart {
			conflictTime := fmt.Sprintf("%02d:%02d-%02d:%02d", ebStart/60, ebStart%60, ebEnd/60, ebEnd%60)
			conflicts = append(conflicts, fmt.Sprintf("Conflict cu alta programare (%s)", conflictTime))
		}
	}

	if len(conflicts) > 0 {
		reason := "Lucratorul are alte programari in acest interval"
		return &model.WorkerAvailabilityCheck{Available: false, Reason: &reason, Conflicts: conflicts}, nil
	}

	return &model.WorkerAvailabilityCheck{Available: true, Conflicts: []string{}}, nil
}

// Booking returns graph.BookingResolver implementation.
func (r *Resolver) Booking() graph.BookingResolver { return &bookingResolver{r} }

type bookingResolver struct{ *Resolver }
