package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph"
	"go2fix-backend/internal/graph/model"
	"go2fix-backend/internal/service/notification"
	"go2fix-backend/internal/storage"
	"log"

	"github.com/99designs/gqlgen/graphql"
	"github.com/jackc/pgx/v5/pgtype"
)

// ServiceCategories is the resolver for the serviceCategories field.
func (r *companyResolver) ServiceCategories(ctx context.Context, obj *model.Company) ([]*model.ServiceCategory, error) {
	companyUUID := stringToUUID(obj.ID)
	if !companyUUID.Valid {
		return []*model.ServiceCategory{}, nil
	}
	rows, err := r.Queries.ListCompanyServiceCategories(ctx, companyUUID)
	if err != nil {
		return []*model.ServiceCategory{}, nil
	}
	result := make([]*model.ServiceCategory, len(rows))
	for i, row := range rows {
		result[i] = &model.ServiceCategory{
			ID:     uuidToString(row.CategoryID),
			Slug:   row.Slug,
			NameRo: row.NameRo,
			NameEn: row.NameEn,
			Icon:   textPtr(row.Icon),
		}
	}
	return result, nil
}

// ApplyAsCompany is the resolver for the applyAsCompany field.
func (r *mutationResolver) ApplyAsCompany(ctx context.Context, input model.CompanyApplicationInput) (*model.CompanyApplicationResult, error) {
	// Allow unauthenticated applications; link to user if authenticated.
	var adminUserID pgtype.UUID
	var claimTokenText pgtype.Text

	claims := auth.GetUserFromContext(ctx)
	if claims != nil {
		adminUserID = stringToUUID(claims.UserID)
	} else {
		// Generate a claim token for unauthenticated applications so the user
		// can link their account later.
		tokenBytes := make([]byte, 32)
		if _, err := rand.Read(tokenBytes); err != nil {
			return nil, fmt.Errorf("failed to generate claim token: %w", err)
		}
		claimTokenText = pgtype.Text{String: hex.EncodeToString(tokenBytes), Valid: true}
	}

	var isVatPayerOnboarding bool
	if input.IsVatPayer != nil {
		isVatPayerOnboarding = *input.IsVatPayer
	}

	company, err := r.Queries.CreateCompany(ctx, db.CreateCompanyParams{
		AdminUserID:         adminUserID,
		CompanyName:         input.CompanyName,
		Cui:                 input.Cui,
		CompanyType:         gqlCompanyTypeToDb(input.CompanyType),
		LegalRepresentative: input.LegalRepresentative,
		ContactEmail:        input.ContactEmail,
		ContactPhone:        input.ContactPhone,
		Address:             input.Address,
		City:                input.City,
		County:              input.County,
		Description:         stringToText(input.Description),
		ClaimToken:          claimTokenText,
		RegNumber:           stringToText(input.RegNumber),
		IsVatPayer:          isVatPayerOnboarding,
		BankName:            stringToText(input.BankName),
		Iban:                stringToText(input.Iban),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create company application: %w", err)
	}

	// Assign service categories to the new company.
	if len(input.CategoryIds) > 0 {
		for _, catID := range input.CategoryIds {
			if err := r.Queries.InsertCompanyServiceCategory(ctx, db.InsertCompanyServiceCategoryParams{
				CompanyID:  company.ID,
				CategoryID: stringToUUID(catID),
			}); err != nil {
				log.Printf("failed to assign category %s to company %s: %v", catID, uuidToString(company.ID), err)
			}
		}
	} else {
		// Default to "curatenie" category when no categories specified.
		curatenie, err := r.Queries.GetServiceCategoryBySlug(ctx, "curatenie")
		if err == nil {
			_ = r.Queries.InsertCompanyServiceCategory(ctx, db.InsertCompanyServiceCategoryParams{
				CompanyID:  company.ID,
				CategoryID: curatenie.ID,
			})
		}
	}

	// For authenticated users, upgrade their role to COMPANY_ADMIN immediately.
	// (Unauthenticated users get upgraded later via ClaimCompany.)
	if claims != nil {
		_, err = r.Queries.UpdateUserRole(ctx, db.UpdateUserRoleParams{
			ID:   stringToUUID(claims.UserID),
			Role: db.UserRoleCompanyAdmin,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to upgrade user role: %w", err)
		}
	}

	// Trigger ANAF verification asynchronously — never blocks the mutation response.
	go r.triggerANAFVerification(company.ID, input.Cui)

	// Notify applicant that their application was received.
	if err := r.NotifSvc.DispatchSync(ctx, notification.EventCompanyApplicationReceived,
		notification.Payload{
			"companyName":         company.CompanyName,
			"legalRepresentative": company.LegalRepresentative,
		},
		[]notification.Target{{Email: company.ContactEmail, Name: company.LegalRepresentative}},
	); err != nil {
		log.Printf("[notif] ApplyAsCompany: %v", err)
	}

	result := &model.CompanyApplicationResult{
		Company: dbCompanyToGQL(company),
	}
	if claimTokenText.Valid {
		result.ClaimToken = &claimTokenText.String
	}
	return result, nil
}

// ClaimCompany is the resolver for the claimCompany field.
func (r *mutationResolver) ClaimCompany(ctx context.Context, claimToken string) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.ClaimCompanyByToken(ctx, db.ClaimCompanyByTokenParams{
		AdminUserID: stringToUUID(claims.UserID),
		ClaimToken:  pgtype.Text{String: claimToken, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("invalid or already claimed token: %w", err)
	}

	// Upgrade user role to COMPANY_ADMIN
	_, err = r.Queries.UpdateUserRole(ctx, db.UpdateUserRoleParams{
		ID:   stringToUUID(claims.UserID),
		Role: db.UserRoleCompanyAdmin,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to upgrade user role: %w", err)
	}

	return dbCompanyToGQL(company), nil
}

// UpdateCompanyProfile is the resolver for the updateCompanyProfile field.
func (r *mutationResolver) UpdateCompanyProfile(ctx context.Context, input model.UpdateCompanyInput) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	var desc, phone, email string
	if input.Description != nil {
		desc = *input.Description
	}
	if input.ContactPhone != nil {
		phone = *input.ContactPhone
	}
	if input.ContactEmail != nil {
		email = *input.ContactEmail
	}
	var regNumber, bankName, iban string
	var isVatPayer bool
	if input.RegNumber != nil {
		regNumber = *input.RegNumber
	}
	if input.IsVatPayer != nil {
		isVatPayer = *input.IsVatPayer
	}
	if input.BankName != nil {
		bankName = *input.BankName
	}
	if input.Iban != nil {
		iban = *input.Iban
	}

	updated, err := r.Queries.UpdateCompanyOwnProfile(ctx, db.UpdateCompanyOwnProfileParams{
		ID:           company.ID,
		Description:  desc,
		ContactPhone: phone,
		ContactEmail: email,
		RegNumber:    regNumber,
		IsVatPayer:   isVatPayer,
		BankName:     bankName,
		Iban:         iban,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update company profile: %w", err)
	}

	// Update work schedule if provided.
	if input.WorkSchedule != nil {
		for _, day := range input.WorkSchedule {
			startTime := parseHHMMToTime(day.StartTime)
			endTime := parseHHMMToTime(day.EndTime)
			_, err := r.Queries.UpsertCompanyWorkScheduleDay(ctx, db.UpsertCompanyWorkScheduleDayParams{
				CompanyID: company.ID,
				DayOfWeek: int32(day.DayOfWeek),
				StartTime: startTime,
				EndTime:   endTime,
				IsWorkDay: day.IsWorkDay,
			})
			if err != nil {
				return nil, fmt.Errorf("failed to update work schedule day %d: %w", day.DayOfWeek, err)
			}
		}
	}

	return dbCompanyToGQL(updated), nil
}

// UploadCompanyLogo is the resolver for the uploadCompanyLogo field.
func (r *mutationResolver) UploadCompanyLogo(ctx context.Context, file graphql.Upload) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Get company for this admin user
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found: %w", err)
	}

	// Validate file type (images only)
	if !isImageFile(file.Filename) {
		return nil, fmt.Errorf("doar imagini sunt permise (jpg, png, webp)")
	}

	// Validate file size (max 10MB)
	if file.Size > 10*1024*1024 {
		return nil, fmt.Errorf("fisierul depaseste limita de 10MB")
	}

	// Build GCS path: uploads/companies/{companyId}/logos
	path := fmt.Sprintf("uploads/companies/%s/logos", uuidToString(company.ID))

	// Upload to GCS with public access
	logoURL, err := r.Storage.Upload(ctx, path, file.Filename, file.File, storage.StorageTypePublic)
	if err != nil {
		return nil, fmt.Errorf("eroare la incarcarea logo-ului: %w", err)
	}

	// Update company logo in DB
	updated, err := r.Queries.UpdateCompanyLogo(ctx, db.UpdateCompanyLogoParams{
		ID:      company.ID,
		LogoUrl: stringToText(&logoURL),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update logo: %w", err)
	}

	return dbCompanyToGQL(updated), nil
}

// UploadCompanyDocument is the resolver for the uploadCompanyDocument field.
func (r *mutationResolver) UploadCompanyDocument(ctx context.Context, companyID string, documentType string, file graphql.Upload) (*model.CompanyDocument, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	path := fmt.Sprintf("uploads/companies/%s/documents", companyID)
	fileURL, err := r.Storage.Upload(ctx, path, file.Filename, file.File, storage.StorageTypePrivate)
	if err != nil {
		return nil, fmt.Errorf("failed to upload file: %w", err)
	}

	doc, err := r.Queries.CreateCompanyDocument(ctx, db.CreateCompanyDocumentParams{
		CompanyID:    stringToUUID(companyID),
		DocumentType: documentType,
		FileUrl:      fileURL,
		FileName:     file.Filename,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to save company document: %w", err)
	}

	return dbCompanyDocToGQL(doc), nil
}

// DeleteCompanyDocument is the resolver for the deleteCompanyDocument field.
func (r *mutationResolver) DeleteCompanyDocument(ctx context.Context, id string) (bool, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return false, fmt.Errorf("not authenticated")
	}

	// Verify the document belongs to the caller's company.
	doc, err := r.Queries.GetCompanyDocument(ctx, stringToUUID(id))
	if err != nil {
		return false, fmt.Errorf("document not found: %w", err)
	}

	// Only allow deletion of pending or rejected documents.
	if doc.Status != "pending" && doc.Status != "rejected" {
		return false, fmt.Errorf("cannot delete an approved document")
	}

	// Verify ownership: caller must be admin of the company that owns the doc.
	if claims.Role == "company_admin" {
		company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
		if err != nil || company.ID != doc.CompanyID {
			return false, fmt.Errorf("not authorized")
		}
	} else if claims.Role != "global_admin" {
		return false, fmt.Errorf("not authorized")
	}

	if err := r.Queries.DeleteCompanyDocument(ctx, stringToUUID(id)); err != nil {
		return false, fmt.Errorf("failed to delete document: %w", err)
	}

	return true, nil
}

// ApproveCompany is the resolver for the approveCompany field.
func (r *mutationResolver) ApproveCompany(ctx context.Context, id string) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authenticated or not authorized")
	}

	companyUUID := stringToUUID(id)

	// Check if all required documents are approved
	docsReady, err := r.Queries.CheckCompanyDocumentsReady(ctx, companyUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to check documents: %w", err)
	}

	if !docsReady.Valid || !docsReady.Bool {
		return nil, fmt.Errorf("cannot approve company: all required documents (Certificat Constatator, Asigurare RCA, Document CUI) must be uploaded and approved first")
	}

	company, err := r.Queries.ApproveCompany(ctx, companyUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to approve company: %w", err)
	}

	// Reactivate workers that were suspended when the company was suspended
	_ = r.Queries.ReactivateWorkersByCompany(ctx, companyUUID)

	// Notify company admin and upsert contact.
	{
		targets := []notification.Target{{Email: company.ContactEmail, Name: company.LegalRepresentative}}
		payload := notification.Payload{
			"companyName":         company.CompanyName,
			"legalRepresentative": company.LegalRepresentative,
		}
		if err := r.NotifSvc.DispatchSync(ctx, notification.EventCompanyApproved, payload, targets); err != nil {
			log.Printf("[notif] ApproveCompany: contact email: %v", err)
		}

		// Also notify admin user (linked account) and upsert contact.
		adminUserID, adminEmail, adminName := r.loadCompanyAdmin(ctx, company)
		if adminEmail != "" && adminEmail != company.ContactEmail {
			if err := r.NotifSvc.DispatchSync(ctx, notification.EventCompanyApproved, payload,
				[]notification.Target{{UserID: adminUserID, Email: adminEmail, Name: adminName}},
			); err != nil {
				log.Printf("[notif] ApproveCompany: admin email: %v", err)
			}
		}
		contactEmail := adminEmail
		contactName := adminName
		if contactEmail == "" {
			contactEmail = company.ContactEmail
			contactName = company.LegalRepresentative
		}
		r.NotifSvc.UpsertContact(ctx, notification.ContactData{
			Email:    contactEmail,
			Name:     contactName,
			UserType: "company_admin",
			City:     company.City,
			Status:   "active",
		})
	}

	return dbCompanyToGQL(company), nil
}

// RejectCompany is the resolver for the rejectCompany field.
func (r *mutationResolver) RejectCompany(ctx context.Context, id string, reason string) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	company, err := r.Queries.RejectCompany(ctx, db.RejectCompanyParams{
		ID:              stringToUUID(id),
		RejectionReason: stringToTextVal(reason),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to reject company: %w", err)
	}

	// Notify applicant of rejection.
	{
		adminUserID, _, _ := r.loadCompanyAdmin(ctx, company)
		if err := r.NotifSvc.DispatchSync(ctx, notification.EventCompanyRejected,
			notification.Payload{
				"companyName": company.CompanyName,
				"reason":      reason,
			},
			[]notification.Target{{UserID: adminUserID, Email: company.ContactEmail, Name: company.LegalRepresentative}},
		); err != nil {
			log.Printf("[notif] RejectCompany: %v", err)
		}
	}

	return dbCompanyToGQL(company), nil
}

// SuspendCompany is the resolver for the suspendCompany field.
func (r *mutationResolver) SuspendCompany(ctx context.Context, id string, reason string) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	companyUUID := stringToUUID(id)

	company, err := r.Queries.UpdateCompanyStatus(ctx, db.UpdateCompanyStatusParams{
		ID:     companyUUID,
		Status: db.CompanyStatusSuspended,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to suspend company: %w", err)
	}

	// Cascade: suspend all active workers
	_ = r.Queries.SuspendWorkersByCompany(ctx, companyUUID)

	// Cascade: cancel future bookings
	_, _ = r.Queries.CancelFutureBookingsByCompany(ctx, db.CancelFutureBookingsByCompanyParams{
		CompanyID:          companyUUID,
		CancellationReason: pgtype.Text{String: "Compania a fost suspendată", Valid: true},
	})

	// Cascade: cancel active subscriptions
	_ = r.Queries.CancelSubscriptionsByCompany(ctx, db.CancelSubscriptionsByCompanyParams{
		CompanyID:          companyUUID,
		CancellationReason: pgtype.Text{String: "Compania a fost suspendată", Valid: true},
	})

	// Notify company contact and update contact record.
	{
		adminUserID, adminEmail, adminName := r.loadCompanyAdmin(ctx, company)
		if err := r.NotifSvc.DispatchSync(ctx, notification.EventCompanySuspended,
			notification.Payload{
				"companyName": company.CompanyName,
				"reason":      reason,
			},
			[]notification.Target{{UserID: adminUserID, Email: company.ContactEmail, Name: company.LegalRepresentative}},
		); err != nil {
			log.Printf("[notif] SuspendCompany: %v", err)
		}
		// Update admin user contact status to suspended.
		if adminEmail == "" {
			adminEmail = company.ContactEmail
			adminName = company.LegalRepresentative
		}
		r.NotifSvc.UpsertContact(ctx, notification.ContactData{
			Email:    adminEmail,
			Name:     adminName,
			UserType: "company_admin",
			City:     company.City,
			Status:   "suspended",
		})
	}

	return dbCompanyToGQL(company), nil
}

// ReviewCompanyDocument is the resolver for the reviewCompanyDocument field.
func (r *mutationResolver) ReviewCompanyDocument(ctx context.Context, id string, approved bool, rejectionReason *string) (*model.CompanyDocument, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	status := "approved"
	if !approved {
		status = "rejected"
	}

	var reason pgtype.Text
	if rejectionReason != nil {
		reason = pgtype.Text{String: *rejectionReason, Valid: true}
	}

	doc, err := r.Queries.UpdateCompanyDocumentStatus(ctx, db.UpdateCompanyDocumentStatusParams{
		ID:              stringToUUID(id),
		Status:          status,
		ReviewedBy:      stringToUUID(claims.UserID),
		RejectionReason: reason,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to review document: %w", err)
	}

	// Notify the company admin about the document review result.
	{
		company, compErr := r.Queries.GetCompanyByID(ctx, doc.CompanyID)
		if compErr != nil {
			log.Printf("[notif] reviewDocument: could not load company %s: %v", uuidToString(doc.CompanyID), compErr)
		} else {
			adminUserID, adminEmail, adminName := r.loadCompanyAdmin(ctx, company)
			if adminEmail == "" {
				adminEmail = company.ContactEmail
				adminName = company.LegalRepresentative
			}
			targets := []notification.Target{{UserID: adminUserID, Email: adminEmail, Name: adminName}}
			if approved {
				if err := r.NotifSvc.DispatchSync(ctx, notification.EventDocumentApproved,
					notification.Payload{
						"documentType": doc.DocumentType,
						"companyName":  company.CompanyName,
					},
					targets,
				); err != nil {
					log.Printf("[notif] ReviewCompanyDocument approved: %v", err)
				}
			} else {
				rejectionStr := ""
				if rejectionReason != nil {
					rejectionStr = *rejectionReason
				}
				if err := r.NotifSvc.DispatchSync(ctx, notification.EventDocumentRejected,
					notification.Payload{
						"documentType": doc.DocumentType,
						"reason":       rejectionStr,
						"companyName":  company.CompanyName,
					},
					targets,
				); err != nil {
					log.Printf("[notif] ReviewCompanyDocument rejected: %v", err)
				}
			}
		}
	}

	return dbCompanyDocToGQL(doc), nil
}

// SetCompanyCommissionOverride is the resolver for the setCompanyCommissionOverride field.
func (r *mutationResolver) SetCompanyCommissionOverride(ctx context.Context, id string, pct *float64) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	companyUUID := stringToUUID(id)

	if pct == nil {
		// Clear override
		company, err := r.Queries.ClearCompanyCommissionOverride(ctx, companyUUID)
		if err != nil {
			return nil, fmt.Errorf("failed to clear commission override: %w", err)
		}
		return dbCompanyToGQL(company), nil
	}

	// Validate range
	if *pct < 0 || *pct > 100 {
		return nil, fmt.Errorf("commission percentage must be between 0 and 100")
	}

	// Set override
	company, err := r.Queries.SetCompanyCommissionOverride(ctx, db.SetCompanyCommissionOverrideParams{
		ID:                    companyUUID,
		CommissionOverridePct: float64ToNumeric(*pct),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to set commission override: %w", err)
	}
	return dbCompanyToGQL(company), nil
}

// UpdateCompanyServiceCategories is the resolver for the updateCompanyServiceCategories field.
// Restricted to global_admin only. company_admin must use requestCategoryAccess instead.
// The companyId parameter is required; it identifies which company's categories to update.
func (r *mutationResolver) UpdateCompanyServiceCategories(ctx context.Context, categoryIds []string, companyID *string) ([]*model.ServiceCategory, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized: only global administrators can directly set company categories")
	}
	if companyID == nil || *companyID == "" {
		return nil, fmt.Errorf("companyId is required for global admin")
	}

	company, err := r.Queries.GetCompanyByID(ctx, stringToUUID(*companyID))
	if err != nil {
		return nil, fmt.Errorf("company not found: %w", err)
	}

	// Delete all existing categories and insert the new ones.
	if err := r.Queries.DeleteAllCompanyServiceCategories(ctx, company.ID); err != nil {
		return nil, fmt.Errorf("failed to clear company categories: %w", err)
	}
	for _, catID := range categoryIds {
		if err := r.Queries.InsertCompanyServiceCategory(ctx, db.InsertCompanyServiceCategoryParams{
			CompanyID:  company.ID,
			CategoryID: stringToUUID(catID),
		}); err != nil {
			return nil, fmt.Errorf("failed to assign category: %w", err)
		}
	}

	// Return the updated list.
	rows, err := r.Queries.ListCompanyServiceCategories(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list company categories: %w", err)
	}
	result := make([]*model.ServiceCategory, len(rows))
	for i, row := range rows {
		result[i] = &model.ServiceCategory{
			ID:     uuidToString(row.CategoryID),
			Slug:   row.Slug,
			NameRo: row.NameRo,
			NameEn: row.NameEn,
			Icon:   textPtr(row.Icon),
		}
	}
	return result, nil
}

// VerifyCompanyWithAnaf is the resolver for the verifyCompanyWithANAF field.
// It triggers a synchronous ANAF lookup and returns the updated company.
// Only global admins may call this.
func (r *mutationResolver) VerifyCompanyWithAnaf(ctx context.Context, id string) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	company, err := r.Queries.GetCompanyByID(ctx, stringToUUID(id))
	if err != nil {
		return nil, fmt.Errorf("company not found: %w", err)
	}

	// Run synchronously so the admin immediately sees the refreshed result.
	r.triggerANAFVerification(company.ID, company.Cui)

	updated, err := r.Queries.GetCompanyByID(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to reload company: %w", err)
	}

	result := dbCompanyToGQL(updated)
	r.enrichCompanyStats(ctx, updated.ID, result)
	r.populateCompanyDocuments(ctx, result, updated.ID)
	return result, nil
}

// MyCompany is the resolver for the myCompany field.
func (r *queryResolver) MyCompany(ctx context.Context) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Try finding company already linked to this user.
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err == nil {
		result := dbCompanyToGQL(company)
		r.enrichCompanyStats(ctx, company.ID, result)
		r.populateCompanyDocuments(ctx, result, company.ID)
		return result, nil
	}

	// Auto-claim: find unclaimed company matching the user's email.
	company, err = r.Queries.GetUnclaimedCompanyByContactEmail(ctx, claims.Email)
	if err != nil {
		return nil, fmt.Errorf("company not found: %w", err)
	}

	// Link the company to this user.
	company, err = r.Queries.SetCompanyAdminUser(ctx, db.SetCompanyAdminUserParams{
		AdminUserID: stringToUUID(claims.UserID),
		ID:          company.ID,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to claim company: %w", err)
	}

	// Upgrade user role to COMPANY_ADMIN
	_, err = r.Queries.UpdateUserRole(ctx, db.UpdateUserRoleParams{
		ID:   stringToUUID(claims.UserID),
		Role: db.UserRoleCompanyAdmin,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to upgrade user role: %w", err)
	}

	result := dbCompanyToGQL(company)
	r.enrichCompanyStats(ctx, company.ID, result)
	r.populateCompanyDocuments(ctx, result, company.ID)
	return result, nil
}

// MyCompanyFinancialSummary is the resolver for the myCompanyFinancialSummary field.
func (r *queryResolver) MyCompanyFinancialSummary(ctx context.Context) (*model.CompanyFinancialSummary, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	summary, err := r.Queries.GetCompanyFinancialSummary(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get financial summary: %w", err)
	}

	return &model.CompanyFinancialSummary{
		CompletedBookings: int(summary.CompletedBookings),
		TotalRevenue:      numericToFloat(summary.TotalRevenue),
		TotalCommission:   numericToFloat(summary.TotalCommission),
		NetPayout:         numericToFloat(summary.NetPayout),
	}, nil
}

// MyCompanyWorkSchedule is the resolver for the myCompanyWorkSchedule field.
func (r *queryResolver) MyCompanyWorkSchedule(ctx context.Context) ([]*model.CompanyWorkSchedule, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	rows, err := r.Queries.ListCompanyWorkSchedule(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list work schedule: %w", err)
	}

	result := make([]*model.CompanyWorkSchedule, len(rows))
	for i, row := range rows {
		result[i] = &model.CompanyWorkSchedule{
			ID:        uuidToString(row.ID),
			DayOfWeek: int(row.DayOfWeek),
			StartTime: timeToString(row.StartTime),
			EndTime:   timeToString(row.EndTime),
			IsWorkDay: row.IsWorkDay,
		}
	}
	return result, nil
}

// Companies is the resolver for the companies field.
func (r *queryResolver) Companies(ctx context.Context, status *model.CompanyStatus, first *int, after *string) (*model.CompanyConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	limit := int32(20)
	if first != nil {
		limit = int32(*first)
	}
	offset := int32(0)
	if after != nil {
		fmt.Sscanf(*after, "%d", &offset)
	}

	var companies []db.Company
	var err error

	if status != nil {
		companies, err = r.Queries.ListCompaniesByStatus(ctx, db.ListCompaniesByStatusParams{
			Status: gqlCompanyStatusToDb(*status),
			Limit:  limit + 1,
			Offset: offset,
		})
	} else {
		companies, err = r.Queries.ListAllCompanies(ctx, db.ListAllCompaniesParams{
			Limit:  limit + 1,
			Offset: offset,
		})
	}
	if err != nil {
		return nil, fmt.Errorf("failed to list companies: %w", err)
	}

	hasNext := len(companies) > int(limit)
	if hasNext {
		companies = companies[:limit]
	}

	edges := make([]*model.Company, len(companies))
	for i, c := range companies {
		gqlCompany := dbCompanyToGQL(c)
		r.enrichCompanyStats(ctx, c.ID, gqlCompany)
		edges[i] = gqlCompany
	}

	var endCursor *string
	if len(companies) > 0 {
		c := fmt.Sprintf("%d", offset+limit)
		endCursor = &c
	}

	return &model.CompanyConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
			EndCursor:   endCursor,
		},
		TotalCount: len(edges),
	}, nil
}

// Company is the resolver for the company field.
func (r *queryResolver) Company(ctx context.Context, id string) (*model.Company, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByID(ctx, stringToUUID(id))
	if err != nil {
		return nil, fmt.Errorf("company not found: %w", err)
	}

	result := dbCompanyToGQL(company)
	r.enrichCompanyStats(ctx, company.ID, result)
	r.populateCompanyDocuments(ctx, result, company.ID)

	// Populate workers with User/Company/Documents/PersonalityAssessment relationships.
	if workers, err := r.Queries.ListWorkersByCompany(ctx, company.ID); err == nil {
		for _, c := range workers {
			// Load full worker profile with all relationships
			profile, err := r.workerWithCompany(ctx, c)
			if err != nil {
				log.Printf("Failed to load worker %s for company: %v", uuidToString(c.ID), err)
				continue // Skip broken workers, don't fail entire query
			}
			result.Workers = append(result.Workers, profile)
		}
	}

	return result, nil
}

// PendingCompanyDocuments is the resolver for the pendingCompanyDocuments field.
func (r *queryResolver) PendingCompanyDocuments(ctx context.Context) ([]*model.CompanyDocument, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	docs, err := r.Queries.ListPendingCompanyDocuments(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list pending documents: %w", err)
	}

	result := make([]*model.CompanyDocument, len(docs))
	for i, d := range docs {
		result[i] = dbCompanyDocToGQL(d)
		if company, err := r.Queries.GetCompanyByID(ctx, d.CompanyID); err == nil {
			result[i].Company = dbCompanyToGQL(company)
		}
	}
	return result, nil
}

// GetDocumentURL is the resolver for the getDocumentUrl field.
func (r *queryResolver) GetDocumentURL(ctx context.Context, documentID string) (string, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return "", fmt.Errorf("not authenticated")
	}

	id := stringToUUID(documentID)

	// Try company document first.
	doc, err := r.Queries.GetCompanyDocument(ctx, id)
	if err == nil {
		return r.Storage.GetSignedURL(ctx, doc.FileUrl)
	}

	// Fallback to worker document.
	workerDoc, err := r.Queries.GetWorkerDocument(ctx, id)
	if err != nil {
		return "", fmt.Errorf("document not found")
	}
	return r.Storage.GetSignedURL(ctx, workerDoc.FileUrl)
}

// Company returns graph.CompanyResolver implementation.
func (r *Resolver) Company() graph.CompanyResolver { return &companyResolver{r} }

type companyResolver struct{ *Resolver }
