package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"go2fix-backend/internal/graph/model"
	"log"
	"os"

	resend "github.com/resend/resend-go/v2"
)

// SendContactMessage forwards a contact form submission to the support team and
// sends a confirmation receipt to the submitter.
// In non-production environments the message is only logged.
func (r *mutationResolver) SendContactMessage(ctx context.Context, input model.ContactMessageInput) (bool, error) {
	if os.Getenv("ENVIRONMENT") != "production" {
		log.Printf("[contact] form submission: from=%s (%s) subject=%q message=%q",
			input.Name, input.Email, input.Subject, input.Message)
		return true, nil
	}

	apiKey := os.Getenv("RESEND_API_KEY")
	if apiKey == "" {
		log.Printf("[contact] RESEND_API_KEY not set — dropping contact form from %s", input.Email)
		return true, nil
	}

	from := os.Getenv("RESEND_FROM_EMAIL")
	if from == "" {
		from = "Go2Fix <noreply@go2fix.ro>"
	}

	client := resend.NewClient(apiKey)

	// Forward to support team.
	_, err := client.Emails.Send(&resend.SendEmailRequest{
		From:    from,
		To:      []string{"contact@go2fix.ro"},
		ReplyTo: input.Email,
		Subject: fmt.Sprintf("[Contact] %s — %s", input.Subject, input.Name),
		Html: fmt.Sprintf(`<div style="font-family:'Inter',Arial,sans-serif;max-width:600px;padding:24px;">
<h2 style="color:#2563EB;margin:0 0 16px;">Mesaj nou de la formularul de contact</h2>
<p><strong>Nume:</strong> %s</p>
<p><strong>Email:</strong> %s</p>
<p><strong>Subiect:</strong> %s</p>
<hr style="margin:16px 0;border:none;border-top:1px solid #e5e7eb;">
<p><strong>Mesaj:</strong></p>
<p style="white-space:pre-wrap;color:#374151;">%s</p>
</div>`, input.Name, input.Email, input.Subject, input.Message),
	})
	if err != nil {
		log.Printf("[contact] failed to forward message from %s: %v", input.Email, err)
		return false, nil
	}

	// Confirmation to the submitter (best-effort — do not fail the request if this send fails).
	_, _ = client.Emails.Send(&resend.SendEmailRequest{
		From:    from,
		To:      []string{input.Email},
		Subject: "Am primit mesajul tău — Go2Fix",
		Html: fmt.Sprintf(`<!DOCTYPE html>
<html lang="ro">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background:#FAFBFC;font-family:'Inter',Arial,sans-serif;">
<div style="max-width:480px;margin:40px auto;background:#fff;border-radius:12px;padding:40px;border:1px solid #e5e7eb;">
  <span style="font-size:24px;font-weight:800;color:#2563EB;">Go2Fix</span>
  <h2 style="color:#111827;font-size:20px;font-weight:700;margin:24px 0 8px;">Mesajul tău a fost primit!</h2>
  <p style="color:#6B7280;font-size:14px;margin:0 0 8px;">Salut %s,</p>
  <p style="color:#6B7280;font-size:14px;margin:0 0 24px;">Îți mulțumim că ne-ai contactat. Echipa noastră va răspunde în cel mai scurt timp posibil.</p>
  <p style="color:#9CA3AF;font-size:12px;margin:0;">Echipa Go2Fix</p>
</div>
</body>
</html>`, input.Name),
	})

	return true, nil
}
