package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph/model"
	"go2fix-backend/internal/storage"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// OpenDispute is the resolver for the openDispute field.
func (r *mutationResolver) OpenDispute(ctx context.Context, bookingID string, reason model.DisputeReason, description string, evidenceUrls []string) (*model.BookingDispute, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bUUID := stringToUUID(bookingID)
	callerUUID := stringToUUID(claims.UserID)

	// Load booking and verify ownership.
	booking, err := r.Queries.GetBookingByID(ctx, bUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("booking not found")
		}
		return nil, fmt.Errorf("failed to load booking: %w", err)
	}
	if booking.ClientUserID != callerUUID {
		return nil, fmt.Errorf("not authorized: booking does not belong to you")
	}

	// Only completed bookings can be disputed.
	if booking.Status != db.BookingStatusCompleted {
		return nil, fmt.Errorf("disputes can only be opened for completed bookings")
	}

	// Enforce 24-hour window from completion.
	if booking.CompletedAt.Valid {
		deadline := booking.CompletedAt.Time.Add(24 * time.Hour)
		if time.Now().After(deadline) {
			return nil, fmt.Errorf("dispute window has closed: disputes must be opened within 24 hours of completion")
		}
	}

	// Ensure no duplicate dispute for the same booking.
	if _, err := r.Queries.GetDisputeByBookingID(ctx, bUUID); err == nil {
		return nil, fmt.Errorf("a dispute already exists for this booking")
	}

	// Normalise evidence URLs (nil → empty slice).
	urls := evidenceUrls
	if urls == nil {
		urls = []string{}
	}

	// Map GQL reason enum to DB enum.
	dbReason, err := gqlReasonToDBReason(reason)
	if err != nil {
		return nil, err
	}

	dispute, err := r.Queries.CreateDispute(ctx, db.CreateDisputeParams{
		BookingID:    bUUID,
		OpenedBy:     callerUUID,
		Reason:       dbReason,
		Description:  description,
		EvidenceUrls: urls,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create dispute: %w", err)
	}

	r.dispatchDisputeOpenedNotifications(ctx, booking, dispute)

	return dbDisputeToGQL(dispute), nil
}

// AddDisputeEvidence is the resolver for the addDisputeEvidence field.
func (r *mutationResolver) AddDisputeEvidence(ctx context.Context, disputeID string, evidenceUrls []string) (*model.BookingDispute, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	dUUID := stringToUUID(disputeID)
	callerUUID := stringToUUID(claims.UserID)

	dispute, err := r.Queries.GetDisputeByID(ctx, dUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("dispute not found")
		}
		return nil, fmt.Errorf("failed to load dispute: %w", err)
	}

	// Verify caller owns the booking linked to this dispute.
	booking, err := r.Queries.GetBookingByID(ctx, dispute.BookingID)
	if err != nil {
		return nil, fmt.Errorf("failed to load booking for dispute: %w", err)
	}
	if booking.ClientUserID != callerUUID {
		return nil, fmt.Errorf("not authorized: dispute does not belong to you")
	}

	// Only allow adding evidence while the dispute is still open.
	if dispute.Status != db.DisputeStatusOpen && dispute.Status != db.DisputeStatusCompanyResponded {
		return nil, fmt.Errorf("evidence can only be added to open or company_responded disputes")
	}

	updated, err := r.Queries.AddDisputeEvidenceURLs(ctx, db.AddDisputeEvidenceURLsParams{
		ID:           dUUID,
		EvidenceUrls: evidenceUrls,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to add evidence: %w", err)
	}

	return dbDisputeToGQL(updated), nil
}

// RespondToDispute is the resolver for the respondToDispute field.
func (r *mutationResolver) RespondToDispute(ctx context.Context, disputeID string, response string) (*model.BookingDispute, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "company_admin" {
		return nil, fmt.Errorf("not authorized: company_admin role required")
	}

	dUUID := stringToUUID(disputeID)

	dispute, err := r.Queries.GetDisputeByID(ctx, dUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("dispute not found")
		}
		return nil, fmt.Errorf("failed to load dispute: %w", err)
	}

	// Verify the booking belongs to the caller's company.
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}
	booking, err := r.Queries.GetBookingByID(ctx, dispute.BookingID)
	if err != nil {
		return nil, fmt.Errorf("failed to load booking: %w", err)
	}
	if booking.CompanyID != company.ID {
		return nil, fmt.Errorf("not authorized: booking does not belong to your company")
	}

	// Only allow responding to open disputes.
	if dispute.Status != db.DisputeStatusOpen && dispute.Status != db.DisputeStatusCompanyResponded {
		return nil, fmt.Errorf("cannot respond to a dispute with status %s", dispute.Status)
	}

	updated, err := r.Queries.UpdateDisputeCompanyResponse(ctx, db.UpdateDisputeCompanyResponseParams{
		ID:              dUUID,
		CompanyResponse: pgtype.Text{String: response, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to save company response: %w", err)
	}

	r.dispatchDisputeResponseNotifications(ctx, booking, updated)

	return dbDisputeToGQL(updated), nil
}

// ResolveDispute is the resolver for the resolveDispute field.
func (r *mutationResolver) ResolveDispute(ctx context.Context, disputeID string, status model.DisputeStatus, resolutionNotes string, refundAmount *float64) (*model.BookingDispute, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized: admin access required")
	}

	// Validate the target status is a terminal resolution or under_review.
	dbStatus, err := gqlStatusToDBStatus(status)
	if err != nil {
		return nil, err
	}
	switch dbStatus {
	case db.DisputeStatusResolvedRefundFull,
		db.DisputeStatusResolvedRefundPartial,
		db.DisputeStatusResolvedNoRefund,
		db.DisputeStatusResolvedRemediation,
		db.DisputeStatusAutoClosed,
		db.DisputeStatusUnderReview:
		// valid
	default:
		return nil, fmt.Errorf("invalid resolution status: must be a resolved_ or under_review status")
	}

	dUUID := stringToUUID(disputeID)
	adminUUID := stringToUUID(claims.UserID)

	dispute, err := r.Queries.GetDisputeByID(ctx, dUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("dispute not found")
		}
		return nil, fmt.Errorf("failed to load dispute: %w", err)
	}

	var refundNumeric pgtype.Numeric
	if refundAmount != nil && *refundAmount > 0 {
		refundNumeric = float64ToNumeric(*refundAmount)
	}

	resolved, err := r.Queries.ResolveDispute(ctx, db.ResolveDisputeParams{
		ID:              dUUID,
		Status:          dbStatus,
		ResolutionNotes: pgtype.Text{String: resolutionNotes, Valid: true},
		ResolvedBy:      adminUUID,
		RefundAmount:    refundNumeric,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to resolve dispute: %w", err)
	}

	// Issue a Stripe refund only for monetary refund statuses (not remediation, which is handled offline).
	if refundAmount != nil && *refundAmount > 0 &&
		(dbStatus == db.DisputeStatusResolvedRefundFull || dbStatus == db.DisputeStatusResolvedRefundPartial) {
		r.issueDisputeRefund(ctx, dispute.BookingID, *refundAmount)
	}

	r.dispatchDisputeResolvedNotification(ctx, dispute.BookingID, resolved)

	return dbDisputeToGQL(resolved), nil
}

// UploadDisputeEvidence is the resolver for the uploadDisputeEvidence field.
func (r *mutationResolver) UploadDisputeEvidence(ctx context.Context, file graphql.Upload) (*model.UploadResult, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	userIDStr := claims.UserID
	path := fmt.Sprintf("disputes/%s/photos", userIDStr)
	url, err := r.Storage.Upload(ctx, path, file.Filename, file.File, storage.StorageTypePrivate)
	if err != nil {
		return nil, fmt.Errorf("dispute evidence: upload failed: %w", err)
	}
	return &model.UploadResult{URL: url, FileName: file.Filename}, nil
}

// MyDisputeForBooking is the resolver for the myDisputeForBooking field.
func (r *queryResolver) MyDisputeForBooking(ctx context.Context, bookingID string) (*model.BookingDispute, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bUUID := stringToUUID(bookingID)
	callerUUID := stringToUUID(claims.UserID)

	// Verify the caller owns the booking.
	booking, err := r.Queries.GetBookingByID(ctx, bUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, fmt.Errorf("booking not found")
		}
		return nil, fmt.Errorf("failed to load booking: %w", err)
	}
	if booking.ClientUserID != callerUUID {
		return nil, fmt.Errorf("not authorized: booking does not belong to you")
	}

	dispute, err := r.Queries.GetDisputeByBookingID(ctx, bUUID)
	if err != nil {
		if err == pgx.ErrNoRows {
			return nil, nil // no dispute yet — return nil gracefully
		}
		return nil, fmt.Errorf("failed to load dispute: %w", err)
	}

	return dbDisputeToGQL(dispute), nil
}

// AllDisputes is the resolver for the allDisputes field.
func (r *queryResolver) AllDisputes(ctx context.Context, status *model.DisputeStatus, first *int, after *string) (*model.DisputeConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized: admin access required")
	}

	lim := int32(50)
	if first != nil && *first > 0 {
		lim = int32(*first)
	}
	// Cursor-based pagination is not implemented; after is ignored for now.
	off := int32(0)

	var (
		rows  []db.BookingDispute
		total int64
	)

	if status != nil {
		dbStatus, err := gqlStatusToDBStatus(*status)
		if err != nil {
			return nil, err
		}
		rows, err = r.Queries.ListDisputesByStatus(ctx, db.ListDisputesByStatusParams{
			Status: dbStatus,
			Limit:  lim,
			Offset: off,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to list disputes: %w", err)
		}
		total, err = r.Queries.CountDisputesByStatus(ctx, dbStatus)
		if err != nil {
			return nil, fmt.Errorf("failed to count disputes: %w", err)
		}
	} else {
		var err error
		rows, err = r.Queries.ListAllDisputes(ctx, db.ListAllDisputesParams{
			Limit:  lim,
			Offset: off,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to list disputes: %w", err)
		}
		total, err = r.Queries.CountAllDisputes(ctx)
		if err != nil {
			return nil, fmt.Errorf("failed to count disputes: %w", err)
		}
	}

	edges := make([]*model.BookingDispute, 0, len(rows))
	for _, d := range rows {
		gqlDispute := dbDisputeToGQL(d)

		// Enrich openedBy with full user data so fullName is populated.
		if openedByUser, err := r.Queries.GetUserByID(ctx, d.OpenedBy); err == nil {
			gqlDispute.OpenedBy = dbUserToGQL(openedByUser)
		}

		// Enrich resolvedBy if present.
		if d.ResolvedBy.Valid {
			if resolvedByUser, err := r.Queries.GetUserByID(ctx, d.ResolvedBy); err == nil {
				gqlDispute.ResolvedBy = dbUserToGQL(resolvedByUser)
			}
		}

		edges = append(edges, gqlDispute)
	}

	hasNext := len(edges) >= int(lim)
	endCursor := fmt.Sprintf("%d", off+int32(len(edges)))
	return &model.DisputeConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
			EndCursor:   &endCursor,
		},
		TotalCount: int(total),
	}, nil
}
