package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph/model"
	"strings"
)

// CreateCity is the resolver for the createCity field.
func (r *mutationResolver) CreateCity(ctx context.Context, name string, county string) (*model.EnabledCity, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	city, err := r.Queries.CreateCity(ctx, db.CreateCityParams{
		Name:   name,
		County: county,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create city: %w", err)
	}

	return r.dbCityToGQL(ctx, cityRowFromCreate(city))
}

// ToggleCityActive is the resolver for the toggleCityActive field.
func (r *mutationResolver) ToggleCityActive(ctx context.Context, id string, isActive bool) (*model.EnabledCity, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	city, err := r.Queries.UpdateCityActive(ctx, db.UpdateCityActiveParams{
		ID:       stringToUUID(id),
		IsActive: isActive,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to toggle city: %w", err)
	}

	return r.dbCityToGQL(ctx, cityRowFromUpdateActive(city))
}

// UpdateCityPricingMultiplier is the resolver for the updateCityPricingMultiplier field.
func (r *mutationResolver) UpdateCityPricingMultiplier(ctx context.Context, id string, pricingMultiplier float64) (*model.EnabledCity, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	if pricingMultiplier < 0.50 || pricingMultiplier > 3.00 {
		return nil, fmt.Errorf("pricing multiplier must be between 0.50 and 3.00")
	}

	city, err := r.Queries.UpdateCityPricingMultiplier(ctx, db.UpdateCityPricingMultiplierParams{
		ID:                stringToUUID(id),
		PricingMultiplier: float64ToNumeric(pricingMultiplier),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update city pricing multiplier: %w", err)
	}

	return r.dbCityToGQL(ctx, cityRowFromUpdatePricing(city))
}

// CreateCityArea is the resolver for the createCityArea field.
func (r *mutationResolver) CreateCityArea(ctx context.Context, cityID string, name string) (*model.CityArea, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	area, err := r.Queries.CreateArea(ctx, db.CreateAreaParams{
		CityID: stringToUUID(cityID),
		Name:   name,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create area: %w", err)
	}

	// Look up city name for the response.
	city, err := r.Queries.GetCityByID(ctx, area.CityID)
	if err != nil {
		return nil, fmt.Errorf("failed to load city: %w", err)
	}

	return &model.CityArea{
		ID:       uuidToString(area.ID),
		Name:     area.Name,
		CityID:   uuidToString(area.CityID),
		CityName: city.Name,
	}, nil
}

// DeleteCityArea is the resolver for the deleteCityArea field.
func (r *mutationResolver) DeleteCityArea(ctx context.Context, id string) (bool, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return false, fmt.Errorf("admin access required")
	}

	err := r.Queries.DeleteArea(ctx, stringToUUID(id))
	if err != nil {
		return false, fmt.Errorf("failed to delete area: %w", err)
	}

	return true, nil
}

// UpdateCompanyServiceAreas is the resolver for the updateCompanyServiceAreas field.
func (r *mutationResolver) UpdateCompanyServiceAreas(ctx context.Context, areaIds []string) ([]*model.CityArea, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user")
	}

	// Delete all existing areas, then insert new ones.
	if err := r.Queries.DeleteAllCompanyServiceAreas(ctx, company.ID); err != nil {
		return nil, fmt.Errorf("failed to clear service areas: %w", err)
	}

	for _, areaID := range areaIds {
		_, err := r.Queries.InsertCompanyServiceArea(ctx, db.InsertCompanyServiceAreaParams{
			CompanyID:  company.ID,
			CityAreaID: stringToUUID(areaID),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to add area %s: %w", areaID, err)
		}
	}

	// Return updated list.
	rows, err := r.Queries.ListCompanyServiceAreas(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list areas: %w", err)
	}

	var result []*model.CityArea
	for _, row := range rows {
		result = append(result, &model.CityArea{
			ID:       uuidToString(row.CityAreaID),
			Name:     row.AreaName,
			CityID:   uuidToString(row.CityID),
			CityName: row.CityName,
		})
	}
	return result, nil
}

// UpdateWorkerServiceAreas is the resolver for the updateWorkerServiceAreas field.
func (r *mutationResolver) UpdateWorkerServiceAreas(ctx context.Context, workerID string, areaIds []string) ([]*model.CityArea, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "company_admin" && claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	wID := stringToUUID(workerID)

	// Delete all existing worker areas, then insert new ones.
	if err := r.Queries.DeleteAllWorkerServiceAreas(ctx, wID); err != nil {
		return nil, fmt.Errorf("failed to clear worker service areas: %w", err)
	}

	for _, areaID := range areaIds {
		_, err := r.Queries.InsertWorkerServiceArea(ctx, db.InsertWorkerServiceAreaParams{
			WorkerID:   wID,
			CityAreaID: stringToUUID(areaID),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to add area %s: %w", areaID, err)
		}
	}

	// Return updated list.
	rows, err := r.Queries.ListWorkerServiceAreas(ctx, wID)
	if err != nil {
		return nil, fmt.Errorf("failed to list worker areas: %w", err)
	}

	var result []*model.CityArea
	for _, row := range rows {
		result = append(result, &model.CityArea{
			ID:       uuidToString(row.CityAreaID),
			Name:     row.AreaName,
			CityID:   uuidToString(row.CityID),
			CityName: row.CityName,
		})
	}
	return result, nil
}

// ActiveCities is the resolver for the activeCities field.
func (r *queryResolver) ActiveCities(ctx context.Context) ([]*model.EnabledCity, error) {
	cities, err := r.Queries.ListActiveCities(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list active cities: %w", err)
	}

	var result []*model.EnabledCity
	for _, c := range cities {
		gqlCity, err := r.dbCityToGQL(ctx, cityRowFromListActive(c))
		if err != nil {
			return nil, err
		}
		result = append(result, gqlCity)
	}
	return result, nil
}

// CityAreas is the resolver for the cityAreas field.
func (r *queryResolver) CityAreas(ctx context.Context, cityID string) ([]*model.CityArea, error) {
	rows, err := r.Queries.ListAreasByCity(ctx, stringToUUID(cityID))
	if err != nil {
		return nil, fmt.Errorf("failed to list areas: %w", err)
	}

	var result []*model.CityArea
	for _, row := range rows {
		result = append(result, &model.CityArea{
			ID:       uuidToString(row.ID),
			Name:     row.Name,
			CityID:   uuidToString(row.CityID),
			CityName: row.CityName,
		})
	}
	return result, nil
}

// AllCities is the resolver for the allCities field.
func (r *queryResolver) AllCities(ctx context.Context) ([]*model.EnabledCity, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("admin access required")
	}

	cities, err := r.Queries.ListEnabledCities(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list cities: %w", err)
	}

	var result []*model.EnabledCity
	for _, c := range cities {
		gqlCity, err := r.dbCityToGQL(ctx, cityRowFromListEnabled(c))
		if err != nil {
			return nil, err
		}
		result = append(result, gqlCity)
	}
	return result, nil
}

// MyCompanyServiceAreas is the resolver for the myCompanyServiceAreas field.
func (r *queryResolver) MyCompanyServiceAreas(ctx context.Context) ([]*model.CityArea, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user")
	}

	rows, err := r.Queries.ListCompanyServiceAreas(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list company areas: %w", err)
	}

	var result []*model.CityArea
	for _, row := range rows {
		result = append(result, &model.CityArea{
			ID:       uuidToString(row.CityAreaID),
			Name:     row.AreaName,
			CityID:   uuidToString(row.CityID),
			CityName: row.CityName,
		})
	}
	return result, nil
}

// WorkerServiceAreas is the resolver for the workerServiceAreas field.
func (r *queryResolver) WorkerServiceAreas(ctx context.Context, workerID string) ([]*model.CityArea, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	return r.workerServiceAreasWithFallback(ctx, stringToUUID(workerID))
}

// MyWorkerServiceAreas is the resolver for the myWorkerServiceAreas field.
func (r *queryResolver) MyWorkerServiceAreas(ctx context.Context) ([]*model.CityArea, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found")
	}

	return r.workerServiceAreasWithFallback(ctx, worker.ID)
}

// SuggestWorkers is the resolver for the suggestWorkers field.
func (r *queryResolver) SuggestWorkers(ctx context.Context, cityID string, areaID string, timeSlots []*model.TimeSlotInput, estimatedDurationHours float64) ([]*model.WorkerSuggestion, error) {
	areaUUID := stringToUUID(areaID)
	if !areaUUID.Valid {
		return nil, fmt.Errorf("invalid area ID")
	}
	return r.suggestWorkersForSlots(ctx, areaUUID, timeSlots, estimatedDurationHours)
}

// IsCitySupported is the resolver for the isCitySupported field.
func (r *queryResolver) IsCitySupported(ctx context.Context, city string) (bool, error) {
	_, err := r.Queries.GetCityByName(ctx, strings.TrimSpace(city))
	if err != nil {
		return false, nil // Not found = not supported.
	}
	return true, nil
}
