package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph"
	"go2fix-backend/internal/graph/model"
	"go2fix-backend/internal/personality"
	personalityService "go2fix-backend/internal/service/personality"
)

// SubmitPersonalityAssessment is the resolver for the submitPersonalityAssessment field.
func (r *mutationResolver) SubmitPersonalityAssessment(ctx context.Context, answers []*model.PersonalityAnswerInput) (*model.PersonalityAssessment, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Get the worker profile for this user.
	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	// Must be in PENDING_REVIEW status.
	if string(worker.Status) != "pending_review" {
		return nil, fmt.Errorf("assessment can only be taken during pending review")
	}

	// Check not already submitted.
	has, err := r.Queries.HasPersonalityAssessment(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to check existing assessment: %w", err)
	}
	if has {
		return nil, fmt.Errorf("personality assessment already completed")
	}

	// Convert input to scorer format.
	submitted := make([]personality.SubmittedAnswer, len(answers))
	for i, a := range answers {
		submitted[i] = personality.SubmittedAnswer{
			QuestionNumber: a.QuestionNumber,
			Response:       a.Response,
		}
	}

	// Score the assessment.
	result, err := personality.ScoreAssessment(submitted)
	if err != nil {
		return nil, fmt.Errorf("invalid assessment: %w", err)
	}

	// Use a transaction for atomic insert of assessment + answers.
	tx, err := r.Pool.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}
	defer tx.Rollback(ctx)

	qtx := r.Queries.WithTx(tx)

	// Insert the assessment.
	assessment, err := qtx.CreatePersonalityAssessment(ctx, db.CreatePersonalityAssessmentParams{
		WorkerID:            worker.ID,
		TrustScore:          int32(result.FacetScores["A1"].Score),
		MoralityScore:       int32(result.FacetScores["A2"].Score),
		AltruismScore:       int32(result.FacetScores["A3"].Score),
		OrderlinessScore:    int32(result.FacetScores["C2"].Score),
		DutifulnessScore:    int32(result.FacetScores["C3"].Score),
		SelfDisciplineScore: int32(result.FacetScores["C5"].Score),
		CautiousnessScore:   int32(result.FacetScores["C6"].Score),
		IntegrityAvg:        float64ToNumeric(result.IntegrityAvg),
		WorkQualityAvg:      float64ToNumeric(result.WorkQualityAvg),
		HasConcerns:         result.HasConcerns,
		FlaggedFacets:       result.FlaggedFacets,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to save assessment: %w", err)
	}

	// Insert individual answers.
	for _, sa := range result.ScoredAnswers {
		err := qtx.CreatePersonalityAnswer(ctx, db.CreatePersonalityAnswerParams{
			AssessmentID:   assessment.ID,
			QuestionNumber: int32(sa.QuestionNumber),
			FacetCode:      sa.FacetCode,
			IsReverseKeyed: sa.IsReverseKeyed,
			RawResponse:    int32(sa.RawResponse),
			ScoredValue:    int32(sa.ScoredValue),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to save answer %d: %w", sa.QuestionNumber, err)
		}
	}

	if err := tx.Commit(ctx); err != nil {
		return nil, fmt.Errorf("failed to commit: %w", err)
	}

	return dbPersonalityAssessmentToGQL(assessment), nil
}

// GeneratePersonalityInsights is the resolver for the generatePersonalityInsights field.
func (r *mutationResolver) GeneratePersonalityInsights(ctx context.Context, workerID string) (*model.PersonalityInsights, error) {
	// Auth check: GLOBAL_ADMIN only
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("unauthorized: global admin access required")
	}

	// Get assessment for this worker
	assessment, err := r.Queries.GetPersonalityAssessmentByWorkerID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("personality assessment not found for worker: %w", err)
	}

	// Check if insights already cached
	existingInsight, err := r.Queries.GetPersonalityInsightByAssessmentID(ctx, assessment.ID)
	if err == nil {
		// Already generated - return cached
		return dbPersonalityInsightsToGQL(existingInsight), nil
	}

	// Generate new insights via AI service
	aiSvc := personalityService.NewService()
	insights, err := aiSvc.GenerateInsights(ctx, personalityService.InsightRequest{
		FacetScores: map[string]int{
			"A1": int(assessment.TrustScore),
			"A2": int(assessment.MoralityScore),
			"A3": int(assessment.AltruismScore),
			"C2": int(assessment.OrderlinessScore),
			"C3": int(assessment.DutifulnessScore),
			"C5": int(assessment.SelfDisciplineScore),
			"C6": int(assessment.CautiousnessScore),
		},
		IntegrityAvg:   numericToFloat(assessment.IntegrityAvg),
		WorkQualityAvg: numericToFloat(assessment.WorkQualityAvg),
		FlaggedFacets:  assessment.FlaggedFacets,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate AI insights: %w", err)
	}

	// Cache in database
	cached, err := r.Queries.CreatePersonalityInsight(ctx, db.CreatePersonalityInsightParams{
		AssessmentID:      assessment.ID,
		Summary:           insights.Summary,
		Strengths:         insights.Strengths,
		Concerns:          insights.Concerns,
		TeamFitAnalysis:   insights.TeamFitAnalysis,
		RecommendedAction: insights.RecommendedAction,
		Confidence:        insights.Confidence,
		AiModel:           "gemini-2.5-flash-lite",
		AiProvider:        "google",
	})
	if err != nil {
		return nil, fmt.Errorf("failed to cache insights: %w", err)
	}

	return dbPersonalityInsightsToGQL(cached), nil
}

// RegeneratePersonalityInsights is the resolver for the regeneratePersonalityInsights field.
func (r *mutationResolver) RegeneratePersonalityInsights(ctx context.Context, workerID string) (*model.PersonalityInsights, error) {
	// Auth check: GLOBAL_ADMIN only
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("unauthorized: global admin access required")
	}

	// Get assessment for this worker
	assessment, err := r.Queries.GetPersonalityAssessmentByWorkerID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("personality assessment not found for worker: %w", err)
	}

	// Delete existing insights (if any)
	_ = r.Queries.DeletePersonalityInsight(ctx, assessment.ID)

	// Generate new insights via AI service
	aiSvc := personalityService.NewService()
	insights, err := aiSvc.GenerateInsights(ctx, personalityService.InsightRequest{
		FacetScores: map[string]int{
			"A1": int(assessment.TrustScore),
			"A2": int(assessment.MoralityScore),
			"A3": int(assessment.AltruismScore),
			"C2": int(assessment.OrderlinessScore),
			"C3": int(assessment.DutifulnessScore),
			"C5": int(assessment.SelfDisciplineScore),
			"C6": int(assessment.CautiousnessScore),
		},
		IntegrityAvg:   numericToFloat(assessment.IntegrityAvg),
		WorkQualityAvg: numericToFloat(assessment.WorkQualityAvg),
		FlaggedFacets:  assessment.FlaggedFacets,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to generate AI insights: %w", err)
	}

	// Cache in database
	cached, err := r.Queries.CreatePersonalityInsight(ctx, db.CreatePersonalityInsightParams{
		AssessmentID:      assessment.ID,
		Summary:           insights.Summary,
		Strengths:         insights.Strengths,
		Concerns:          insights.Concerns,
		TeamFitAnalysis:   insights.TeamFitAnalysis,
		RecommendedAction: insights.RecommendedAction,
		Confidence:        insights.Confidence,
		AiModel:           "gemini-2.5-flash-lite",
		AiProvider:        "google",
	})
	if err != nil {
		return nil, fmt.Errorf("failed to cache insights: %w", err)
	}

	return dbPersonalityInsightsToGQL(cached), nil
}

// Insights is the resolver for the insights field.
func (r *personalityAssessmentResolver) Insights(ctx context.Context, obj *model.PersonalityAssessment) (*model.PersonalityInsights, error) {
	// Try to get cached insights
	assessmentUUID := stringToUUID(obj.ID)
	insight, err := r.Queries.GetPersonalityInsightByAssessmentID(ctx, assessmentUUID)
	if err != nil {
		return nil, nil // No insights generated yet - return nil (optional field)
	}

	return dbPersonalityInsightsToGQL(insight), nil
}

// PersonalityQuestions is the resolver for the personalityQuestions field.
func (r *queryResolver) PersonalityQuestions(ctx context.Context) ([]*model.PersonalityQuestion, error) {
	questions := make([]*model.PersonalityQuestion, len(personality.Questions))
	for i, q := range personality.Questions {
		questions[i] = &model.PersonalityQuestion{
			Number:    q.Number,
			FacetCode: q.FacetCode,
			Text:      q.TextRO,
		}
	}
	return questions, nil
}

// MyPersonalityAssessment is the resolver for the myPersonalityAssessment field.
func (r *queryResolver) MyPersonalityAssessment(ctx context.Context) (*model.PersonalityAssessment, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, nil // No worker profile → no assessment.
	}

	assessment, err := r.Queries.GetPersonalityAssessmentByWorkerID(ctx, worker.ID)
	if err != nil {
		return nil, nil // No assessment yet.
	}

	return dbPersonalityAssessmentToGQL(assessment), nil
}

// WorkerPersonalityAssessment is the resolver for the workerPersonalityAssessment field.
func (r *queryResolver) WorkerPersonalityAssessment(ctx context.Context, workerID string) (*model.PersonalityAssessment, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "company_admin" && claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	assessment, err := r.Queries.GetPersonalityAssessmentByWorkerID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, nil // No assessment yet.
	}

	return dbPersonalityAssessmentToGQL(assessment), nil
}

// PersonalityAssessment returns graph.PersonalityAssessmentResolver implementation.
func (r *Resolver) PersonalityAssessment() graph.PersonalityAssessmentResolver {
	return &personalityAssessmentResolver{r}
}

type personalityAssessmentResolver struct{ *Resolver }
