package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph/model"
)

// SubmitReview is the resolver for the submitReview field.
func (r *mutationResolver) SubmitReview(ctx context.Context, input model.SubmitReviewInput) (*model.Review, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	bookingUUID := stringToUUID(input.BookingID)

	// Get the booking to determine the worker.
	booking, err := r.Queries.GetBookingByID(ctx, bookingUUID)
	if err != nil {
		return nil, fmt.Errorf("booking not found: %w", err)
	}

	review, err := r.Queries.CreateReview(ctx, db.CreateReviewParams{
		BookingID:        bookingUUID,
		ReviewerUserID:   stringToUUID(claims.UserID),
		ReviewedUserID:   booking.ClientUserID,
		ReviewedWorkerID: booking.WorkerID,
		Rating:           int32(input.Rating),
		Comment:          stringToText(input.Comment),
		ReviewType:       "client_to_worker",
	})
	if err != nil {
		return nil, fmt.Errorf("failed to submit review: %w", err)
	}

	return dbReviewToGQL(review), nil
}
