package resolver

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"go2fix-backend/internal/auth"
	db "go2fix-backend/internal/db/generated"
	"go2fix-backend/internal/graph"
	"go2fix-backend/internal/graph/model"
	"go2fix-backend/internal/service/notification"
	"go2fix-backend/internal/storage"
	"log"
	"strings"
	"time"

	"github.com/99designs/gqlgen/graphql"
	"github.com/jackc/pgx/v5/pgtype"
)

// InviteWorker is the resolver for the inviteWorker field.
func (r *mutationResolver) InviteWorker(ctx context.Context, input model.InviteWorkerInput) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Get the company for this admin user
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("you need to register your company before inviting workers")
	}

	// Verify company is approved before allowing worker invitations
	if company.Status != db.CompanyStatusApproved {
		return nil, fmt.Errorf("your company is not yet approved. only approved companies can invite workers")
	}

	// Step 1: Create User record with pending status
	user, err := r.Queries.CreateWorkerUser(ctx, db.CreateWorkerUserParams{
		Email:    input.Email,
		FullName: input.FullName,
		Phone:    stringToText(input.Phone),
		Status:   db.UserStatusPending, // Pending until invitation accepted
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create user for worker: %w", err)
	}

	// Step 2: Generate invite token
	tokenBytes := make([]byte, 32)
	if _, err := rand.Read(tokenBytes); err != nil {
		return nil, fmt.Errorf("failed to generate invite token: %w", err)
	}
	inviteToken := "inv-" + hex.EncodeToString(tokenBytes)

	// Step 3: Create Worker profile linked to user
	worker, err := r.Queries.CreateWorkerProfile(ctx, db.CreateWorkerProfileParams{
		UserID:         user.ID,
		CompanyID:      company.ID,
		Status:         db.WorkerStatusInvited,
		IsCompanyAdmin: pgtype.Bool{Bool: false, Valid: true},
		InviteToken:    stringToTextVal(inviteToken),
		InviteExpiresAt: pgtype.Timestamptz{
			Time:  time.Now().Add(7 * 24 * time.Hour),
			Valid: true,
		},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create worker profile: %w", err)
	}

	// Auto-assign all company service areas to the new worker
	r.copyCompanyAreasToWorkerHelper(ctx, company.ID, worker.ID)

	// Notify the invited worker by email and upsert contact (non-blocking).
	workerInviteToken := textVal(worker.InviteToken)
	go func() {
		inviteToken := workerInviteToken
		acceptURL := buildInviteURL(inviteToken)
		r.NotifSvc.Dispatch(notification.EventWorkerInvited,
			notification.Payload{
				"companyName": company.CompanyName,
				"workerName":  input.FullName,
				"inviteToken": inviteToken,
				"acceptUrl":   acceptURL,
			},
			[]notification.Target{{Email: input.Email, Name: input.FullName}},
		)
		r.NotifSvc.UpsertContact(context.Background(), notification.ContactData{
			Email:    input.Email,
			Name:     input.FullName,
			UserType: "worker",
			Status:   "active",
		})
	}()

	return r.workerWithCompany(ctx, worker)
}

// InviteSelfAsWorker is the resolver for the inviteSelfAsWorker field.
func (r *mutationResolver) InviteSelfAsWorker(ctx context.Context) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Get the company for this admin user
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	userID := stringToUUID(claims.UserID)

	// Create worker profile linked to current user (no need to create new user)
	worker, err := r.Queries.CreateWorkerProfile(ctx, db.CreateWorkerProfileParams{
		UserID:          userID,
		CompanyID:       company.ID,
		Status:          db.WorkerStatusActive,
		IsCompanyAdmin:  pgtype.Bool{Bool: true, Valid: true},
		InviteToken:     pgtype.Text{},        // No token needed
		InviteExpiresAt: pgtype.Timestamptz{}, // No expiration
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create worker profile: %w", err)
	}

	// Upgrade user role to worker
	_, err = r.Queries.UpdateUserRole(ctx, db.UpdateUserRoleParams{
		ID:   userID,
		Role: db.UserRoleWorker,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to upgrade user role: %w", err)
	}

	// Auto-assign all company service areas to the new worker
	r.copyCompanyAreasToWorkerHelper(ctx, company.ID, worker.ID)

	return r.workerWithCompany(ctx, worker)
}

// UpdateWorkerStatus is the resolver for the updateWorkerStatus field.
func (r *mutationResolver) UpdateWorkerStatus(ctx context.Context, id string, status model.WorkerStatus) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.UpdateWorkerStatus(ctx, db.UpdateWorkerStatusParams{
		ID:     stringToUUID(id),
		Status: gqlWorkerStatusToDb(status),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update worker status: %w", err)
	}

	return r.workerWithCompany(ctx, worker)
}

// AcceptInvitation is the resolver for the acceptInvitation field.
func (r *mutationResolver) AcceptInvitation(ctx context.Context, token string) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Look up worker by invite token
	worker, err := r.Queries.GetWorkerByInviteToken(ctx, stringToTextVal(token))
	if err != nil {
		return nil, fmt.Errorf("invalid invitation token: %w", err)
	}

	currentUserID := stringToUUID(claims.UserID)

	// Security check: if the invitation was issued for a specific user (UserID is set),
	// verify that the authenticated caller's email matches the intended recipient's email.
	// This prevents any logged-in user from hijacking an invitation meant for someone else.
	if worker.UserID.Valid {
		invitedUser, err := r.Queries.GetUserByID(ctx, worker.UserID)
		if err != nil {
			return nil, fmt.Errorf("invalid invitation: could not verify intended recipient: %w", err)
		}
		if !strings.EqualFold(invitedUser.Email, claims.Email) {
			return nil, fmt.Errorf("Această invitație a fost trimisă la o altă adresă de email.")
		}
	}

	// Case 1: Invited worker has their own pending user, accepting user is different
	// Transfer the worker association to the current user and delete pending user
	if worker.UserID.Valid && uuidToString(worker.UserID) != claims.UserID {
		pendingUserID := worker.UserID

		// Link worker to current user
		worker, err = r.Queries.LinkWorkerToUser(ctx, db.LinkWorkerToUserParams{
			ID:     worker.ID,
			UserID: currentUserID,
		})
		if err != nil {
			return nil, fmt.Errorf("failed to link worker to user: %w", err)
		}

		// Delete the pending user (no longer needed)
		if err := r.Queries.DeleteUser(ctx, pendingUserID); err != nil {
			// Non-fatal - log but continue
			fmt.Printf("Warning: failed to delete pending user %s: %v\n", uuidToString(pendingUserID), err)
		}
	}

	// Set worker status to pending_review (requires personality test, documents, and admin approval)
	worker, err = r.Queries.UpdateWorkerStatus(ctx, db.UpdateWorkerStatusParams{
		ID:     worker.ID,
		Status: db.WorkerStatusPendingReview,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update worker status: %w", err)
	}

	// Upgrade user role
	_, err = r.Queries.UpdateUserRole(ctx, db.UpdateUserRoleParams{
		ID:   currentUserID,
		Role: db.UserRoleWorker,
	})
	if err != nil {
		fmt.Printf("Warning: failed to upgrade user role: %v\n", err)
	}

	// Activate user status
	_, err = r.Queries.UpdateUserStatus(ctx, db.UpdateUserStatusParams{
		ID:     currentUserID,
		Status: db.UserStatusActive,
	})
	if err != nil {
		fmt.Printf("Warning: failed to activate user: %v\n", err)
	}

	// Notify company admin that the worker accepted the invitation.
	go func(w db.Worker) {
		bgCtx := context.Background()
		company, cErr := r.Queries.GetCompanyByID(bgCtx, w.CompanyID)
		if cErr != nil || !company.AdminUserID.Valid {
			return
		}
		if _, nErr := r.Queries.CreateNotification(bgCtx, db.CreateNotificationParams{
			UserID: company.AdminUserID,
			Type:   db.NotificationTypeWorkerAccepted,
			Title:  "Lucrător a acceptat invitația",
			Body:   "Un lucrător a acceptat invitația și și-a creat profilul. Verificați profilul pentru aprobare.",
			Data:   []byte(fmt.Sprintf(`{"workerId":"%s"}`, uuidToString(w.ID))),
		}); nErr != nil {
			log.Printf("acceptInvitation: failed to notify company admin: %v", nErr)
		}
	}(worker)

	return r.workerWithCompany(ctx, worker)
}

// UpdateAvailability is the resolver for the updateAvailability field.
func (r *mutationResolver) UpdateAvailability(ctx context.Context, slots []*model.AvailabilitySlotInput) ([]*model.AvailabilitySlot, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	// Delete existing availability and recreate.
	err = r.Queries.DeleteWorkerAvailability(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to clear availability: %w", err)
	}

	var result []*model.AvailabilitySlot
	for _, slot := range slots {
		// Parse start time.
		startTime, _ := time.Parse("15:04", slot.StartTime)
		endTime, _ := time.Parse("15:04", slot.EndTime)

		avail, err := r.Queries.SetWorkerAvailability(ctx, db.SetWorkerAvailabilityParams{
			WorkerID:  worker.ID,
			DayOfWeek: int32(slot.DayOfWeek),
			StartTime: pgtype.Time{
				Microseconds: int64(startTime.Hour())*3_600_000_000 + int64(startTime.Minute())*60_000_000,
				Valid:        true,
			},
			EndTime: pgtype.Time{
				Microseconds: int64(endTime.Hour())*3_600_000_000 + int64(endTime.Minute())*60_000_000,
				Valid:        true,
			},
			IsAvailable: pgtype.Bool{Bool: slot.IsAvailable, Valid: true},
		})
		if err != nil {
			return nil, fmt.Errorf("failed to set availability: %w", err)
		}

		result = append(result, &model.AvailabilitySlot{
			ID:          uuidToString(avail.ID),
			DayOfWeek:   int(avail.DayOfWeek),
			StartTime:   timeToString(avail.StartTime),
			EndTime:     timeToString(avail.EndTime),
			IsAvailable: boolVal(avail.IsAvailable),
		})
	}

	return result, nil
}

// UpdateWorkerAvailability is the resolver for the updateWorkerAvailability field.
func (r *mutationResolver) UpdateWorkerAvailability(ctx context.Context, workerID string, slots []*model.AvailabilitySlotInput) ([]*model.AvailabilitySlot, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Verify the worker belongs to the company admin's company.
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	worker, err := r.Queries.GetWorkerByID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("worker not found: %w", err)
	}

	if worker.CompanyID != company.ID {
		return nil, fmt.Errorf("worker does not belong to your company")
	}

	// Delete existing availability and recreate.
	err = r.Queries.DeleteWorkerAvailability(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to clear availability: %w", err)
	}

	var result []*model.AvailabilitySlot
	for _, slot := range slots {
		startTime, _ := time.Parse("15:04", slot.StartTime)
		endTime, _ := time.Parse("15:04", slot.EndTime)

		avail, err := r.Queries.SetWorkerAvailability(ctx, db.SetWorkerAvailabilityParams{
			WorkerID:  worker.ID,
			DayOfWeek: int32(slot.DayOfWeek),
			StartTime: pgtype.Time{
				Microseconds: int64(startTime.Hour())*3_600_000_000 + int64(startTime.Minute())*60_000_000,
				Valid:        true,
			},
			EndTime: pgtype.Time{
				Microseconds: int64(endTime.Hour())*3_600_000_000 + int64(endTime.Minute())*60_000_000,
				Valid:        true,
			},
			IsAvailable: pgtype.Bool{Bool: slot.IsAvailable, Valid: true},
		})
		if err != nil {
			return nil, fmt.Errorf("failed to set availability: %w", err)
		}

		result = append(result, &model.AvailabilitySlot{
			ID:          uuidToString(avail.ID),
			DayOfWeek:   int(avail.DayOfWeek),
			StartTime:   timeToString(avail.StartTime),
			EndTime:     timeToString(avail.EndTime),
			IsAvailable: boolVal(avail.IsAvailable),
		})
	}

	return result, nil
}

// UpdateWorkerProfile is the resolver for the updateWorkerProfile field.
func (r *mutationResolver) UpdateWorkerProfile(ctx context.Context, input model.UpdateWorkerProfileInput) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	if input.Bio != nil {
		worker, err = r.Queries.UpdateWorkerBio(ctx, db.UpdateWorkerBioParams{
			ID:  worker.ID,
			Bio: stringToText(input.Bio),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to update bio: %w", err)
		}
	}

	if input.Phone != nil {
		_, err = r.Queries.UpdateUserPhone(ctx, db.UpdateUserPhoneParams{
			ID:    stringToUUID(claims.UserID),
			Phone: stringToText(input.Phone),
		})
		if err != nil {
			return nil, fmt.Errorf("failed to update phone: %w", err)
		}
	}

	return r.workerWithCompany(ctx, worker)
}

// UploadWorkerAvatar is the resolver for the uploadWorkerAvatar field.
func (r *mutationResolver) UploadWorkerAvatar(ctx context.Context, workerID string, file graphql.Upload) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Get worker record
	worker, err := r.Queries.GetWorkerByID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("worker not found: %w", err)
	}

	// Authorization: user must be the worker OR company admin OR global admin
	isOwnProfile := worker.UserID.Valid && uuidToString(worker.UserID) == claims.UserID
	isCompanyAdmin := false
	if claims.Role == "company_admin" {
		company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
		if err == nil {
			isCompanyAdmin = company.ID == worker.CompanyID
		}
	}

	if !isOwnProfile && !isCompanyAdmin && claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	// Validate file type (images only)
	if !isImageFile(file.Filename) {
		return nil, fmt.Errorf("doar imagini sunt permise (jpg, png, webp)")
	}

	// Validate file size (max 10MB)
	if file.Size > 10*1024*1024 {
		return nil, fmt.Errorf("fisierul depaseste limita de 10MB")
	}

	// Build GCS path: uploads/users/{userId}/avatars (avatar belongs to user, not worker)
	path := fmt.Sprintf("uploads/users/%s/avatars", uuidToString(worker.UserID))

	// Upload to GCS with public access
	avatarURL, err := r.Storage.Upload(ctx, path, file.Filename, file.File, storage.StorageTypePublic)
	if err != nil {
		return nil, fmt.Errorf("eroare la incarcarea imaginii: %w", err)
	}

	// Update USER's avatar (not worker's) - avatar is a user-level attribute
	_, err = r.Queries.UpdateUserAvatar(ctx, db.UpdateUserAvatarParams{
		ID:        stringToUUID(uuidToString(worker.UserID)),
		AvatarUrl: stringToText(&avatarURL),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update avatar: %w", err)
	}

	// Refetch worker to return updated profile
	updated, err := r.Queries.GetWorkerByID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("failed to refetch worker: %w", err)
	}

	return r.workerWithCompany(ctx, updated)
}

// SetWorkerDateOverride is the resolver for the setWorkerDateOverride field.
func (r *mutationResolver) SetWorkerDateOverride(ctx context.Context, date string, isAvailable bool, startTime string, endTime string) (*model.WorkerDateOverride, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		return nil, fmt.Errorf("invalid date format: %w", err)
	}

	row, err := r.Queries.UpsertWorkerDateOverride(ctx, db.UpsertWorkerDateOverrideParams{
		WorkerID:     worker.ID,
		OverrideDate: pgtype.Date{Time: parsedDate, Valid: true},
		IsAvailable:  isAvailable,
		StartTime:    parseHHMMToTime(startTime),
		EndTime:      parseHHMMToTime(endTime),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to set date override: %w", err)
	}

	return &model.WorkerDateOverride{
		ID:          uuidToString(row.ID),
		Date:        dateToString(row.OverrideDate),
		IsAvailable: row.IsAvailable,
		StartTime:   timeToString(row.StartTime),
		EndTime:     timeToString(row.EndTime),
	}, nil
}

// SetWorkerDateOverrideByAdmin is the resolver for the setWorkerDateOverrideByAdmin field.
func (r *mutationResolver) SetWorkerDateOverrideByAdmin(ctx context.Context, workerID string, date string, isAvailable bool, startTime string, endTime string) (*model.WorkerDateOverride, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Verify the caller is a company admin.
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	// Verify the worker belongs to the admin's company.
	worker, err := r.Queries.GetWorkerByID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("worker not found: %w", err)
	}

	if worker.CompanyID != company.ID {
		return nil, fmt.Errorf("worker does not belong to your company")
	}

	parsedDate, err := time.Parse("2006-01-02", date)
	if err != nil {
		return nil, fmt.Errorf("invalid date format: %w", err)
	}

	row, err := r.Queries.UpsertWorkerDateOverride(ctx, db.UpsertWorkerDateOverrideParams{
		WorkerID:     worker.ID,
		OverrideDate: pgtype.Date{Time: parsedDate, Valid: true},
		IsAvailable:  isAvailable,
		StartTime:    parseHHMMToTime(startTime),
		EndTime:      parseHHMMToTime(endTime),
	})
	if err != nil {
		return nil, fmt.Errorf("failed to set date override: %w", err)
	}

	return &model.WorkerDateOverride{
		ID:          uuidToString(row.ID),
		Date:        dateToString(row.OverrideDate),
		IsAvailable: row.IsAvailable,
		StartTime:   timeToString(row.StartTime),
		EndTime:     timeToString(row.EndTime),
	}, nil
}

// UploadWorkerDocument is the resolver for the uploadWorkerDocument field.
func (r *mutationResolver) UploadWorkerDocument(ctx context.Context, workerID string, documentType string, file graphql.Upload) (*model.WorkerDocument, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Get the worker record
	worker, err := r.Queries.GetWorkerByID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("worker not found: %w", err)
	}

	// Authorization: Either the worker's own user OR the company admin OR global admin
	isOwnWorker := worker.UserID.Valid && uuidToString(worker.UserID) == claims.UserID

	var isCompanyAdmin bool
	if !isOwnWorker {
		// Check if user is company admin for this worker's company
		company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
		if err == nil && uuidToString(company.ID) == uuidToString(worker.CompanyID) {
			isCompanyAdmin = true
		}
	}

	if !isOwnWorker && !isCompanyAdmin && claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized to upload documents for this worker")
	}

	path := fmt.Sprintf("uploads/workers/%s/documents", workerID)
	fileURL, err := r.Storage.Upload(ctx, path, file.Filename, file.File, storage.StorageTypePrivate)
	if err != nil {
		return nil, fmt.Errorf("failed to upload file: %w", err)
	}

	doc, err := r.Queries.CreateWorkerDocument(ctx, db.CreateWorkerDocumentParams{
		WorkerID:     stringToUUID(workerID),
		DocumentType: documentType,
		FileUrl:      fileURL,
		FileName:     file.Filename,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to save worker document: %w", err)
	}

	return dbWorkerDocToGQL(doc), nil
}

// DeleteWorkerDocument is the resolver for the deleteWorkerDocument field.
func (r *mutationResolver) DeleteWorkerDocument(ctx context.Context, id string) (bool, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return false, fmt.Errorf("not authenticated")
	}

	if err := r.Queries.DeleteWorkerDocument(ctx, stringToUUID(id)); err != nil {
		return false, fmt.Errorf("failed to delete document: %w", err)
	}
	return true, nil
}

// ReviewWorkerDocument is the resolver for the reviewWorkerDocument field.
func (r *mutationResolver) ReviewWorkerDocument(ctx context.Context, id string, approved bool, rejectionReason *string) (*model.WorkerDocument, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	status := "approved"
	if !approved {
		status = "rejected"
	}

	var reason pgtype.Text
	if rejectionReason != nil {
		reason = pgtype.Text{String: *rejectionReason, Valid: true}
	}

	doc, err := r.Queries.UpdateWorkerDocumentStatus(ctx, db.UpdateWorkerDocumentStatusParams{
		ID:              stringToUUID(id),
		Status:          status,
		ReviewedBy:      stringToUUID(claims.UserID),
		RejectionReason: reason,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to review document: %w", err)
	}

	return dbWorkerDocToGQL(doc), nil
}

// ActivateWorker is the resolver for the activateWorker field.
func (r *mutationResolver) ActivateWorker(ctx context.Context, id string) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	// Require personality assessment before activation.
	workerUUID := stringToUUID(id)
	has, err := r.Queries.HasPersonalityAssessment(ctx, workerUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to check personality assessment: %w", err)
	}
	if !has {
		return nil, fmt.Errorf("worker must complete personality assessment before activation")
	}

	worker, err := r.Queries.ActivateWorkerStatus(ctx, workerUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to activate worker: %w", err)
	}

	// Notify the worker's linked user account that they've been activated.
	if worker.UserID.Valid {
		go func(userID pgtype.UUID) {
			if _, nErr := r.Queries.CreateNotification(context.Background(), db.CreateNotificationParams{
				UserID: userID,
				Type:   db.NotificationTypeWorkerActivated,
				Title:  "Cont activat!",
				Body:   "Felicitări! Contul tău de lucrător a fost aprobat. Poți începe să primești comenzi.",
				Data:   []byte(fmt.Sprintf(`{"workerId":"%s"}`, uuidToString(worker.ID))),
			}); nErr != nil {
				log.Printf("activateWorker: failed to notify worker: %v", nErr)
			}
		}(worker.UserID)
	}

	return r.workerWithCompany(ctx, worker)
}

// UpdateWorkerServiceCategories is the resolver for the updateWorkerServiceCategories field.
func (r *mutationResolver) UpdateWorkerServiceCategories(ctx context.Context, workerID string, categoryIds []string) ([]*model.ServiceCategory, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}
	if claims.Role != "company_admin" && claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	workerUUID := stringToUUID(workerID)

	// Company admin can only update workers from their own company.
	if claims.Role == "company_admin" {
		company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
		if err != nil {
			return nil, fmt.Errorf("company not found for user")
		}
		worker, err := r.Queries.GetWorkerByID(ctx, workerUUID)
		if err != nil {
			return nil, fmt.Errorf("worker not found: %w", err)
		}
		if uuidToString(worker.CompanyID) != uuidToString(company.ID) {
			return nil, fmt.Errorf("worker does not belong to your company")
		}
	}

	// Delete all existing categories and insert the new ones.
	if err := r.Queries.DeleteAllWorkerServiceCategories(ctx, workerUUID); err != nil {
		return nil, fmt.Errorf("failed to clear worker categories: %w", err)
	}
	for _, catID := range categoryIds {
		if err := r.Queries.InsertWorkerServiceCategory(ctx, db.InsertWorkerServiceCategoryParams{
			WorkerID:   workerUUID,
			CategoryID: stringToUUID(catID),
		}); err != nil {
			return nil, fmt.Errorf("failed to assign category: %w", err)
		}
	}

	// Return the updated list.
	rows, err := r.Queries.ListWorkerServiceCategories(ctx, workerUUID)
	if err != nil {
		return nil, fmt.Errorf("failed to list worker categories: %w", err)
	}
	result := make([]*model.ServiceCategory, len(rows))
	for i, row := range rows {
		result[i] = &model.ServiceCategory{
			ID:     uuidToString(row.CategoryID),
			Slug:   row.Slug,
			NameRo: row.NameRo,
			NameEn: row.NameEn,
			Icon:   textPtr(row.Icon),
		}
	}
	return result, nil
}

// UpdateWorkerMaxDailyBookings is the resolver for the updateWorkerMaxDailyBookings field.
func (r *mutationResolver) UpdateWorkerMaxDailyBookings(ctx context.Context, workerID string, limit *int) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || (claims.Role != "company_admin" && claims.Role != "global_admin") {
		return nil, fmt.Errorf("not authorized")
	}

	wID := stringToUUID(workerID)
	var maxBookings pgtype.Int4
	if limit != nil {
		maxBookings = pgtype.Int4{Int32: int32(*limit), Valid: true}
	} else {
		maxBookings = pgtype.Int4{Valid: false}
	}

	worker, err := r.Queries.UpdateWorkerMaxDailyBookings(ctx, db.UpdateWorkerMaxDailyBookingsParams{
		ID:               wID,
		MaxDailyBookings: maxBookings,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to update worker: %w", err)
	}

	return r.workerWithCompany(ctx, worker)
}

// MyWorkers is the resolver for the myWorkers field.
func (r *queryResolver) MyWorkers(ctx context.Context) ([]*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user. please register your company first: %w", err)
	}

	workers, err := r.Queries.ListWorkersByCompany(ctx, company.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list workers: %w", err)
	}

	// Batch-load users for all workers (1 query per unique user, not per worker).
	userMap := map[string]db.User{}
	for _, c := range workers {
		if c.UserID.Valid {
			uid := uuidToString(c.UserID)
			if _, exists := userMap[uid]; !exists {
				if u, uErr := r.Queries.GetUserByID(ctx, c.UserID); uErr == nil {
					userMap[uid] = u
				}
			}
		}
	}

	result := make([]*model.WorkerProfile, len(workers))
	for i, c := range workers {
		var uPtr *db.User
		if c.UserID.Valid {
			if u, ok := userMap[uuidToString(c.UserID)]; ok {
				uPtr = &u
			}
		}
		profile := dbWorkerToGQL(c, uPtr)
		if uPtr != nil {
			profile.User = dbUserToGQL(*uPtr)
		}
		// Compute worker stats dynamically from reviews/bookings
		r.enrichWorkerStats(ctx, c.ID, profile)
		result[i] = profile
	}

	return result, nil
}

// MyWorkerProfile is the resolver for the myWorkerProfile field.
func (r *queryResolver) MyWorkerProfile(ctx context.Context) (*model.WorkerProfile, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	return r.workerWithCompany(ctx, worker)
}

// MyWorkerStats is the resolver for the myWorkerStats field.
func (r *queryResolver) MyWorkerStats(ctx context.Context) (*model.WorkerStats, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	avgRating, err := r.Queries.GetAverageWorkerRating(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to get average rating: %w", err)
	}

	reviews, err := r.Queries.ListReviewsByWorkerID(ctx, db.ListReviewsByWorkerIDParams{
		ReviewedWorkerID: worker.ID,
		Limit:            1000,
		Offset:           0,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list reviews: %w", err)
	}

	completedCount, err := r.Queries.CountCompletedJobsByWorker(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to count completed jobs: %w", err)
	}

	thisMonthJobs, err := r.Queries.CountThisMonthJobsByWorker(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to count this month jobs: %w", err)
	}

	thisMonthEarnings, err := r.Queries.SumThisMonthEarningsByWorker(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to sum this month earnings: %w", err)
	}

	return &model.WorkerStats{
		TotalJobsCompleted: int(completedCount),
		AverageRating:      numericToFloat(avgRating),
		TotalReviews:       len(reviews),
		ThisMonthJobs:      int(thisMonthJobs),
		ThisMonthEarnings:  numericToFloat(thisMonthEarnings),
	}, nil
}

// WorkerPerformance is the resolver for the workerPerformance field.
func (r *queryResolver) WorkerPerformance(ctx context.Context, workerID string) (*model.WorkerPerformance, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	stats, err := r.Queries.GetWorkerPerformanceStats(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("failed to get worker performance: %w", err)
	}

	return &model.WorkerPerformance{
		WorkerID:           workerID,
		FullName:           stats.FullName,
		RatingAvg:          numericToFloat(stats.RatingAvg),
		TotalCompletedJobs: int(stats.TotalCompletedJobs),
		ThisMonthCompleted: int(stats.ThisMonthCompleted),
		TotalEarnings:      numericToFloat(stats.TotalEarnings),
		ThisMonthEarnings:  numericToFloat(stats.ThisMonthEarnings),
	}, nil
}

// MyWorkerAvailability is the resolver for the myWorkerAvailability field.
func (r *queryResolver) MyWorkerAvailability(ctx context.Context) ([]*model.AvailabilitySlot, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	avails, err := r.Queries.ListWorkerAvailability(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to list availability: %w", err)
	}

	result := make([]*model.AvailabilitySlot, len(avails))
	for i, a := range avails {
		result[i] = &model.AvailabilitySlot{
			ID:          uuidToString(a.ID),
			DayOfWeek:   int(a.DayOfWeek),
			StartTime:   timeToString(a.StartTime),
			EndTime:     timeToString(a.EndTime),
			IsAvailable: boolVal(a.IsAvailable),
		}
	}
	return result, nil
}

// MyWorkerBookingsByDateRange is the resolver for the myWorkerBookingsByDateRange field.
func (r *queryResolver) MyWorkerBookingsByDateRange(ctx context.Context, from string, to string) ([]*model.Booking, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	fromDate, err := time.Parse("2006-01-02", from)
	if err != nil {
		return nil, fmt.Errorf("invalid 'from' date: %w", err)
	}
	toDate, err := time.Parse("2006-01-02", to)
	if err != nil {
		return nil, fmt.Errorf("invalid 'to' date: %w", err)
	}

	bookings, err := r.Queries.ListBookingsByWorkerAndDateRange(ctx, db.ListBookingsByWorkerAndDateRangeParams{
		WorkerID: worker.ID,
		DateFrom: pgtype.Date{Time: fromDate, Valid: true},
		DateTo:   pgtype.Date{Time: toDate, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list bookings: %w", err)
	}

	result := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		gqlBooking := dbBookingToGQL(b)
		r.enrichBooking(ctx, b, gqlBooking)
		result[i] = gqlBooking
	}
	return result, nil
}

// WorkerEarningsByDateRange is the resolver for the workerEarningsByDateRange field.
func (r *queryResolver) WorkerEarningsByDateRange(ctx context.Context, from string, to string) ([]*model.WorkerDailyEarnings, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	fromDate, err := time.Parse("2006-01-02", from)
	if err != nil {
		return nil, fmt.Errorf("invalid 'from' date: %w", err)
	}
	toDate, err := time.Parse("2006-01-02", to)
	if err != nil {
		return nil, fmt.Errorf("invalid 'to' date: %w", err)
	}

	rows, err := r.Queries.GetWorkerEarningsByDateRange(ctx, db.GetWorkerEarningsByDateRangeParams{
		WorkerID:      worker.ID,
		CompletedAt:   pgtype.Timestamptz{Time: fromDate, Valid: true},
		CompletedAt_2: pgtype.Timestamptz{Time: toDate.Add(24 * time.Hour), Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to get earnings: %w", err)
	}

	result := make([]*model.WorkerDailyEarnings, len(rows))
	for i, row := range rows {
		result[i] = &model.WorkerDailyEarnings{
			Date:   row.Date.Time.Format("2006-01-02"),
			Amount: numericToFloat(row.Amount),
		}
	}
	return result, nil
}

// SearchWorkerBookings is the resolver for the searchWorkerBookings field.
func (r *queryResolver) SearchWorkerBookings(ctx context.Context, query *string, status *string, dateFrom *string, dateTo *string, limit *int, offset *int) (*model.BookingConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	qLimit := int32(20)
	if limit != nil {
		qLimit = int32(*limit)
	}
	qOffset := int32(0)
	if offset != nil {
		qOffset = int32(*offset)
	}

	var queryStr string
	if query != nil {
		queryStr = *query
	}
	var statusStr string
	if status != nil {
		statusStr = strings.ToLower(*status)
	}

	zeroDate := pgtype.Date{Time: time.Date(1, 1, 1, 0, 0, 0, 0, time.UTC), Valid: true}
	fromDate := zeroDate
	toDate := zeroDate
	if dateFrom != nil {
		if t, err := time.Parse("2006-01-02", *dateFrom); err == nil {
			fromDate = pgtype.Date{Time: t, Valid: true}
		}
	}
	if dateTo != nil {
		if t, err := time.Parse("2006-01-02", *dateTo); err == nil {
			toDate = pgtype.Date{Time: t, Valid: true}
		}
	}

	bookings, err := r.Queries.SearchWorkerBookings(ctx, db.SearchWorkerBookingsParams{
		WorkerID:     worker.ID,
		Limit:        qLimit + 1,
		Offset:       qOffset,
		Query:        queryStr,
		StatusFilter: statusStr,
		DateFrom:     fromDate,
		DateTo:       toDate,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to search worker bookings: %w", err)
	}

	hasNext := len(bookings) > int(qLimit)
	if hasNext {
		bookings = bookings[:qLimit]
	}

	// Batch-load clients and addresses (list only needs these two).
	clientIDs := map[string]bool{}
	addressIDs := map[string]bool{}
	for _, b := range bookings {
		clientIDs[uuidToString(b.ClientUserID)] = true
		if b.AddressID.Valid {
			addressIDs[uuidToString(b.AddressID)] = true
		}
	}
	clientMap := map[string]*model.User{}
	for cid := range clientIDs {
		if u, uErr := r.Queries.GetUserByID(ctx, stringToUUID(cid)); uErr == nil {
			clientMap[cid] = dbUserToGQL(u)
		}
	}
	addressMap := map[string]*model.Address{}
	for aid := range addressIDs {
		if a, aErr := r.Queries.GetAddressByID(ctx, stringToUUID(aid)); aErr == nil {
			addressMap[aid] = dbAddressToGQL(a)
		}
	}

	// Build service name map (single query).
	serviceNameMap := map[string]string{}
	if services, sErr := r.Queries.ListActiveServices(ctx); sErr == nil {
		for _, s := range services {
			serviceNameMap[string(s.ServiceType)] = s.NameRo
		}
	}

	edges := make([]*model.Booking, len(bookings))
	for i, b := range bookings {
		gqlBooking := dbBookingToGQL(b)
		if name, ok := serviceNameMap[string(b.ServiceType)]; ok {
			gqlBooking.ServiceName = name
		}
		if u, ok := clientMap[uuidToString(b.ClientUserID)]; ok {
			gqlBooking.Client = u
		}
		if b.AddressID.Valid {
			if a, ok := addressMap[uuidToString(b.AddressID)]; ok {
				gqlBooking.Address = a
			}
		}
		edges[i] = gqlBooking
	}

	total, _ := r.Queries.CountSearchWorkerBookings(ctx, db.CountSearchWorkerBookingsParams{
		WorkerID:     worker.ID,
		Query:        queryStr,
		StatusFilter: statusStr,
		DateFrom:     fromDate,
		DateTo:       toDate,
	})

	return &model.BookingConnection{
		Edges: edges,
		PageInfo: &model.PageInfo{
			HasNextPage: hasNext,
		},
		TotalCount: int(total),
	}, nil
}

// MyWorkerReviews is the resolver for the myWorkerReviews field.
func (r *queryResolver) MyWorkerReviews(ctx context.Context, limit *int, offset *int) (*model.ReviewConnection, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	l := int32(20)
	if limit != nil {
		l = int32(*limit)
	}
	o := int32(0)
	if offset != nil {
		o = int32(*offset)
	}

	dbReviews, err := r.Queries.ListReviewsByWorkerID(ctx, db.ListReviewsByWorkerIDParams{
		ReviewedWorkerID: worker.ID,
		Limit:            l,
		Offset:           o,
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list reviews: %w", err)
	}

	count, err := r.Queries.CountReviewsByWorkerID(ctx, worker.ID)
	if err != nil {
		return nil, fmt.Errorf("failed to count reviews: %w", err)
	}

	reviews := make([]*model.Review, len(dbReviews))
	for i, rv := range dbReviews {
		review := dbReviewToGQL(rv)
		if booking, bErr := r.Queries.GetBookingByID(ctx, rv.BookingID); bErr == nil {
			review.Booking = dbBookingToGQL(booking)
		}
		if rv.ReviewerUserID.Valid {
			if user, uErr := r.Queries.GetUserByID(ctx, rv.ReviewerUserID); uErr == nil {
				review.Reviewer = dbUserToGQL(user)
			}
		}
		reviews[i] = review
	}

	return &model.ReviewConnection{
		Reviews:    reviews,
		TotalCount: int(count),
	}, nil
}

// MyWorkerCompanySchedule is the resolver for the myWorkerCompanySchedule field.
func (r *queryResolver) MyWorkerCompanySchedule(ctx context.Context) ([]*model.CompanyWorkSchedule, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	rows, err := r.Queries.ListCompanyWorkSchedule(ctx, worker.CompanyID)
	if err != nil {
		return nil, fmt.Errorf("failed to list company work schedule: %w", err)
	}

	result := make([]*model.CompanyWorkSchedule, len(rows))
	for i, row := range rows {
		result[i] = &model.CompanyWorkSchedule{
			ID:        uuidToString(row.ID),
			DayOfWeek: int(row.DayOfWeek),
			StartTime: timeToString(row.StartTime),
			EndTime:   timeToString(row.EndTime),
			IsWorkDay: row.IsWorkDay,
		}
	}
	return result, nil
}

// MyWorkerDateOverrides is the resolver for the myWorkerDateOverrides field.
func (r *queryResolver) MyWorkerDateOverrides(ctx context.Context, from string, to string) ([]*model.WorkerDateOverride, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	worker, err := r.Queries.GetWorkerByUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("worker profile not found: %w", err)
	}

	fromDate, err := time.Parse("2006-01-02", from)
	if err != nil {
		return nil, fmt.Errorf("invalid from date: %w", err)
	}
	toDate, err := time.Parse("2006-01-02", to)
	if err != nil {
		return nil, fmt.Errorf("invalid to date: %w", err)
	}

	rows, err := r.Queries.ListWorkerDateOverrides(ctx, db.ListWorkerDateOverridesParams{
		WorkerID:       worker.ID,
		OverrideDate:   pgtype.Date{Time: fromDate, Valid: true},
		OverrideDate_2: pgtype.Date{Time: toDate, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list date overrides: %w", err)
	}

	result := make([]*model.WorkerDateOverride, len(rows))
	for i, row := range rows {
		result[i] = &model.WorkerDateOverride{
			ID:          uuidToString(row.ID),
			Date:        dateToString(row.OverrideDate),
			IsAvailable: row.IsAvailable,
			StartTime:   timeToString(row.StartTime),
			EndTime:     timeToString(row.EndTime),
		}
	}
	return result, nil
}

// WorkerDateOverrides is the resolver for the workerDateOverrides field.
func (r *queryResolver) WorkerDateOverrides(ctx context.Context, workerID string, from string, to string) ([]*model.WorkerDateOverride, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil {
		return nil, fmt.Errorf("not authenticated")
	}

	// Verify the caller is a company admin.
	company, err := r.Queries.GetCompanyByAdminUserID(ctx, stringToUUID(claims.UserID))
	if err != nil {
		return nil, fmt.Errorf("company not found for user: %w", err)
	}

	// Verify the worker belongs to the admin's company.
	worker, err := r.Queries.GetWorkerByID(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("worker not found: %w", err)
	}

	if worker.CompanyID != company.ID {
		return nil, fmt.Errorf("worker does not belong to your company")
	}

	fromDate, err := time.Parse("2006-01-02", from)
	if err != nil {
		return nil, fmt.Errorf("invalid from date: %w", err)
	}
	toDate, err := time.Parse("2006-01-02", to)
	if err != nil {
		return nil, fmt.Errorf("invalid to date: %w", err)
	}

	rows, err := r.Queries.ListWorkerDateOverrides(ctx, db.ListWorkerDateOverridesParams{
		WorkerID:       worker.ID,
		OverrideDate:   pgtype.Date{Time: fromDate, Valid: true},
		OverrideDate_2: pgtype.Date{Time: toDate, Valid: true},
	})
	if err != nil {
		return nil, fmt.Errorf("failed to list date overrides: %w", err)
	}

	result := make([]*model.WorkerDateOverride, len(rows))
	for i, row := range rows {
		result[i] = &model.WorkerDateOverride{
			ID:          uuidToString(row.ID),
			Date:        dateToString(row.OverrideDate),
			IsAvailable: row.IsAvailable,
			StartTime:   timeToString(row.StartTime),
			EndTime:     timeToString(row.EndTime),
		}
	}
	return result, nil
}

// WorkerDocuments is the resolver for the workerDocuments field.
func (r *queryResolver) WorkerDocuments(ctx context.Context, workerID string) ([]*model.WorkerDocument, error) {
	docs, err := r.Queries.ListWorkerDocuments(ctx, stringToUUID(workerID))
	if err != nil {
		return nil, fmt.Errorf("failed to list worker documents: %w", err)
	}

	result := make([]*model.WorkerDocument, len(docs))
	for i, d := range docs {
		result[i] = dbWorkerDocToGQL(d)
	}
	return result, nil
}

// PendingWorkerDocuments is the resolver for the pendingWorkerDocuments field.
func (r *queryResolver) PendingWorkerDocuments(ctx context.Context) ([]*model.WorkerDocument, error) {
	claims := auth.GetUserFromContext(ctx)
	if claims == nil || claims.Role != "global_admin" {
		return nil, fmt.Errorf("not authorized")
	}

	docs, err := r.Queries.ListPendingWorkerDocuments(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to list pending worker documents: %w", err)
	}

	result := make([]*model.WorkerDocument, len(docs))
	for i, d := range docs {
		result[i] = dbWorkerDocToGQL(d)
	}
	return result, nil
}

// ServiceCategories is the resolver for the serviceCategories field.
func (r *workerProfileResolver) ServiceCategories(ctx context.Context, obj *model.WorkerProfile) ([]*model.ServiceCategory, error) {
	workerUUID := stringToUUID(obj.ID)
	if !workerUUID.Valid {
		return []*model.ServiceCategory{}, nil
	}
	rows, err := r.Queries.ListWorkerServiceCategories(ctx, workerUUID)
	if err != nil {
		return []*model.ServiceCategory{}, nil
	}
	result := make([]*model.ServiceCategory, len(rows))
	for i, row := range rows {
		result[i] = &model.ServiceCategory{
			ID:     uuidToString(row.CategoryID),
			Slug:   row.Slug,
			NameRo: row.NameRo,
			NameEn: row.NameEn,
			Icon:   textPtr(row.Icon),
		}
	}
	return result, nil
}

// WorkerProfile returns graph.WorkerProfileResolver implementation.
func (r *Resolver) WorkerProfile() graph.WorkerProfileResolver { return &workerProfileResolver{r} }

type workerProfileResolver struct{ *Resolver }
