// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AddAddressInput struct {
	Label         *string  `json:"label,omitempty"`
	StreetAddress string   `json:"streetAddress"`
	City          string   `json:"city"`
	County        string   `json:"county"`
	PostalCode    *string  `json:"postalCode,omitempty"`
	Floor         *string  `json:"floor,omitempty"`
	Apartment     *string  `json:"apartment,omitempty"`
	EntryCode     *string  `json:"entryCode,omitempty"`
	Latitude      *float64 `json:"latitude,omitempty"`
	Longitude     *float64 `json:"longitude,omitempty"`
	Notes         *string  `json:"notes,omitempty"`
}

type Address struct {
	ID            string       `json:"id"`
	Label         *string      `json:"label,omitempty"`
	StreetAddress string       `json:"streetAddress"`
	City          string       `json:"city"`
	County        string       `json:"county"`
	PostalCode    *string      `json:"postalCode,omitempty"`
	Floor         *string      `json:"floor,omitempty"`
	Apartment     *string      `json:"apartment,omitempty"`
	EntryCode     *string      `json:"entryCode,omitempty"`
	Coordinates   *Coordinates `json:"coordinates,omitempty"`
	Notes         *string      `json:"notes,omitempty"`
	IsDefault     bool         `json:"isDefault"`
}

type AdminUpdateCompanyInput struct {
	ID           string `json:"id"`
	CompanyName  string `json:"companyName"`
	Cui          string `json:"cui"`
	Address      string `json:"address"`
	ContactPhone string `json:"contactPhone"`
	ContactEmail string `json:"contactEmail"`
}

type AuthPayload struct {
	Token     string `json:"token"`
	User      *User  `json:"user"`
	IsNewUser bool   `json:"isNewUser"`
}

type AvailabilitySlot struct {
	ID          string `json:"id"`
	DayOfWeek   int    `json:"dayOfWeek"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	IsAvailable bool   `json:"isAvailable"`
}

type AvailabilitySlotInput struct {
	DayOfWeek   int    `json:"dayOfWeek"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	IsAvailable bool   `json:"isAvailable"`
}

type BillingProfileInput struct {
	IsCompany   bool    `json:"isCompany"`
	CompanyName *string `json:"companyName,omitempty"`
	Cui         *string `json:"cui,omitempty"`
	RegNumber   *string `json:"regNumber,omitempty"`
	Address     *string `json:"address,omitempty"`
	City        *string `json:"city,omitempty"`
	County      *string `json:"county,omitempty"`
	IsVatPayer  *bool   `json:"isVatPayer,omitempty"`
	BankName    *string `json:"bankName,omitempty"`
	Iban        *string `json:"iban,omitempty"`
}

type Booking struct {
	ID                     string             `json:"id"`
	ReferenceCode          string             `json:"referenceCode"`
	Client                 *User              `json:"client,omitempty"`
	Company                *Company           `json:"company,omitempty"`
	Cleaner                *CleanerProfile    `json:"cleaner,omitempty"`
	Address                *Address           `json:"address,omitempty"`
	ServiceType            ServiceType        `json:"serviceType"`
	ServiceName            string             `json:"serviceName"`
	IncludedItems          []string           `json:"includedItems"`
	ScheduledDate          string             `json:"scheduledDate"`
	ScheduledStartTime     string             `json:"scheduledStartTime"`
	EstimatedDurationHours float64            `json:"estimatedDurationHours"`
	PropertyType           *string            `json:"propertyType,omitempty"`
	NumRooms               *int               `json:"numRooms,omitempty"`
	NumBathrooms           *int               `json:"numBathrooms,omitempty"`
	AreaSqm                *int               `json:"areaSqm,omitempty"`
	HasPets                *bool              `json:"hasPets,omitempty"`
	SpecialInstructions    *string            `json:"specialInstructions,omitempty"`
	HourlyRate             float64            `json:"hourlyRate"`
	EstimatedTotal         float64            `json:"estimatedTotal"`
	FinalTotal             *float64           `json:"finalTotal,omitempty"`
	PlatformCommissionPct  float64            `json:"platformCommissionPct"`
	Extras                 []*BookingExtra    `json:"extras"`
	Status                 BookingStatus      `json:"status"`
	StartedAt              *time.Time         `json:"startedAt,omitempty"`
	CompletedAt            *time.Time         `json:"completedAt,omitempty"`
	CancelledAt            *time.Time         `json:"cancelledAt,omitempty"`
	CancellationReason     *string            `json:"cancellationReason,omitempty"`
	PaymentStatus          string             `json:"paymentStatus"`
	PaidAt                 *time.Time         `json:"paidAt,omitempty"`
	RecurringGroupID       *string            `json:"recurringGroupId,omitempty"`
	OccurrenceNumber       *int               `json:"occurrenceNumber,omitempty"`
	TimeSlots              []*BookingTimeSlot `json:"timeSlots"`
	Review                 *Review            `json:"review,omitempty"`
	ChatRoom               *ChatRoom          `json:"chatRoom,omitempty"`
	CreatedAt              time.Time          `json:"createdAt"`
}

type BookingConnection struct {
	Edges      []*Booking `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type BookingExtra struct {
	Extra    *ServiceExtra `json:"extra"`
	Price    float64       `json:"price"`
	Quantity int           `json:"quantity"`
}

type BookingTimeSlot struct {
	ID         string `json:"id"`
	SlotDate   string `json:"slotDate"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
	IsSelected bool   `json:"isSelected"`
}

type BookingsByStatus struct {
	Status BookingStatus `json:"status"`
	Count  int           `json:"count"`
}

type ChatMessage struct {
	ID          string    `json:"id"`
	Sender      *User     `json:"sender"`
	Content     string    `json:"content"`
	MessageType string    `json:"messageType"`
	IsRead      bool      `json:"isRead"`
	CreatedAt   time.Time `json:"createdAt"`
}

type ChatMessageConnection struct {
	Edges    []*ChatMessage `json:"edges"`
	PageInfo *PageInfo      `json:"pageInfo"`
}

type ChatParticipant struct {
	User     *User     `json:"user"`
	JoinedAt time.Time `json:"joinedAt"`
}

type ChatRoom struct {
	ID           string                 `json:"id"`
	Booking      *Booking               `json:"booking,omitempty"`
	RoomType     string                 `json:"roomType"`
	Participants []*ChatParticipant     `json:"participants"`
	Messages     *ChatMessageConnection `json:"messages"`
	LastMessage  *ChatMessage           `json:"lastMessage,omitempty"`
	CreatedAt    time.Time              `json:"createdAt"`
}

type CityArea struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CityID   string `json:"cityId"`
	CityName string `json:"cityName"`
}

type CleanerDailyEarnings struct {
	Date   string  `json:"date"`
	Amount float64 `json:"amount"`
}

type CleanerDateOverride struct {
	ID          string `json:"id"`
	Date        string `json:"date"`
	IsAvailable bool   `json:"isAvailable"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
}

type CleanerDocument struct {
	ID              string         `json:"id"`
	DocumentType    string         `json:"documentType"`
	FileURL         string         `json:"fileUrl"`
	FileName        string         `json:"fileName"`
	Status          DocumentStatus `json:"status"`
	UploadedAt      time.Time      `json:"uploadedAt"`
	ReviewedAt      *time.Time     `json:"reviewedAt,omitempty"`
	RejectionReason *string        `json:"rejectionReason,omitempty"`
}

type CleanerPerformance struct {
	CleanerID          string  `json:"cleanerId"`
	FullName           string  `json:"fullName"`
	RatingAvg          float64 `json:"ratingAvg"`
	TotalCompletedJobs int     `json:"totalCompletedJobs"`
	ThisMonthCompleted int     `json:"thisMonthCompleted"`
	TotalEarnings      float64 `json:"totalEarnings"`
	ThisMonthEarnings  float64 `json:"thisMonthEarnings"`
}

type CleanerProfile struct {
	ID                    string                 `json:"id"`
	UserID                *string                `json:"userId,omitempty"`
	User                  *User                  `json:"user,omitempty"`
	Company               *Company               `json:"company,omitempty"`
	FullName              string                 `json:"fullName"`
	Phone                 *string                `json:"phone,omitempty"`
	Email                 *string                `json:"email,omitempty"`
	Bio                   *string                `json:"bio,omitempty"`
	Status                CleanerStatus          `json:"status"`
	IsCompanyAdmin        bool                   `json:"isCompanyAdmin"`
	InviteToken           *string                `json:"inviteToken,omitempty"`
	RatingAvg             float64                `json:"ratingAvg"`
	TotalJobsCompleted    int                    `json:"totalJobsCompleted"`
	Documents             []*CleanerDocument     `json:"documents"`
	PersonalityAssessment *PersonalityAssessment `json:"personalityAssessment,omitempty"`
	Availability          []*AvailabilitySlot    `json:"availability"`
	CreatedAt             time.Time              `json:"createdAt"`
}

type CleanerStats struct {
	TotalJobsCompleted int     `json:"totalJobsCompleted"`
	AverageRating      float64 `json:"averageRating"`
	TotalReviews       int     `json:"totalReviews"`
	ThisMonthJobs      int     `json:"thisMonthJobs"`
	ThisMonthEarnings  float64 `json:"thisMonthEarnings"`
}

type CleanerSuggestion struct {
	Cleaner            *CleanerProfile `json:"cleaner"`
	Company            *Company        `json:"company"`
	AvailabilityStatus string          `json:"availabilityStatus"`
	AvailableFrom      *string         `json:"availableFrom,omitempty"`
	AvailableTo        *string         `json:"availableTo,omitempty"`
	SuggestedStartTime *string         `json:"suggestedStartTime,omitempty"`
	SuggestedEndTime   *string         `json:"suggestedEndTime,omitempty"`
	SuggestedSlotIndex *int            `json:"suggestedSlotIndex,omitempty"`
	SuggestedDate      *string         `json:"suggestedDate,omitempty"`
	MatchScore         float64         `json:"matchScore"`
}

type ClientBillingProfile struct {
	ID          string  `json:"id"`
	IsCompany   bool    `json:"isCompany"`
	CompanyName *string `json:"companyName,omitempty"`
	Cui         *string `json:"cui,omitempty"`
	RegNumber   *string `json:"regNumber,omitempty"`
	Address     *string `json:"address,omitempty"`
	City        *string `json:"city,omitempty"`
	County      *string `json:"county,omitempty"`
	IsVatPayer  bool    `json:"isVatPayer"`
	BankName    *string `json:"bankName,omitempty"`
	Iban        *string `json:"iban,omitempty"`
	IsDefault   bool    `json:"isDefault"`
}

type Company struct {
	ID                  string             `json:"id"`
	CompanyName         string             `json:"companyName"`
	Cui                 string             `json:"cui"`
	CompanyType         CompanyType        `json:"companyType"`
	LegalRepresentative string             `json:"legalRepresentative"`
	ContactEmail        string             `json:"contactEmail"`
	ContactPhone        string             `json:"contactPhone"`
	Address             string             `json:"address"`
	City                string             `json:"city"`
	County              string             `json:"county"`
	Description         *string            `json:"description,omitempty"`
	LogoURL             *string            `json:"logoUrl,omitempty"`
	Status              CompanyStatus      `json:"status"`
	RejectionReason     *string            `json:"rejectionReason,omitempty"`
	MaxServiceRadiusKm  int                `json:"maxServiceRadiusKm"`
	RatingAvg           float64            `json:"ratingAvg"`
	TotalJobsCompleted  int                `json:"totalJobsCompleted"`
	Documents           []*CompanyDocument `json:"documents"`
	Cleaners            []*CleanerProfile  `json:"cleaners"`
	Admin               *User              `json:"admin,omitempty"`
	CreatedAt           time.Time          `json:"createdAt"`
}

type CompanyApplicationInput struct {
	CompanyName         string      `json:"companyName"`
	Cui                 string      `json:"cui"`
	CompanyType         CompanyType `json:"companyType"`
	LegalRepresentative string      `json:"legalRepresentative"`
	ContactEmail        string      `json:"contactEmail"`
	ContactPhone        string      `json:"contactPhone"`
	Address             string      `json:"address"`
	City                string      `json:"city"`
	County              string      `json:"county"`
	Description         *string     `json:"description,omitempty"`
}

type CompanyApplicationResult struct {
	Company    *Company `json:"company"`
	ClaimToken *string  `json:"claimToken,omitempty"`
}

type CompanyConnection struct {
	Edges      []*Company `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type CompanyDocument struct {
	ID              string         `json:"id"`
	DocumentType    string         `json:"documentType"`
	FileURL         string         `json:"fileUrl"`
	FileName        string         `json:"fileName"`
	Status          DocumentStatus `json:"status"`
	UploadedAt      time.Time      `json:"uploadedAt"`
	ReviewedAt      *time.Time     `json:"reviewedAt,omitempty"`
	RejectionReason *string        `json:"rejectionReason,omitempty"`
}

type CompanyEarningsSummary struct {
	TotalGross        int `json:"totalGross"`
	TotalCommission   int `json:"totalCommission"`
	TotalNet          int `json:"totalNet"`
	BookingCount      int `json:"bookingCount"`
	AveragePerBooking int `json:"averagePerBooking"`
}

type CompanyFinancialSummary struct {
	CompletedBookings int     `json:"completedBookings"`
	TotalRevenue      float64 `json:"totalRevenue"`
	TotalCommission   float64 `json:"totalCommission"`
	NetPayout         float64 `json:"netPayout"`
}

type CompanyPayout struct {
	ID           string            `json:"id"`
	Company      *Company          `json:"company,omitempty"`
	Amount       int               `json:"amount"`
	Currency     string            `json:"currency"`
	PeriodFrom   string            `json:"periodFrom"`
	PeriodTo     string            `json:"periodTo"`
	BookingCount int               `json:"bookingCount"`
	Status       PayoutStatus      `json:"status"`
	PaidAt       *time.Time        `json:"paidAt,omitempty"`
	LineItems    []*PayoutLineItem `json:"lineItems"`
	CreatedAt    time.Time         `json:"createdAt"`
}

type CompanyPerformance struct {
	Company        *Company `json:"company"`
	TotalBookings  int      `json:"totalBookings"`
	TotalRevenue   float64  `json:"totalRevenue"`
	AverageRating  float64  `json:"averageRating"`
	CompletionRate float64  `json:"completionRate"`
}

type CompanyWorkSchedule struct {
	ID        string `json:"id"`
	DayOfWeek int    `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	IsWorkDay bool   `json:"isWorkDay"`
}

type ConnectOnboardingLink struct {
	URL string `json:"url"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CreateBookingInput struct {
	AddressID           *string          `json:"addressId,omitempty"`
	Address             *AddAddressInput `json:"address,omitempty"`
	ServiceType         ServiceType      `json:"serviceType"`
	ScheduledDate       *string          `json:"scheduledDate,omitempty"`
	ScheduledStartTime  *string          `json:"scheduledStartTime,omitempty"`
	TimeSlots           []*TimeSlotInput `json:"timeSlots,omitempty"`
	PropertyType        *string          `json:"propertyType,omitempty"`
	NumRooms            int              `json:"numRooms"`
	NumBathrooms        int              `json:"numBathrooms"`
	AreaSqm             *int             `json:"areaSqm,omitempty"`
	HasPets             *bool            `json:"hasPets,omitempty"`
	SpecialInstructions *string          `json:"specialInstructions,omitempty"`
	Extras              []*ExtraInput    `json:"extras,omitempty"`
	GuestEmail          *string          `json:"guestEmail,omitempty"`
	GuestName           *string          `json:"guestName,omitempty"`
	GuestPhone          *string          `json:"guestPhone,omitempty"`
	PreferredCleanerID  *string          `json:"preferredCleanerId,omitempty"`
	SuggestedStartTime  *string          `json:"suggestedStartTime,omitempty"`
	Recurrence          *RecurrenceInput `json:"recurrence,omitempty"`
}

type CreateServiceDefinitionInput struct {
	ServiceType        ServiceType `json:"serviceType"`
	NameRo             string      `json:"nameRo"`
	NameEn             string      `json:"nameEn"`
	BasePricePerHour   float64     `json:"basePricePerHour"`
	MinHours           float64     `json:"minHours"`
	HoursPerRoom       float64     `json:"hoursPerRoom"`
	HoursPerBathroom   float64     `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64     `json:"hoursPer100Sqm"`
	HouseMultiplier    float64     `json:"houseMultiplier"`
	PetDurationMinutes int         `json:"petDurationMinutes"`
	IsActive           bool        `json:"isActive"`
	IncludedItems      []string    `json:"includedItems,omitempty"`
}

type CreateServiceExtraInput struct {
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	IsActive        bool    `json:"isActive"`
	AllowMultiple   bool    `json:"allowMultiple"`
	UnitLabel       *string `json:"unitLabel,omitempty"`
}

type DailyRevenue struct {
	Date         string  `json:"date"`
	BookingCount int     `json:"bookingCount"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
}

type EnabledCity struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	County   string      `json:"county"`
	IsActive bool        `json:"isActive"`
	Areas    []*CityArea `json:"areas"`
}

type ExtraInput struct {
	ExtraID  string `json:"extraId"`
	Quantity int    `json:"quantity"`
}

type ExtraLineItem struct {
	Extra     *ServiceExtra `json:"extra"`
	Quantity  int           `json:"quantity"`
	LineTotal float64       `json:"lineTotal"`
}

type InviteCleanerInput struct {
	FullName string  `json:"fullName"`
	Email    string  `json:"email"`
	Phone    *string `json:"phone,omitempty"`
}

type Invoice struct {
	ID                string             `json:"id"`
	InvoiceType       InvoiceType        `json:"invoiceType"`
	InvoiceNumber     *string            `json:"invoiceNumber,omitempty"`
	Status            InvoiceStatus      `json:"status"`
	SellerCompanyName string             `json:"sellerCompanyName"`
	SellerCui         string             `json:"sellerCui"`
	BuyerName         string             `json:"buyerName"`
	BuyerCui          *string            `json:"buyerCui,omitempty"`
	SubtotalAmount    int                `json:"subtotalAmount"`
	VatRate           float64            `json:"vatRate"`
	VatAmount         int                `json:"vatAmount"`
	TotalAmount       int                `json:"totalAmount"`
	Currency          string             `json:"currency"`
	Booking           *Booking           `json:"booking,omitempty"`
	Company           *Company           `json:"company,omitempty"`
	EfacturaStatus    *string            `json:"efacturaStatus,omitempty"`
	DownloadURL       *string            `json:"downloadUrl,omitempty"`
	IssuedAt          *time.Time         `json:"issuedAt,omitempty"`
	DueDate           *string            `json:"dueDate,omitempty"`
	Notes             *string            `json:"notes,omitempty"`
	LineItems         []*InvoiceLineItem `json:"lineItems"`
	CreatedAt         time.Time          `json:"createdAt"`
}

type InvoiceAnalytics struct {
	TotalIssued int                   `json:"totalIssued"`
	TotalAmount int                   `json:"totalAmount"`
	TotalVat    int                   `json:"totalVat"`
	ByStatus    []*InvoiceStatusCount `json:"byStatus"`
	ByType      []*InvoiceTypeCount   `json:"byType"`
}

type InvoiceConnection struct {
	Edges      []*Invoice `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type InvoiceLineItem struct {
	ID               string  `json:"id"`
	DescriptionRo    string  `json:"descriptionRo"`
	DescriptionEn    *string `json:"descriptionEn,omitempty"`
	Quantity         float64 `json:"quantity"`
	UnitPrice        int     `json:"unitPrice"`
	VatRate          float64 `json:"vatRate"`
	VatAmount        int     `json:"vatAmount"`
	LineTotal        int     `json:"lineTotal"`
	LineTotalWithVat int     `json:"lineTotalWithVat"`
}

type InvoiceStatusCount struct {
	Status      InvoiceStatus `json:"status"`
	Count       int           `json:"count"`
	TotalAmount int           `json:"totalAmount"`
}

type InvoiceTypeCount struct {
	Type        InvoiceType `json:"type"`
	Count       int         `json:"count"`
	TotalAmount int         `json:"totalAmount"`
}

type JoinWaitlistInput struct {
	LeadType    WaitlistLeadType `json:"leadType"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Phone       *string          `json:"phone,omitempty"`
	City        *string          `json:"city,omitempty"`
	CompanyName *string          `json:"companyName,omitempty"`
	Message     *string          `json:"message,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	Data      map[string]any `json:"data,omitempty"`
	IsRead    bool           `json:"isRead"`
	CreatedAt time.Time      `json:"createdAt"`
}

type NotificationConnection struct {
	Edges      []*Notification `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PaymentHistoryConnection struct {
	Edges      []*PaymentHistoryEntry `json:"edges"`
	PageInfo   *PageInfo              `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

type PaymentHistoryEntry struct {
	ID        string                   `json:"id"`
	Booking   *Booking                 `json:"booking,omitempty"`
	Amount    int                      `json:"amount"`
	Currency  string                   `json:"currency"`
	Status    PaymentTransactionStatus `json:"status"`
	PaidAt    *time.Time               `json:"paidAt,omitempty"`
	CreatedAt time.Time                `json:"createdAt"`
}

type PaymentIntentResult struct {
	ClientSecret    string `json:"clientSecret"`
	PaymentIntentID string `json:"paymentIntentId"`
	Amount          int    `json:"amount"`
	Currency        string `json:"currency"`
}

type PaymentMethod struct {
	ID                    string `json:"id"`
	StripePaymentMethodID string `json:"stripePaymentMethodId"`
	CardLastFour          string `json:"cardLastFour"`
	CardBrand             string `json:"cardBrand"`
	CardExpMonth          *int   `json:"cardExpMonth,omitempty"`
	CardExpYear           *int   `json:"cardExpYear,omitempty"`
	IsDefault             bool   `json:"isDefault"`
}

type PaymentTransaction struct {
	ID                    string                   `json:"id"`
	BookingID             string                   `json:"bookingId"`
	Booking               *Booking                 `json:"booking,omitempty"`
	StripePaymentIntentID string                   `json:"stripePaymentIntentId"`
	AmountTotal           int                      `json:"amountTotal"`
	AmountCompany         int                      `json:"amountCompany"`
	AmountPlatformFee     int                      `json:"amountPlatformFee"`
	Currency              string                   `json:"currency"`
	Status                PaymentTransactionStatus `json:"status"`
	FailureReason         *string                  `json:"failureReason,omitempty"`
	RefundAmount          *int                     `json:"refundAmount,omitempty"`
	CreatedAt             time.Time                `json:"createdAt"`
}

type PayoutLineItem struct {
	ID               string   `json:"id"`
	Booking          *Booking `json:"booking,omitempty"`
	AmountGross      int      `json:"amountGross"`
	AmountCommission int      `json:"amountCommission"`
	AmountNet        int      `json:"amountNet"`
}

type PersonalityAnswerInput struct {
	QuestionNumber int `json:"questionNumber"`
	Response       int `json:"response"`
}

type PersonalityAssessment struct {
	ID             string                   `json:"id"`
	CleanerID      string                   `json:"cleanerId"`
	FacetScores    []*PersonalityFacetScore `json:"facetScores"`
	IntegrityAvg   float64                  `json:"integrityAvg"`
	WorkQualityAvg float64                  `json:"workQualityAvg"`
	HasConcerns    bool                     `json:"hasConcerns"`
	FlaggedFacets  []string                 `json:"flaggedFacets"`
	CompletedAt    time.Time                `json:"completedAt"`
	Insights       *PersonalityInsights     `json:"insights,omitempty"`
}

type PersonalityFacetScore struct {
	FacetCode string `json:"facetCode"`
	FacetName string `json:"facetName"`
	Score     int    `json:"score"`
	MaxScore  int    `json:"maxScore"`
	IsFlagged bool   `json:"isFlagged"`
}

type PersonalityInsights struct {
	Summary           string    `json:"summary"`
	Strengths         []string  `json:"strengths"`
	Concerns          []string  `json:"concerns"`
	TeamFitAnalysis   string    `json:"teamFitAnalysis"`
	RecommendedAction string    `json:"recommendedAction"`
	Confidence        string    `json:"confidence"`
	AiModel           string    `json:"aiModel"`
	GeneratedAt       time.Time `json:"generatedAt"`
}

type PersonalityQuestion struct {
	Number    int    `json:"number"`
	FacetCode string `json:"facetCode"`
	Text      string `json:"text"`
}

type PlatformRevenueReport struct {
	TotalRevenue    int `json:"totalRevenue"`
	TotalCommission int `json:"totalCommission"`
	TotalPayouts    int `json:"totalPayouts"`
	PendingPayouts  int `json:"pendingPayouts"`
	TotalRefunds    int `json:"totalRefunds"`
	NetRevenue      int `json:"netRevenue"`
	BookingCount    int `json:"bookingCount"`
}

type PlatformSetting struct {
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	ValueType   string    `json:"valueType"`
	Description *string   `json:"description,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type PlatformStats struct {
	TotalClients            int     `json:"totalClients"`
	TotalCompanies          int     `json:"totalCompanies"`
	TotalCleaners           int     `json:"totalCleaners"`
	TotalBookings           int     `json:"totalBookings"`
	TotalRevenue            float64 `json:"totalRevenue"`
	PlatformCommissionTotal float64 `json:"platformCommissionTotal"`
	AverageRating           float64 `json:"averageRating"`
	BookingsThisMonth       int     `json:"bookingsThisMonth"`
	RevenueThisMonth        float64 `json:"revenueThisMonth"`
	NewClientsThisMonth     int     `json:"newClientsThisMonth"`
	NewCompaniesThisMonth   int     `json:"newCompaniesThisMonth"`
}

type PlatformTotals struct {
	TotalCompleted  int     `json:"totalCompleted"`
	TotalBookings   int     `json:"totalBookings"`
	TotalRevenue    float64 `json:"totalRevenue"`
	TotalCommission float64 `json:"totalCommission"`
	UniqueClients   int     `json:"uniqueClients"`
	ActiveCompanies int     `json:"activeCompanies"`
}

type PriceEstimate struct {
	HourlyRate         float64          `json:"hourlyRate"`
	EstimatedHours     float64          `json:"estimatedHours"`
	PropertyMultiplier float64          `json:"propertyMultiplier"`
	PetsSurcharge      float64          `json:"petsSurcharge"`
	Subtotal           float64          `json:"subtotal"`
	Extras             []*ExtraLineItem `json:"extras"`
	Total              float64          `json:"total"`
}

type PriceEstimateInput struct {
	ServiceType  ServiceType   `json:"serviceType"`
	NumRooms     int           `json:"numRooms"`
	NumBathrooms int           `json:"numBathrooms"`
	AreaSqm      *int          `json:"areaSqm,omitempty"`
	PropertyType *string       `json:"propertyType,omitempty"`
	HasPets      *bool         `json:"hasPets,omitempty"`
	Extras       []*ExtraInput `json:"extras,omitempty"`
}

type Query struct {
}

type RecurrenceInput struct {
	Type      RecurrenceType `json:"type"`
	DayOfWeek int            `json:"dayOfWeek"`
}

type RecurringBookingGroup struct {
	ID                          string          `json:"id"`
	Client                      *User           `json:"client,omitempty"`
	Company                     *Company        `json:"company,omitempty"`
	PreferredCleaner            *CleanerProfile `json:"preferredCleaner,omitempty"`
	Address                     *Address        `json:"address,omitempty"`
	RecurrenceType              RecurrenceType  `json:"recurrenceType"`
	DayOfWeek                   *int            `json:"dayOfWeek,omitempty"`
	PreferredTime               string          `json:"preferredTime"`
	ServiceType                 ServiceType     `json:"serviceType"`
	ServiceName                 string          `json:"serviceName"`
	PropertyType                *string         `json:"propertyType,omitempty"`
	NumRooms                    *int            `json:"numRooms,omitempty"`
	NumBathrooms                *int            `json:"numBathrooms,omitempty"`
	AreaSqm                     *int            `json:"areaSqm,omitempty"`
	HasPets                     *bool           `json:"hasPets,omitempty"`
	SpecialInstructions         *string         `json:"specialInstructions,omitempty"`
	HourlyRate                  float64         `json:"hourlyRate"`
	EstimatedTotalPerOccurrence float64         `json:"estimatedTotalPerOccurrence"`
	IsActive                    bool            `json:"isActive"`
	CancelledAt                 *time.Time      `json:"cancelledAt,omitempty"`
	CancellationReason          *string         `json:"cancellationReason,omitempty"`
	Occurrences                 []*Booking      `json:"occurrences"`
	UpcomingOccurrences         []*Booking      `json:"upcomingOccurrences"`
	TotalOccurrences            int             `json:"totalOccurrences"`
	CompletedOccurrences        int             `json:"completedOccurrences"`
	CreatedAt                   time.Time       `json:"createdAt"`
}

type RefundRequest struct {
	ID          string       `json:"id"`
	Booking     *Booking     `json:"booking,omitempty"`
	RequestedBy *User        `json:"requestedBy,omitempty"`
	ApprovedBy  *User        `json:"approvedBy,omitempty"`
	Amount      int          `json:"amount"`
	Reason      string       `json:"reason"`
	Status      RefundStatus `json:"status"`
	ProcessedAt *time.Time   `json:"processedAt,omitempty"`
	CreatedAt   time.Time    `json:"createdAt"`
}

type RequestOtpResponse struct {
	Success bool    `json:"success"`
	DevCode *string `json:"devCode,omitempty"`
}

type RevenueByMonth struct {
	Month        string  `json:"month"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
	BookingCount int     `json:"bookingCount"`
}

type Review struct {
	ID         string    `json:"id"`
	Booking    *Booking  `json:"booking,omitempty"`
	Reviewer   *User     `json:"reviewer,omitempty"`
	Rating     int       `json:"rating"`
	Comment    *string   `json:"comment,omitempty"`
	ReviewType string    `json:"reviewType"`
	CreatedAt  time.Time `json:"createdAt"`
}

type ReviewConnection struct {
	Reviews    []*Review `json:"reviews"`
	TotalCount int       `json:"totalCount"`
}

type ServiceDefinition struct {
	ID                 string      `json:"id"`
	ServiceType        ServiceType `json:"serviceType"`
	NameRo             string      `json:"nameRo"`
	NameEn             string      `json:"nameEn"`
	DescriptionRo      *string     `json:"descriptionRo,omitempty"`
	DescriptionEn      *string     `json:"descriptionEn,omitempty"`
	BasePricePerHour   float64     `json:"basePricePerHour"`
	MinHours           float64     `json:"minHours"`
	HoursPerRoom       float64     `json:"hoursPerRoom"`
	HoursPerBathroom   float64     `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64     `json:"hoursPer100Sqm"`
	HouseMultiplier    float64     `json:"houseMultiplier"`
	PetDurationMinutes int         `json:"petDurationMinutes"`
	Icon               *string     `json:"icon,omitempty"`
	IsActive           bool        `json:"isActive"`
	IncludedItems      []string    `json:"includedItems"`
}

type ServiceExtra struct {
	ID              string  `json:"id"`
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	Icon            *string `json:"icon,omitempty"`
	IsActive        bool    `json:"isActive"`
	AllowMultiple   bool    `json:"allowMultiple"`
	UnitLabel       *string `json:"unitLabel,omitempty"`
}

type ServiceRevenue struct {
	ServiceType  ServiceType `json:"serviceType"`
	BookingCount int         `json:"bookingCount"`
	Revenue      float64     `json:"revenue"`
}

type SetupIntentResult struct {
	ClientSecret string `json:"clientSecret"`
}

type StripeConnectStatus struct {
	AccountID        *string                 `json:"accountId,omitempty"`
	OnboardingStatus ConnectOnboardingStatus `json:"onboardingStatus"`
	ChargesEnabled   bool                    `json:"chargesEnabled"`
	PayoutsEnabled   bool                    `json:"payoutsEnabled"`
}

type SubmitReviewInput struct {
	BookingID string  `json:"bookingId"`
	Rating    int     `json:"rating"`
	Comment   *string `json:"comment,omitempty"`
}

type TimeSlotInput struct {
	Date      string `json:"date"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type TopCompany struct {
	ID           string  `json:"id"`
	CompanyName  string  `json:"companyName"`
	BookingCount int     `json:"bookingCount"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
}

type UpdateAddressInput struct {
	Label         *string  `json:"label,omitempty"`
	StreetAddress *string  `json:"streetAddress,omitempty"`
	City          *string  `json:"city,omitempty"`
	County        *string  `json:"county,omitempty"`
	PostalCode    *string  `json:"postalCode,omitempty"`
	Floor         *string  `json:"floor,omitempty"`
	Apartment     *string  `json:"apartment,omitempty"`
	EntryCode     *string  `json:"entryCode,omitempty"`
	Latitude      *float64 `json:"latitude,omitempty"`
	Longitude     *float64 `json:"longitude,omitempty"`
	Notes         *string  `json:"notes,omitempty"`
}

type UpdateCleanerProfileInput struct {
	Bio *string `json:"bio,omitempty"`
}

type UpdateCompanyInput struct {
	Description        *string                 `json:"description,omitempty"`
	ContactPhone       *string                 `json:"contactPhone,omitempty"`
	ContactEmail       *string                 `json:"contactEmail,omitempty"`
	MaxServiceRadiusKm *int                    `json:"maxServiceRadiusKm,omitempty"`
	WorkSchedule       []*WorkScheduleDayInput `json:"workSchedule,omitempty"`
}

type UpdateProfileInput struct {
	FullName          *string `json:"fullName,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	AvatarURL         *string `json:"avatarUrl,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
}

type UpdateServiceDefinitionInput struct {
	ID                 string   `json:"id"`
	NameRo             string   `json:"nameRo"`
	NameEn             string   `json:"nameEn"`
	BasePricePerHour   float64  `json:"basePricePerHour"`
	MinHours           float64  `json:"minHours"`
	HoursPerRoom       float64  `json:"hoursPerRoom"`
	HoursPerBathroom   float64  `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64  `json:"hoursPer100Sqm"`
	HouseMultiplier    float64  `json:"houseMultiplier"`
	PetDurationMinutes int      `json:"petDurationMinutes"`
	IsActive           bool     `json:"isActive"`
	IncludedItems      []string `json:"includedItems,omitempty"`
}

type UpdateServiceExtraInput struct {
	ID              string  `json:"id"`
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	IsActive        bool    `json:"isActive"`
	AllowMultiple   bool    `json:"allowMultiple"`
	UnitLabel       *string `json:"unitLabel,omitempty"`
}

type UploadResult struct {
	URL      string `json:"url"`
	FileName string `json:"fileName"`
}

type User struct {
	ID                string          `json:"id"`
	Email             string          `json:"email"`
	FullName          string          `json:"fullName"`
	Phone             *string         `json:"phone,omitempty"`
	AvatarURL         *string         `json:"avatarUrl,omitempty"`
	Role              UserRole        `json:"role"`
	Status            UserStatus      `json:"status"`
	PreferredLanguage string          `json:"preferredLanguage"`
	CreatedAt         time.Time       `json:"createdAt"`
	CleanerProfile    *CleanerProfile `json:"cleanerProfile,omitempty"`
}

type UserConnection struct {
	Users      []*User `json:"users"`
	TotalCount int     `json:"totalCount"`
}

type WaitlistLead struct {
	ID          string           `json:"id"`
	LeadType    WaitlistLeadType `json:"leadType"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Phone       *string          `json:"phone,omitempty"`
	City        *string          `json:"city,omitempty"`
	CompanyName *string          `json:"companyName,omitempty"`
	Message     *string          `json:"message,omitempty"`
	CreatedAt   time.Time        `json:"createdAt"`
}

type WaitlistStats struct {
	ClientCount  int `json:"clientCount"`
	CompanyCount int `json:"companyCount"`
	TotalCount   int `json:"totalCount"`
}

type WorkScheduleDayInput struct {
	DayOfWeek int    `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	IsWorkDay bool   `json:"isWorkDay"`
}

type BookingStatus string

const (
	BookingStatusAssigned           BookingStatus = "ASSIGNED"
	BookingStatusConfirmed          BookingStatus = "CONFIRMED"
	BookingStatusInProgress         BookingStatus = "IN_PROGRESS"
	BookingStatusCompleted          BookingStatus = "COMPLETED"
	BookingStatusCancelledByClient  BookingStatus = "CANCELLED_BY_CLIENT"
	BookingStatusCancelledByCompany BookingStatus = "CANCELLED_BY_COMPANY"
	BookingStatusCancelledByAdmin   BookingStatus = "CANCELLED_BY_ADMIN"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusAssigned,
	BookingStatusConfirmed,
	BookingStatusInProgress,
	BookingStatusCompleted,
	BookingStatusCancelledByClient,
	BookingStatusCancelledByCompany,
	BookingStatusCancelledByAdmin,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusAssigned, BookingStatusConfirmed, BookingStatusInProgress, BookingStatusCompleted, BookingStatusCancelledByClient, BookingStatusCancelledByCompany, BookingStatusCancelledByAdmin:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CleanerStatus string

const (
	CleanerStatusInvited       CleanerStatus = "INVITED"
	CleanerStatusPendingReview CleanerStatus = "PENDING_REVIEW"
	CleanerStatusActive        CleanerStatus = "ACTIVE"
	CleanerStatusInactive      CleanerStatus = "INACTIVE"
	CleanerStatusSuspended     CleanerStatus = "SUSPENDED"
)

var AllCleanerStatus = []CleanerStatus{
	CleanerStatusInvited,
	CleanerStatusPendingReview,
	CleanerStatusActive,
	CleanerStatusInactive,
	CleanerStatusSuspended,
}

func (e CleanerStatus) IsValid() bool {
	switch e {
	case CleanerStatusInvited, CleanerStatusPendingReview, CleanerStatusActive, CleanerStatusInactive, CleanerStatusSuspended:
		return true
	}
	return false
}

func (e CleanerStatus) String() string {
	return string(e)
}

func (e *CleanerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CleanerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CleanerStatus", str)
	}
	return nil
}

func (e CleanerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CleanerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CleanerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyStatus string

const (
	CompanyStatusPendingReview CompanyStatus = "PENDING_REVIEW"
	CompanyStatusApproved      CompanyStatus = "APPROVED"
	CompanyStatusRejected      CompanyStatus = "REJECTED"
	CompanyStatusSuspended     CompanyStatus = "SUSPENDED"
)

var AllCompanyStatus = []CompanyStatus{
	CompanyStatusPendingReview,
	CompanyStatusApproved,
	CompanyStatusRejected,
	CompanyStatusSuspended,
}

func (e CompanyStatus) IsValid() bool {
	switch e {
	case CompanyStatusPendingReview, CompanyStatusApproved, CompanyStatusRejected, CompanyStatusSuspended:
		return true
	}
	return false
}

func (e CompanyStatus) String() string {
	return string(e)
}

func (e *CompanyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyStatus", str)
	}
	return nil
}

func (e CompanyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyType string

const (
	CompanyTypeSrl CompanyType = "SRL"
	CompanyTypePfa CompanyType = "PFA"
	CompanyTypeIi  CompanyType = "II"
)

var AllCompanyType = []CompanyType{
	CompanyTypeSrl,
	CompanyTypePfa,
	CompanyTypeIi,
}

func (e CompanyType) IsValid() bool {
	switch e {
	case CompanyTypeSrl, CompanyTypePfa, CompanyTypeIi:
		return true
	}
	return false
}

func (e CompanyType) String() string {
	return string(e)
}

func (e *CompanyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyType", str)
	}
	return nil
}

func (e CompanyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectOnboardingStatus string

const (
	ConnectOnboardingStatusNotStarted ConnectOnboardingStatus = "NOT_STARTED"
	ConnectOnboardingStatusPending    ConnectOnboardingStatus = "PENDING"
	ConnectOnboardingStatusComplete   ConnectOnboardingStatus = "COMPLETE"
	ConnectOnboardingStatusRestricted ConnectOnboardingStatus = "RESTRICTED"
)

var AllConnectOnboardingStatus = []ConnectOnboardingStatus{
	ConnectOnboardingStatusNotStarted,
	ConnectOnboardingStatusPending,
	ConnectOnboardingStatusComplete,
	ConnectOnboardingStatusRestricted,
}

func (e ConnectOnboardingStatus) IsValid() bool {
	switch e {
	case ConnectOnboardingStatusNotStarted, ConnectOnboardingStatusPending, ConnectOnboardingStatusComplete, ConnectOnboardingStatusRestricted:
		return true
	}
	return false
}

func (e ConnectOnboardingStatus) String() string {
	return string(e)
}

func (e *ConnectOnboardingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectOnboardingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectOnboardingStatus", str)
	}
	return nil
}

func (e ConnectOnboardingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectOnboardingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectOnboardingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DocumentStatus string

const (
	DocumentStatusPending  DocumentStatus = "PENDING"
	DocumentStatusApproved DocumentStatus = "APPROVED"
	DocumentStatusRejected DocumentStatus = "REJECTED"
)

var AllDocumentStatus = []DocumentStatus{
	DocumentStatusPending,
	DocumentStatusApproved,
	DocumentStatusRejected,
}

func (e DocumentStatus) IsValid() bool {
	switch e {
	case DocumentStatusPending, DocumentStatusApproved, DocumentStatusRejected:
		return true
	}
	return false
}

func (e DocumentStatus) String() string {
	return string(e)
}

func (e *DocumentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentStatus", str)
	}
	return nil
}

func (e DocumentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocumentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocumentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft       InvoiceStatus = "DRAFT"
	InvoiceStatusIssued      InvoiceStatus = "ISSUED"
	InvoiceStatusSent        InvoiceStatus = "SENT"
	InvoiceStatusTransmitted InvoiceStatus = "TRANSMITTED"
	InvoiceStatusPaid        InvoiceStatus = "PAID"
	InvoiceStatusCancelled   InvoiceStatus = "CANCELLED"
	InvoiceStatusCreditNote  InvoiceStatus = "CREDIT_NOTE"
)

var AllInvoiceStatus = []InvoiceStatus{
	InvoiceStatusDraft,
	InvoiceStatusIssued,
	InvoiceStatusSent,
	InvoiceStatusTransmitted,
	InvoiceStatusPaid,
	InvoiceStatusCancelled,
	InvoiceStatusCreditNote,
}

func (e InvoiceStatus) IsValid() bool {
	switch e {
	case InvoiceStatusDraft, InvoiceStatusIssued, InvoiceStatusSent, InvoiceStatusTransmitted, InvoiceStatusPaid, InvoiceStatusCancelled, InvoiceStatusCreditNote:
		return true
	}
	return false
}

func (e InvoiceStatus) String() string {
	return string(e)
}

func (e *InvoiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceStatus", str)
	}
	return nil
}

func (e InvoiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvoiceType string

const (
	InvoiceTypeClientService      InvoiceType = "CLIENT_SERVICE"
	InvoiceTypePlatformCommission InvoiceType = "PLATFORM_COMMISSION"
)

var AllInvoiceType = []InvoiceType{
	InvoiceTypeClientService,
	InvoiceTypePlatformCommission,
}

func (e InvoiceType) IsValid() bool {
	switch e {
	case InvoiceTypeClientService, InvoiceTypePlatformCommission:
		return true
	}
	return false
}

func (e InvoiceType) String() string {
	return string(e)
}

func (e *InvoiceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceType", str)
	}
	return nil
}

func (e InvoiceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentTransactionStatus string

const (
	PaymentTransactionStatusPending           PaymentTransactionStatus = "PENDING"
	PaymentTransactionStatusRequiresAction    PaymentTransactionStatus = "REQUIRES_ACTION"
	PaymentTransactionStatusProcessing        PaymentTransactionStatus = "PROCESSING"
	PaymentTransactionStatusSucceeded         PaymentTransactionStatus = "SUCCEEDED"
	PaymentTransactionStatusFailed            PaymentTransactionStatus = "FAILED"
	PaymentTransactionStatusRefunded          PaymentTransactionStatus = "REFUNDED"
	PaymentTransactionStatusPartiallyRefunded PaymentTransactionStatus = "PARTIALLY_REFUNDED"
	PaymentTransactionStatusCancelled         PaymentTransactionStatus = "CANCELLED"
)

var AllPaymentTransactionStatus = []PaymentTransactionStatus{
	PaymentTransactionStatusPending,
	PaymentTransactionStatusRequiresAction,
	PaymentTransactionStatusProcessing,
	PaymentTransactionStatusSucceeded,
	PaymentTransactionStatusFailed,
	PaymentTransactionStatusRefunded,
	PaymentTransactionStatusPartiallyRefunded,
	PaymentTransactionStatusCancelled,
}

func (e PaymentTransactionStatus) IsValid() bool {
	switch e {
	case PaymentTransactionStatusPending, PaymentTransactionStatusRequiresAction, PaymentTransactionStatusProcessing, PaymentTransactionStatusSucceeded, PaymentTransactionStatusFailed, PaymentTransactionStatusRefunded, PaymentTransactionStatusPartiallyRefunded, PaymentTransactionStatusCancelled:
		return true
	}
	return false
}

func (e PaymentTransactionStatus) String() string {
	return string(e)
}

func (e *PaymentTransactionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentTransactionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentTransactionStatus", str)
	}
	return nil
}

func (e PaymentTransactionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentTransactionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentTransactionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "PENDING"
	PayoutStatusProcessing PayoutStatus = "PROCESSING"
	PayoutStatusPaid       PayoutStatus = "PAID"
	PayoutStatusFailed     PayoutStatus = "FAILED"
	PayoutStatusCancelled  PayoutStatus = "CANCELLED"
)

var AllPayoutStatus = []PayoutStatus{
	PayoutStatusPending,
	PayoutStatusProcessing,
	PayoutStatusPaid,
	PayoutStatusFailed,
	PayoutStatusCancelled,
}

func (e PayoutStatus) IsValid() bool {
	switch e {
	case PayoutStatusPending, PayoutStatusProcessing, PayoutStatusPaid, PayoutStatusFailed, PayoutStatusCancelled:
		return true
	}
	return false
}

func (e PayoutStatus) String() string {
	return string(e)
}

func (e *PayoutStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PayoutStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PayoutStatus", str)
	}
	return nil
}

func (e PayoutStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PayoutStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PayoutStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurrenceType string

const (
	RecurrenceTypeWeekly   RecurrenceType = "WEEKLY"
	RecurrenceTypeBiweekly RecurrenceType = "BIWEEKLY"
	RecurrenceTypeMonthly  RecurrenceType = "MONTHLY"
)

var AllRecurrenceType = []RecurrenceType{
	RecurrenceTypeWeekly,
	RecurrenceTypeBiweekly,
	RecurrenceTypeMonthly,
}

func (e RecurrenceType) IsValid() bool {
	switch e {
	case RecurrenceTypeWeekly, RecurrenceTypeBiweekly, RecurrenceTypeMonthly:
		return true
	}
	return false
}

func (e RecurrenceType) String() string {
	return string(e)
}

func (e *RecurrenceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurrenceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurrenceType", str)
	}
	return nil
}

func (e RecurrenceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurrenceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurrenceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RefundStatus string

const (
	RefundStatusRequested RefundStatus = "REQUESTED"
	RefundStatusApproved  RefundStatus = "APPROVED"
	RefundStatusProcessed RefundStatus = "PROCESSED"
	RefundStatusRejected  RefundStatus = "REJECTED"
)

var AllRefundStatus = []RefundStatus{
	RefundStatusRequested,
	RefundStatusApproved,
	RefundStatusProcessed,
	RefundStatusRejected,
}

func (e RefundStatus) IsValid() bool {
	switch e {
	case RefundStatusRequested, RefundStatusApproved, RefundStatusProcessed, RefundStatusRejected:
		return true
	}
	return false
}

func (e RefundStatus) String() string {
	return string(e)
}

func (e *RefundStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RefundStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RefundStatus", str)
	}
	return nil
}

func (e RefundStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RefundStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RefundStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceType string

const (
	ServiceTypeStandardCleaning  ServiceType = "STANDARD_CLEANING"
	ServiceTypeDeepCleaning      ServiceType = "DEEP_CLEANING"
	ServiceTypeMoveInOutCleaning ServiceType = "MOVE_IN_OUT_CLEANING"
	ServiceTypePostConstruction  ServiceType = "POST_CONSTRUCTION"
	ServiceTypeOfficeCleaning    ServiceType = "OFFICE_CLEANING"
	ServiceTypeWindowCleaning    ServiceType = "WINDOW_CLEANING"
)

var AllServiceType = []ServiceType{
	ServiceTypeStandardCleaning,
	ServiceTypeDeepCleaning,
	ServiceTypeMoveInOutCleaning,
	ServiceTypePostConstruction,
	ServiceTypeOfficeCleaning,
	ServiceTypeWindowCleaning,
}

func (e ServiceType) IsValid() bool {
	switch e {
	case ServiceTypeStandardCleaning, ServiceTypeDeepCleaning, ServiceTypeMoveInOutCleaning, ServiceTypePostConstruction, ServiceTypeOfficeCleaning, ServiceTypeWindowCleaning:
		return true
	}
	return false
}

func (e ServiceType) String() string {
	return string(e)
}

func (e *ServiceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceType", str)
	}
	return nil
}

func (e ServiceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleClient       UserRole = "CLIENT"
	UserRoleCompanyAdmin UserRole = "COMPANY_ADMIN"
	UserRoleCleaner      UserRole = "CLEANER"
	UserRoleGlobalAdmin  UserRole = "GLOBAL_ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleClient,
	UserRoleCompanyAdmin,
	UserRoleCleaner,
	UserRoleGlobalAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleClient, UserRoleCompanyAdmin, UserRoleCleaner, UserRoleGlobalAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
	UserStatusPending   UserStatus = "PENDING"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
	UserStatusPending,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended, UserStatusPending:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WaitlistLeadType string

const (
	WaitlistLeadTypeClient  WaitlistLeadType = "CLIENT"
	WaitlistLeadTypeCompany WaitlistLeadType = "COMPANY"
)

var AllWaitlistLeadType = []WaitlistLeadType{
	WaitlistLeadTypeClient,
	WaitlistLeadTypeCompany,
}

func (e WaitlistLeadType) IsValid() bool {
	switch e {
	case WaitlistLeadTypeClient, WaitlistLeadTypeCompany:
		return true
	}
	return false
}

func (e WaitlistLeadType) String() string {
	return string(e)
}

func (e *WaitlistLeadType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WaitlistLeadType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WaitlistLeadType", str)
	}
	return nil
}

func (e WaitlistLeadType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WaitlistLeadType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WaitlistLeadType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
