// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type ANAFVerification struct {
	Status         string     `json:"status"`
	Denumire       *string    `json:"denumire,omitempty"`
	Adresa         *string    `json:"adresa,omitempty"`
	DataInfiintare *string    `json:"dataInfiintare,omitempty"`
	ScpTva         *bool      `json:"scpTva,omitempty"`
	Inactive       *bool      `json:"inactive,omitempty"`
	VerifiedAt     *time.Time `json:"verifiedAt,omitempty"`
	RawError       *string    `json:"rawError,omitempty"`
	NameMatchScore *float64   `json:"nameMatchScore,omitempty"`
	IsActive       *bool      `json:"isActive,omitempty"`
}

type AddAddressInput struct {
	Label         *string  `json:"label,omitempty"`
	StreetAddress string   `json:"streetAddress"`
	City          string   `json:"city"`
	County        string   `json:"county"`
	PostalCode    *string  `json:"postalCode,omitempty"`
	Floor         *string  `json:"floor,omitempty"`
	Apartment     *string  `json:"apartment,omitempty"`
	EntryCode     *string  `json:"entryCode,omitempty"`
	Latitude      *float64 `json:"latitude,omitempty"`
	Longitude     *float64 `json:"longitude,omitempty"`
	Notes         *string  `json:"notes,omitempty"`
}

type Address struct {
	ID            string       `json:"id"`
	Label         *string      `json:"label,omitempty"`
	StreetAddress string       `json:"streetAddress"`
	City          string       `json:"city"`
	County        string       `json:"county"`
	PostalCode    *string      `json:"postalCode,omitempty"`
	Floor         *string      `json:"floor,omitempty"`
	Apartment     *string      `json:"apartment,omitempty"`
	EntryCode     *string      `json:"entryCode,omitempty"`
	Coordinates   *Coordinates `json:"coordinates,omitempty"`
	Notes         *string      `json:"notes,omitempty"`
	IsDefault     bool         `json:"isDefault"`
}

type AdminUpdateCompanyInput struct {
	ID           string `json:"id"`
	CompanyName  string `json:"companyName"`
	Cui          string `json:"cui"`
	Address      string `json:"address"`
	ContactPhone string `json:"contactPhone"`
	ContactEmail string `json:"contactEmail"`
}

type AuthPayload struct {
	Token     string `json:"token"`
	User      *User  `json:"user"`
	IsNewUser bool   `json:"isNewUser"`
}

type AvailabilitySlot struct {
	ID          string `json:"id"`
	DayOfWeek   int    `json:"dayOfWeek"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	IsAvailable bool   `json:"isAvailable"`
}

type AvailabilitySlotInput struct {
	DayOfWeek   int    `json:"dayOfWeek"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
	IsAvailable bool   `json:"isAvailable"`
}

type BillingProfileInput struct {
	IsCompany   bool    `json:"isCompany"`
	CompanyName *string `json:"companyName,omitempty"`
	Cui         *string `json:"cui,omitempty"`
	RegNumber   *string `json:"regNumber,omitempty"`
	Address     *string `json:"address,omitempty"`
	City        *string `json:"city,omitempty"`
	County      *string `json:"county,omitempty"`
	IsVatPayer  *bool   `json:"isVatPayer,omitempty"`
	BankName    *string `json:"bankName,omitempty"`
	Iban        *string `json:"iban,omitempty"`
}

type Booking struct {
	ID                     string             `json:"id"`
	ReferenceCode          string             `json:"referenceCode"`
	Client                 *User              `json:"client,omitempty"`
	Company                *Company           `json:"company,omitempty"`
	Worker                 *WorkerProfile     `json:"worker,omitempty"`
	Address                *Address           `json:"address,omitempty"`
	ServiceType            ServiceType        `json:"serviceType"`
	ServiceName            string             `json:"serviceName"`
	IncludedItems          []string           `json:"includedItems"`
	ScheduledDate          string             `json:"scheduledDate"`
	ScheduledStartTime     string             `json:"scheduledStartTime"`
	EstimatedDurationHours float64            `json:"estimatedDurationHours"`
	PropertyType           *string            `json:"propertyType,omitempty"`
	NumRooms               *int               `json:"numRooms,omitempty"`
	NumBathrooms           *int               `json:"numBathrooms,omitempty"`
	AreaSqm                *int               `json:"areaSqm,omitempty"`
	HasPets                *bool              `json:"hasPets,omitempty"`
	SpecialInstructions    *string            `json:"specialInstructions,omitempty"`
	HourlyRate             float64            `json:"hourlyRate"`
	EstimatedTotal         float64            `json:"estimatedTotal"`
	FinalTotal             *float64           `json:"finalTotal,omitempty"`
	PlatformCommissionPct  float64            `json:"platformCommissionPct"`
	Extras                 []*BookingExtra    `json:"extras"`
	Status                 BookingStatus      `json:"status"`
	StartedAt              *time.Time         `json:"startedAt,omitempty"`
	CompletedAt            *time.Time         `json:"completedAt,omitempty"`
	CancelledAt            *time.Time         `json:"cancelledAt,omitempty"`
	CancellationReason     *string            `json:"cancellationReason,omitempty"`
	StartLat               *float64           `json:"startLat,omitempty"`
	StartLng               *float64           `json:"startLng,omitempty"`
	FinishLat              *float64           `json:"finishLat,omitempty"`
	FinishLng              *float64           `json:"finishLng,omitempty"`
	PaymentStatus          string             `json:"paymentStatus"`
	PaidAt                 *time.Time         `json:"paidAt,omitempty"`
	RecurringGroupID       *string            `json:"recurringGroupId,omitempty"`
	SubscriptionID         *string            `json:"subscriptionId,omitempty"`
	OccurrenceNumber       *int               `json:"occurrenceNumber,omitempty"`
	RescheduleCount        int                `json:"rescheduleCount"`
	RescheduledAt          *time.Time         `json:"rescheduledAt,omitempty"`
	TimeSlots              []*BookingTimeSlot `json:"timeSlots"`
	Review                 *Review            `json:"review,omitempty"`
	Photos                 []*BookingJobPhoto `json:"photos"`
	CategoryID             *string            `json:"categoryId,omitempty"`
	Category               *ServiceCategory   `json:"category,omitempty"`
	CustomFields           *string            `json:"customFields,omitempty"`
	ReferralDiscountID     *string            `json:"referralDiscountId,omitempty"`
	PromoCodeID            *string            `json:"promoCodeId,omitempty"`
	PromoDiscountAmount    *float64           `json:"promoDiscountAmount,omitempty"`
	CreatedAt              time.Time          `json:"createdAt"`
}

type BookingAvailabilityStatus struct {
	BookingID              string   `json:"bookingId"`
	ScheduledDate          string   `json:"scheduledDate"`
	ScheduledStartTime     string   `json:"scheduledStartTime"`
	EstimatedDurationHours float64  `json:"estimatedDurationHours"`
	ReferenceCode          string   `json:"referenceCode"`
	Available              bool     `json:"available"`
	Reason                 *string  `json:"reason,omitempty"`
	Conflicts              []string `json:"conflicts"`
}

type BookingConnection struct {
	Edges      []*Booking `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type BookingDispute struct {
	ID                 string        `json:"id"`
	BookingID          string        `json:"bookingId"`
	Booking            *Booking      `json:"booking,omitempty"`
	OpenedBy           *User         `json:"openedBy"`
	Reason             DisputeReason `json:"reason"`
	Description        string        `json:"description"`
	EvidenceUrls       []string      `json:"evidenceUrls"`
	CompanyResponse    *string       `json:"companyResponse,omitempty"`
	CompanyRespondedAt *time.Time    `json:"companyRespondedAt,omitempty"`
	ResolutionNotes    *string       `json:"resolutionNotes,omitempty"`
	ResolvedBy         *User         `json:"resolvedBy,omitempty"`
	RefundAmount       *float64      `json:"refundAmount,omitempty"`
	Status             DisputeStatus `json:"status"`
	AutoCloseAt        time.Time     `json:"autoCloseAt"`
	CreatedAt          time.Time     `json:"createdAt"`
}

type BookingExtra struct {
	Extra    *ServiceExtra `json:"extra"`
	Price    float64       `json:"price"`
	Quantity int           `json:"quantity"`
}

type BookingJobPhoto struct {
	ID         string    `json:"id"`
	BookingID  string    `json:"bookingId"`
	UploadedBy string    `json:"uploadedBy"`
	PhotoURL   string    `json:"photoUrl"`
	Phase      string    `json:"phase"`
	SortOrder  int       `json:"sortOrder"`
	CreatedAt  time.Time `json:"createdAt"`
}

type BookingOrderByInput struct {
	Field     BookingOrderField `json:"field"`
	Direction OrderDirection    `json:"direction"`
}

type BookingPolicy struct {
	CancelFreeHoursBefore     int `json:"cancelFreeHoursBefore"`
	CancelLateRefundPct       int `json:"cancelLateRefundPct"`
	CancelNoRefundHoursBefore int `json:"cancelNoRefundHoursBefore"`
	RescheduleFreeHoursBefore int `json:"rescheduleFreeHoursBefore"`
	RescheduleMaxPerBooking   int `json:"rescheduleMaxPerBooking"`
}

type BookingTimeSlot struct {
	ID         string `json:"id"`
	SlotDate   string `json:"slotDate"`
	StartTime  string `json:"startTime"`
	EndTime    string `json:"endTime"`
	IsSelected bool   `json:"isSelected"`
}

type BookingWorkerAssignment struct {
	BookingID string `json:"bookingId"`
	WorkerID  string `json:"workerId"`
}

type BookingsByStatus struct {
	Status BookingStatus `json:"status"`
	Count  int           `json:"count"`
}

type BulkPayoutResult struct {
	Succeeded []*CompanyPayout `json:"succeeded"`
	Skipped   int              `json:"skipped"`
	Failed    int              `json:"failed"`
}

type CityArea struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	CityID   string `json:"cityId"`
	CityName string `json:"cityName"`
}

type ClientBillingProfile struct {
	ID          string  `json:"id"`
	IsCompany   bool    `json:"isCompany"`
	CompanyName *string `json:"companyName,omitempty"`
	Cui         *string `json:"cui,omitempty"`
	RegNumber   *string `json:"regNumber,omitempty"`
	Address     *string `json:"address,omitempty"`
	City        *string `json:"city,omitempty"`
	County      *string `json:"county,omitempty"`
	IsVatPayer  bool    `json:"isVatPayer"`
	BankName    *string `json:"bankName,omitempty"`
	Iban        *string `json:"iban,omitempty"`
	IsDefault   bool    `json:"isDefault"`
}

type Company struct {
	ID                    string             `json:"id"`
	CompanyName           string             `json:"companyName"`
	Cui                   string             `json:"cui"`
	CompanyType           CompanyType        `json:"companyType"`
	LegalRepresentative   string             `json:"legalRepresentative"`
	ContactEmail          string             `json:"contactEmail"`
	ContactPhone          string             `json:"contactPhone"`
	Address               string             `json:"address"`
	City                  string             `json:"city"`
	County                string             `json:"county"`
	Description           *string            `json:"description,omitempty"`
	LogoURL               *string            `json:"logoUrl,omitempty"`
	Status                CompanyStatus      `json:"status"`
	RejectionReason       *string            `json:"rejectionReason,omitempty"`
	RatingAvg             float64            `json:"ratingAvg"`
	TotalJobsCompleted    int                `json:"totalJobsCompleted"`
	Documents             []*CompanyDocument `json:"documents"`
	Workers               []*WorkerProfile   `json:"workers"`
	CommissionOverridePct *float64           `json:"commissionOverridePct,omitempty"`
	ServiceCategories     []*ServiceCategory `json:"serviceCategories"`
	Admin                 *User              `json:"admin,omitempty"`
	CreatedAt             time.Time          `json:"createdAt"`
	AnafVerification      *ANAFVerification  `json:"anafVerification,omitempty"`
	RegNumber             *string            `json:"regNumber,omitempty"`
	IsVatPayer            bool               `json:"isVatPayer"`
	BankName              *string            `json:"bankName,omitempty"`
	Iban                  *string            `json:"iban,omitempty"`
}

type CompanyApplicationInput struct {
	CompanyName         string      `json:"companyName"`
	Cui                 string      `json:"cui"`
	CompanyType         CompanyType `json:"companyType"`
	LegalRepresentative string      `json:"legalRepresentative"`
	ContactEmail        string      `json:"contactEmail"`
	ContactPhone        string      `json:"contactPhone"`
	Address             string      `json:"address"`
	City                string      `json:"city"`
	County              string      `json:"county"`
	Description         *string     `json:"description,omitempty"`
	CategoryIds         []string    `json:"categoryIds,omitempty"`
	RegNumber           *string     `json:"regNumber,omitempty"`
	IsVatPayer          *bool       `json:"isVatPayer,omitempty"`
	BankName            *string     `json:"bankName,omitempty"`
	Iban                *string     `json:"iban,omitempty"`
}

type CompanyApplicationResult struct {
	Company    *Company `json:"company"`
	ClaimToken *string  `json:"claimToken,omitempty"`
}

type CompanyCategoryRequest struct {
	ID          string                `json:"id"`
	Company     *Company              `json:"company"`
	Category    *ServiceCategory      `json:"category"`
	RequestType CategoryRequestType   `json:"requestType"`
	Status      CategoryRequestStatus `json:"status"`
	ReviewNote  *string               `json:"reviewNote,omitempty"`
	CreatedAt   time.Time             `json:"createdAt"`
	UpdatedAt   time.Time             `json:"updatedAt"`
}

type CompanyConnection struct {
	Edges      []*Company `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type CompanyDocument struct {
	ID              string         `json:"id"`
	DocumentType    string         `json:"documentType"`
	FileURL         string         `json:"fileUrl"`
	FileName        string         `json:"fileName"`
	Status          DocumentStatus `json:"status"`
	UploadedAt      time.Time      `json:"uploadedAt"`
	ReviewedAt      *time.Time     `json:"reviewedAt,omitempty"`
	RejectionReason *string        `json:"rejectionReason,omitempty"`
	Company         *Company       `json:"company"`
}

type CompanyEarningsSummary struct {
	TotalGross        int `json:"totalGross"`
	TotalCommission   int `json:"totalCommission"`
	TotalNet          int `json:"totalNet"`
	BookingCount      int `json:"bookingCount"`
	AveragePerBooking int `json:"averagePerBooking"`
}

type CompanyFinancialSummary struct {
	CompletedBookings int     `json:"completedBookings"`
	TotalRevenue      float64 `json:"totalRevenue"`
	TotalCommission   float64 `json:"totalCommission"`
	NetPayout         float64 `json:"netPayout"`
}

type CompanyPayout struct {
	ID             string            `json:"id"`
	Company        *Company          `json:"company,omitempty"`
	Amount         int               `json:"amount"`
	Currency       string            `json:"currency"`
	PeriodFrom     string            `json:"periodFrom"`
	PeriodTo       string            `json:"periodTo"`
	BookingCount   int               `json:"bookingCount"`
	Status         PayoutStatus      `json:"status"`
	PaidAt         *time.Time        `json:"paidAt,omitempty"`
	LineItems      []*PayoutLineItem `json:"lineItems"`
	CreatedAt      time.Time         `json:"createdAt"`
	StripePayoutID *string           `json:"stripePayoutId,omitempty"`
	FailureReason  *string           `json:"failureReason,omitempty"`
}

type CompanyPerformance struct {
	Company        *Company `json:"company"`
	TotalBookings  int      `json:"totalBookings"`
	TotalRevenue   float64  `json:"totalRevenue"`
	AverageRating  float64  `json:"averageRating"`
	CompletionRate float64  `json:"completionRate"`
}

type CompanyScorecard struct {
	ID               string  `json:"id"`
	CompanyName      string  `json:"companyName"`
	Status           string  `json:"status"`
	CompletedCount   int     `json:"completedCount"`
	CancelledCount   int     `json:"cancelledCount"`
	TotalBookings    int     `json:"totalBookings"`
	TotalRevenue     float64 `json:"totalRevenue"`
	CompletionRate   float64 `json:"completionRate"`
	CancellationRate float64 `json:"cancellationRate"`
	AvgRating        float64 `json:"avgRating"`
	ReviewCount      int     `json:"reviewCount"`
}

type CompanyWorkSchedule struct {
	ID        string `json:"id"`
	DayOfWeek int    `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	IsWorkDay bool   `json:"isWorkDay"`
}

type ConnectOnboardingLink struct {
	URL string `json:"url"`
}

type ContactMessageInput struct {
	Name    string `json:"name"`
	Email   string `json:"email"`
	Subject string `json:"subject"`
	Message string `json:"message"`
}

type Coordinates struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

type CreateBookingInput struct {
	AddressID           *string          `json:"addressId,omitempty"`
	Address             *AddAddressInput `json:"address,omitempty"`
	ServiceType         ServiceType      `json:"serviceType"`
	CategoryID          *string          `json:"categoryId,omitempty"`
	ScheduledDate       *string          `json:"scheduledDate,omitempty"`
	ScheduledStartTime  *string          `json:"scheduledStartTime,omitempty"`
	TimeSlots           []*TimeSlotInput `json:"timeSlots,omitempty"`
	PropertyType        *string          `json:"propertyType,omitempty"`
	NumRooms            int              `json:"numRooms"`
	NumBathrooms        int              `json:"numBathrooms"`
	AreaSqm             *int             `json:"areaSqm,omitempty"`
	HasPets             *bool            `json:"hasPets,omitempty"`
	SpecialInstructions *string          `json:"specialInstructions,omitempty"`
	Extras              []*ExtraInput    `json:"extras,omitempty"`
	GuestEmail          *string          `json:"guestEmail,omitempty"`
	GuestName           *string          `json:"guestName,omitempty"`
	GuestPhone          *string          `json:"guestPhone,omitempty"`
	PreferredWorkerID   *string          `json:"preferredWorkerId,omitempty"`
	SuggestedStartTime  *string          `json:"suggestedStartTime,omitempty"`
	Recurrence          *RecurrenceInput `json:"recurrence,omitempty"`
	CustomFields        *string          `json:"customFields,omitempty"`
	CityAreaID          *string          `json:"cityAreaId,omitempty"`
}

type CreatePromoCodeInput struct {
	Code           string   `json:"code"`
	Description    *string  `json:"description,omitempty"`
	DiscountType   string   `json:"discountType"`
	DiscountValue  float64  `json:"discountValue"`
	MinOrderAmount *float64 `json:"minOrderAmount,omitempty"`
	MaxUses        *int     `json:"maxUses,omitempty"`
	MaxUsesPerUser *int     `json:"maxUsesPerUser,omitempty"`
	ActiveFrom     *string  `json:"activeFrom,omitempty"`
	ActiveUntil    *string  `json:"activeUntil,omitempty"`
}

type CreateServiceCategoryInput struct {
	Slug          string   `json:"slug"`
	NameRo        string   `json:"nameRo"`
	NameEn        string   `json:"nameEn"`
	DescriptionRo *string  `json:"descriptionRo,omitempty"`
	DescriptionEn *string  `json:"descriptionEn,omitempty"`
	Icon          *string  `json:"icon,omitempty"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
	CommissionPct *float64 `json:"commissionPct,omitempty"`
	SortOrder     int      `json:"sortOrder"`
	IsActive      bool     `json:"isActive"`
	FormFields    *string  `json:"formFields,omitempty"`
}

type CreateServiceDefinitionInput struct {
	ServiceType        ServiceType  `json:"serviceType"`
	NameRo             string       `json:"nameRo"`
	NameEn             string       `json:"nameEn"`
	BasePricePerHour   float64      `json:"basePricePerHour"`
	MinHours           float64      `json:"minHours"`
	HoursPerRoom       float64      `json:"hoursPerRoom"`
	HoursPerBathroom   float64      `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64      `json:"hoursPer100Sqm"`
	HouseMultiplier    float64      `json:"houseMultiplier"`
	PetDurationMinutes int          `json:"petDurationMinutes"`
	IsActive           bool         `json:"isActive"`
	IncludedItems      []string     `json:"includedItems,omitempty"`
	CategoryID         *string      `json:"categoryId,omitempty"`
	PricingModel       PricingModel `json:"pricingModel"`
	PricePerSqm        *float64     `json:"pricePerSqm,omitempty"`
}

type CreateServiceExtraInput struct {
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	IsActive        bool    `json:"isActive"`
	AllowMultiple   bool    `json:"allowMultiple"`
	UnitLabel       *string `json:"unitLabel,omitempty"`
	CategoryID      *string `json:"categoryId,omitempty"`
}

type CreateSubscriptionInput struct {
	AddressID           *string          `json:"addressId,omitempty"`
	Address             *AddAddressInput `json:"address,omitempty"`
	ServiceType         ServiceType      `json:"serviceType"`
	RecurrenceType      RecurrenceType   `json:"recurrenceType"`
	DayOfWeek           int              `json:"dayOfWeek"`
	PreferredTime       string           `json:"preferredTime"`
	PropertyType        *string          `json:"propertyType,omitempty"`
	NumRooms            int              `json:"numRooms"`
	NumBathrooms        int              `json:"numBathrooms"`
	AreaSqm             *int             `json:"areaSqm,omitempty"`
	HasPets             *bool            `json:"hasPets,omitempty"`
	SpecialInstructions *string          `json:"specialInstructions,omitempty"`
	Extras              []*ExtraInput    `json:"extras,omitempty"`
	PreferredWorkerID   string           `json:"preferredWorkerId"`
	PaymentMethodID     string           `json:"paymentMethodId"`
}

type DailyRevenue struct {
	Date         string  `json:"date"`
	BookingCount int     `json:"bookingCount"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
}

type DemandSlot struct {
	DayOfWeek int `json:"dayOfWeek"`
	Hour      int `json:"hour"`
	Count     int `json:"count"`
}

type DisputeConnection struct {
	Edges      []*BookingDispute `json:"edges"`
	PageInfo   *PageInfo         `json:"pageInfo"`
	TotalCount int               `json:"totalCount"`
}

type EnabledCity struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	County            string      `json:"county"`
	IsActive          bool        `json:"isActive"`
	PricingMultiplier float64     `json:"pricingMultiplier"`
	Areas             []*CityArea `json:"areas"`
}

type ExtraInput struct {
	ExtraID  string `json:"extraId"`
	Quantity int    `json:"quantity"`
}

type ExtraLineItem struct {
	Extra     *ServiceExtra `json:"extra"`
	Quantity  int           `json:"quantity"`
	LineTotal float64       `json:"lineTotal"`
}

type InviteWorkerInput struct {
	FullName    string   `json:"fullName"`
	Email       string   `json:"email"`
	Phone       *string  `json:"phone,omitempty"`
	CategoryIds []string `json:"categoryIds,omitempty"`
}

type Invoice struct {
	ID                string             `json:"id"`
	InvoiceType       InvoiceType        `json:"invoiceType"`
	InvoiceNumber     *string            `json:"invoiceNumber,omitempty"`
	Status            InvoiceStatus      `json:"status"`
	SellerCompanyName string             `json:"sellerCompanyName"`
	SellerCui         string             `json:"sellerCui"`
	SellerRegNumber   *string            `json:"sellerRegNumber,omitempty"`
	SellerAddress     string             `json:"sellerAddress"`
	SellerCity        string             `json:"sellerCity"`
	SellerCounty      string             `json:"sellerCounty"`
	SellerIsVatPayer  bool               `json:"sellerIsVatPayer"`
	SellerBankName    *string            `json:"sellerBankName,omitempty"`
	SellerIban        *string            `json:"sellerIban,omitempty"`
	BuyerName         string             `json:"buyerName"`
	BuyerCui          *string            `json:"buyerCui,omitempty"`
	BuyerAddress      *string            `json:"buyerAddress,omitempty"`
	BuyerCity         *string            `json:"buyerCity,omitempty"`
	BuyerCounty       *string            `json:"buyerCounty,omitempty"`
	BuyerIsVatPayer   *bool              `json:"buyerIsVatPayer,omitempty"`
	SubtotalAmount    int                `json:"subtotalAmount"`
	VatRate           float64            `json:"vatRate"`
	VatAmount         int                `json:"vatAmount"`
	TotalAmount       int                `json:"totalAmount"`
	Currency          string             `json:"currency"`
	Booking           *Booking           `json:"booking,omitempty"`
	Company           *Company           `json:"company,omitempty"`
	EfacturaStatus    *string            `json:"efacturaStatus,omitempty"`
	DownloadURL       *string            `json:"downloadUrl,omitempty"`
	IssuedAt          *time.Time         `json:"issuedAt,omitempty"`
	DueDate           *string            `json:"dueDate,omitempty"`
	Notes             *string            `json:"notes,omitempty"`
	LineItems         []*InvoiceLineItem `json:"lineItems"`
	CreatedAt         time.Time          `json:"createdAt"`
}

type InvoiceAnalytics struct {
	TotalIssued int                   `json:"totalIssued"`
	TotalAmount int                   `json:"totalAmount"`
	TotalVat    int                   `json:"totalVat"`
	ByStatus    []*InvoiceStatusCount `json:"byStatus"`
	ByType      []*InvoiceTypeCount   `json:"byType"`
}

type InvoiceConnection struct {
	Edges      []*Invoice `json:"edges"`
	PageInfo   *PageInfo  `json:"pageInfo"`
	TotalCount int        `json:"totalCount"`
}

type InvoiceLineItem struct {
	ID               string  `json:"id"`
	DescriptionRo    string  `json:"descriptionRo"`
	DescriptionEn    *string `json:"descriptionEn,omitempty"`
	Quantity         float64 `json:"quantity"`
	UnitPrice        int     `json:"unitPrice"`
	VatRate          float64 `json:"vatRate"`
	VatAmount        int     `json:"vatAmount"`
	LineTotal        int     `json:"lineTotal"`
	LineTotalWithVat int     `json:"lineTotalWithVat"`
}

type InvoiceStatusCount struct {
	Status      InvoiceStatus `json:"status"`
	Count       int           `json:"count"`
	TotalAmount int           `json:"totalAmount"`
}

type InvoiceTypeCount struct {
	Type        InvoiceType `json:"type"`
	Count       int         `json:"count"`
	TotalAmount int         `json:"totalAmount"`
}

type JoinWaitlistInput struct {
	LeadType    WaitlistLeadType `json:"leadType"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Phone       *string          `json:"phone,omitempty"`
	City        *string          `json:"city,omitempty"`
	CompanyName *string          `json:"companyName,omitempty"`
	Message     *string          `json:"message,omitempty"`
}

type Mutation struct {
}

type Notification struct {
	ID        string         `json:"id"`
	Type      string         `json:"type"`
	Title     string         `json:"title"`
	Body      string         `json:"body"`
	Data      map[string]any `json:"data,omitempty"`
	IsRead    bool           `json:"isRead"`
	CreatedAt time.Time      `json:"createdAt"`
}

type NotificationConnection struct {
	Edges      []*Notification `json:"edges"`
	PageInfo   *PageInfo       `json:"pageInfo"`
	TotalCount int             `json:"totalCount"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PaymentHistoryConnection struct {
	Edges      []*PaymentHistoryEntry `json:"edges"`
	PageInfo   *PageInfo              `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

type PaymentHistoryEntry struct {
	ID        string                   `json:"id"`
	Booking   *Booking                 `json:"booking,omitempty"`
	Amount    int                      `json:"amount"`
	Currency  string                   `json:"currency"`
	Status    PaymentTransactionStatus `json:"status"`
	PaidAt    *time.Time               `json:"paidAt,omitempty"`
	CreatedAt time.Time                `json:"createdAt"`
}

type PaymentIntentResult struct {
	ClientSecret    string `json:"clientSecret"`
	PaymentIntentID string `json:"paymentIntentId"`
	Amount          int    `json:"amount"`
	Currency        string `json:"currency"`
}

type PaymentMethod struct {
	ID                    string `json:"id"`
	StripePaymentMethodID string `json:"stripePaymentMethodId"`
	CardLastFour          string `json:"cardLastFour"`
	CardBrand             string `json:"cardBrand"`
	CardExpMonth          *int   `json:"cardExpMonth,omitempty"`
	CardExpYear           *int   `json:"cardExpYear,omitempty"`
	IsDefault             bool   `json:"isDefault"`
}

type PaymentTransaction struct {
	ID                    string                   `json:"id"`
	BookingID             string                   `json:"bookingId"`
	Booking               *Booking                 `json:"booking,omitempty"`
	StripePaymentIntentID string                   `json:"stripePaymentIntentId"`
	AmountTotal           int                      `json:"amountTotal"`
	AmountCompany         int                      `json:"amountCompany"`
	AmountPlatformFee     int                      `json:"amountPlatformFee"`
	Currency              string                   `json:"currency"`
	Status                PaymentTransactionStatus `json:"status"`
	FailureReason         *string                  `json:"failureReason,omitempty"`
	RefundAmount          *int                     `json:"refundAmount,omitempty"`
	CreatedAt             time.Time                `json:"createdAt"`
	StripeChargeID        *string                  `json:"stripeChargeId,omitempty"`
	StripeDisputeID       *string                  `json:"stripeDisputeId,omitempty"`
}

type PayoutLineItem struct {
	ID               string   `json:"id"`
	Booking          *Booking `json:"booking,omitempty"`
	AmountGross      int      `json:"amountGross"`
	AmountCommission int      `json:"amountCommission"`
	AmountNet        int      `json:"amountNet"`
}

type PendingReviewCount struct {
	Applications      int `json:"applications"`
	CompanyDocuments  int `json:"companyDocuments"`
	WorkerDocuments   int `json:"workerDocuments"`
	WorkerActivations int `json:"workerActivations"`
	CategoryRequests  int `json:"categoryRequests"`
	Total             int `json:"total"`
}

type PersonalityAnswerInput struct {
	QuestionNumber int `json:"questionNumber"`
	Response       int `json:"response"`
}

type PersonalityAssessment struct {
	ID             string                   `json:"id"`
	WorkerID       string                   `json:"workerId"`
	FacetScores    []*PersonalityFacetScore `json:"facetScores"`
	IntegrityAvg   float64                  `json:"integrityAvg"`
	WorkQualityAvg float64                  `json:"workQualityAvg"`
	HasConcerns    bool                     `json:"hasConcerns"`
	FlaggedFacets  []string                 `json:"flaggedFacets"`
	CompletedAt    time.Time                `json:"completedAt"`
	Insights       *PersonalityInsights     `json:"insights,omitempty"`
}

type PersonalityFacetScore struct {
	FacetCode string `json:"facetCode"`
	FacetName string `json:"facetName"`
	Score     int    `json:"score"`
	MaxScore  int    `json:"maxScore"`
	IsFlagged bool   `json:"isFlagged"`
}

type PersonalityInsights struct {
	Summary           string    `json:"summary"`
	Strengths         []string  `json:"strengths"`
	Concerns          []string  `json:"concerns"`
	TeamFitAnalysis   string    `json:"teamFitAnalysis"`
	RecommendedAction string    `json:"recommendedAction"`
	Confidence        string    `json:"confidence"`
	AiModel           string    `json:"aiModel"`
	GeneratedAt       time.Time `json:"generatedAt"`
}

type PersonalityQuestion struct {
	Number    int    `json:"number"`
	FacetCode string `json:"facetCode"`
	Text      string `json:"text"`
}

type PlatformRevenueReport struct {
	TotalRevenue    int `json:"totalRevenue"`
	TotalCommission int `json:"totalCommission"`
	TotalPayouts    int `json:"totalPayouts"`
	PendingPayouts  int `json:"pendingPayouts"`
	TotalRefunds    int `json:"totalRefunds"`
	NetRevenue      int `json:"netRevenue"`
	BookingCount    int `json:"bookingCount"`
}

type PlatformSetting struct {
	Key         string    `json:"key"`
	Value       string    `json:"value"`
	ValueType   string    `json:"valueType"`
	Description *string   `json:"description,omitempty"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type PlatformStats struct {
	TotalClients            int     `json:"totalClients"`
	TotalCompanies          int     `json:"totalCompanies"`
	TotalWorkers            int     `json:"totalWorkers"`
	TotalBookings           int     `json:"totalBookings"`
	TotalRevenue            float64 `json:"totalRevenue"`
	PlatformCommissionTotal float64 `json:"platformCommissionTotal"`
	AverageRating           float64 `json:"averageRating"`
	BookingsThisMonth       int     `json:"bookingsThisMonth"`
	RevenueThisMonth        float64 `json:"revenueThisMonth"`
	NewClientsThisMonth     int     `json:"newClientsThisMonth"`
	NewCompaniesThisMonth   int     `json:"newCompaniesThisMonth"`
	BookingsLastMonth       int     `json:"bookingsLastMonth"`
	RevenueLastMonth        float64 `json:"revenueLastMonth"`
	NewClientsLastMonth     int     `json:"newClientsLastMonth"`
	NewCompaniesLastMonth   int     `json:"newCompaniesLastMonth"`
}

type PlatformTotals struct {
	TotalCompleted  int     `json:"totalCompleted"`
	TotalBookings   int     `json:"totalBookings"`
	TotalRevenue    float64 `json:"totalRevenue"`
	TotalCommission float64 `json:"totalCommission"`
	UniqueClients   int     `json:"uniqueClients"`
	ActiveCompanies int     `json:"activeCompanies"`
}

type PriceAuditConnection struct {
	Entries    []*PriceAuditEntry `json:"entries"`
	TotalCount int                `json:"totalCount"`
}

type PriceAuditEntry struct {
	ID             string    `json:"id"`
	EntityType     string    `json:"entityType"`
	EntityID       string    `json:"entityId"`
	FieldName      string    `json:"fieldName"`
	OldValue       *string   `json:"oldValue,omitempty"`
	NewValue       *string   `json:"newValue,omitempty"`
	ChangedByName  *string   `json:"changedByName,omitempty"`
	ChangedByEmail *string   `json:"changedByEmail,omitempty"`
	ChangedAt      time.Time `json:"changedAt"`
	Reason         *string   `json:"reason,omitempty"`
}

type PriceEstimate struct {
	HourlyRate            float64          `json:"hourlyRate"`
	EstimatedHours        float64          `json:"estimatedHours"`
	PropertyMultiplier    float64          `json:"propertyMultiplier"`
	CityPricingMultiplier float64          `json:"cityPricingMultiplier"`
	PetsSurcharge         float64          `json:"petsSurcharge"`
	Subtotal              float64          `json:"subtotal"`
	Extras                []*ExtraLineItem `json:"extras"`
	Total                 float64          `json:"total"`
	PricingModel          PricingModel     `json:"pricingModel"`
	AreaTotal             *float64         `json:"areaTotal,omitempty"`
}

type PriceEstimateInput struct {
	ServiceType  ServiceType   `json:"serviceType"`
	NumRooms     int           `json:"numRooms"`
	NumBathrooms int           `json:"numBathrooms"`
	AreaSqm      *int          `json:"areaSqm,omitempty"`
	PropertyType *string       `json:"propertyType,omitempty"`
	HasPets      *bool         `json:"hasPets,omitempty"`
	Extras       []*ExtraInput `json:"extras,omitempty"`
	City         *string       `json:"city,omitempty"`
}

type PromoCode struct {
	ID             string     `json:"id"`
	Code           string     `json:"code"`
	Description    *string    `json:"description,omitempty"`
	DiscountType   string     `json:"discountType"`
	DiscountValue  float64    `json:"discountValue"`
	MinOrderAmount float64    `json:"minOrderAmount"`
	MaxUses        *int       `json:"maxUses,omitempty"`
	UsesCount      int        `json:"usesCount"`
	MaxUsesPerUser int        `json:"maxUsesPerUser"`
	ActiveFrom     time.Time  `json:"activeFrom"`
	ActiveUntil    *time.Time `json:"activeUntil,omitempty"`
	IsActive       bool       `json:"isActive"`
	CreatedAt      time.Time  `json:"createdAt"`
}

type PromoCodeConnection struct {
	Edges      []*PromoCode `json:"edges"`
	PageInfo   *PageInfo    `json:"pageInfo"`
	TotalCount int          `json:"totalCount"`
}

type PromoCodeValidation struct {
	Valid          bool       `json:"valid"`
	PromoCode      *PromoCode `json:"promoCode,omitempty"`
	DiscountAmount float64    `json:"discountAmount"`
	ErrorMessage   *string    `json:"errorMessage,omitempty"`
}

type Query struct {
}

type RecurrenceInput struct {
	Type      RecurrenceType `json:"type"`
	DayOfWeek int            `json:"dayOfWeek"`
}

type RecurringDiscount struct {
	RecurrenceType RecurrenceType `json:"recurrenceType"`
	DiscountPct    float64        `json:"discountPct"`
	IsActive       bool           `json:"isActive"`
}

type ReferralDiscountInfo struct {
	ID        string     `json:"id"`
	Status    string     `json:"status"`
	EarnedAt  time.Time  `json:"earnedAt"`
	ExpiresAt *time.Time `json:"expiresAt,omitempty"`
}

type ReferralSignupProgress struct {
	JoinedCount    int `json:"joinedCount"`
	CompletedCount int `json:"completedCount"`
	RequiredCount  int `json:"requiredCount"`
}

type ReferralStatus struct {
	Code               *string                 `json:"code,omitempty"`
	ShareURL           *string                 `json:"shareUrl,omitempty"`
	CurrentProgress    *ReferralSignupProgress `json:"currentProgress"`
	AvailableDiscounts int                     `json:"availableDiscounts"`
	Discounts          []*ReferralDiscountInfo `json:"discounts"`
}

type RefundRequest struct {
	ID             string       `json:"id"`
	Booking        *Booking     `json:"booking,omitempty"`
	RequestedBy    *User        `json:"requestedBy,omitempty"`
	ApprovedBy     *User        `json:"approvedBy,omitempty"`
	Amount         int          `json:"amount"`
	Reason         string       `json:"reason"`
	Status         RefundStatus `json:"status"`
	ProcessedAt    *time.Time   `json:"processedAt,omitempty"`
	CreatedAt      time.Time    `json:"createdAt"`
	StripeRefundID *string      `json:"stripeRefundId,omitempty"`
}

type RequestOtpResponse struct {
	Success bool    `json:"success"`
	DevCode *string `json:"devCode,omitempty"`
}

type RevenueByMonth struct {
	Month        string  `json:"month"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
	BookingCount int     `json:"bookingCount"`
}

type Review struct {
	ID                  string         `json:"id"`
	Booking             *Booking       `json:"booking,omitempty"`
	Reviewer            *User          `json:"reviewer,omitempty"`
	Worker              *WorkerProfile `json:"worker,omitempty"`
	Rating              int            `json:"rating"`
	RatingPunctuality   *int           `json:"ratingPunctuality,omitempty"`
	RatingQuality       *int           `json:"ratingQuality,omitempty"`
	RatingCommunication *int           `json:"ratingCommunication,omitempty"`
	RatingValue         *int           `json:"ratingValue,omitempty"`
	Comment             *string        `json:"comment,omitempty"`
	ReviewType          string         `json:"reviewType"`
	Status              string         `json:"status"`
	Photos              []*ReviewPhoto `json:"photos"`
	CreatedAt           time.Time      `json:"createdAt"`
}

type ReviewConnection struct {
	Reviews    []*Review `json:"reviews"`
	TotalCount int       `json:"totalCount"`
}

type ReviewPhoto struct {
	ID        string `json:"id"`
	PhotoURL  string `json:"photoUrl"`
	SortOrder int    `json:"sortOrder"`
}

type ServiceCategory struct {
	ID            string               `json:"id"`
	Slug          string               `json:"slug"`
	NameRo        string               `json:"nameRo"`
	NameEn        string               `json:"nameEn"`
	DescriptionRo *string              `json:"descriptionRo,omitempty"`
	DescriptionEn *string              `json:"descriptionEn,omitempty"`
	Icon          *string              `json:"icon,omitempty"`
	ImageURL      *string              `json:"imageUrl,omitempty"`
	CommissionPct *float64             `json:"commissionPct,omitempty"`
	SortOrder     int                  `json:"sortOrder"`
	IsActive      bool                 `json:"isActive"`
	Services      []*ServiceDefinition `json:"services"`
	FormFields    *string              `json:"formFields,omitempty"`
}

type ServiceDefinition struct {
	ID                 string       `json:"id"`
	ServiceType        ServiceType  `json:"serviceType"`
	NameRo             string       `json:"nameRo"`
	NameEn             string       `json:"nameEn"`
	DescriptionRo      *string      `json:"descriptionRo,omitempty"`
	DescriptionEn      *string      `json:"descriptionEn,omitempty"`
	BasePricePerHour   float64      `json:"basePricePerHour"`
	MinHours           float64      `json:"minHours"`
	HoursPerRoom       float64      `json:"hoursPerRoom"`
	HoursPerBathroom   float64      `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64      `json:"hoursPer100Sqm"`
	HouseMultiplier    float64      `json:"houseMultiplier"`
	PetDurationMinutes int          `json:"petDurationMinutes"`
	Icon               *string      `json:"icon,omitempty"`
	IsActive           bool         `json:"isActive"`
	IncludedItems      []string     `json:"includedItems"`
	CategoryID         *string      `json:"categoryId,omitempty"`
	PricingModel       PricingModel `json:"pricingModel"`
	PricePerSqm        *float64     `json:"pricePerSqm,omitempty"`
}

type ServiceExtra struct {
	ID              string  `json:"id"`
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	Icon            *string `json:"icon,omitempty"`
	IsActive        bool    `json:"isActive"`
	AllowMultiple   bool    `json:"allowMultiple"`
	UnitLabel       *string `json:"unitLabel,omitempty"`
	CategoryID      *string `json:"categoryId,omitempty"`
}

type ServiceRevenue struct {
	ServiceType  ServiceType `json:"serviceType"`
	BookingCount int         `json:"bookingCount"`
	Revenue      float64     `json:"revenue"`
}

type ServiceSubscription struct {
	ID                      string             `json:"id"`
	Client                  *User              `json:"client,omitempty"`
	Company                 *Company           `json:"company,omitempty"`
	Worker                  *WorkerProfile     `json:"worker,omitempty"`
	Address                 *Address           `json:"address,omitempty"`
	RecurrenceType          RecurrenceType     `json:"recurrenceType"`
	DayOfWeek               *int               `json:"dayOfWeek,omitempty"`
	PreferredTime           string             `json:"preferredTime"`
	ServiceType             ServiceType        `json:"serviceType"`
	ServiceName             string             `json:"serviceName"`
	PropertyType            *string            `json:"propertyType,omitempty"`
	NumRooms                *int               `json:"numRooms,omitempty"`
	NumBathrooms            *int               `json:"numBathrooms,omitempty"`
	AreaSqm                 *int               `json:"areaSqm,omitempty"`
	HasPets                 *bool              `json:"hasPets,omitempty"`
	SpecialInstructions     *string            `json:"specialInstructions,omitempty"`
	HourlyRate              float64            `json:"hourlyRate"`
	EstimatedDurationHours  float64            `json:"estimatedDurationHours"`
	PerSessionOriginal      float64            `json:"perSessionOriginal"`
	DiscountPct             float64            `json:"discountPct"`
	PerSessionDiscounted    float64            `json:"perSessionDiscounted"`
	SessionsPerMonth        int                `json:"sessionsPerMonth"`
	MonthlyAmount           float64            `json:"monthlyAmount"`
	PlatformCommissionPct   float64            `json:"platformCommissionPct"`
	StripeSubscriptionID    *string            `json:"stripeSubscriptionId,omitempty"`
	Status                  SubscriptionStatus `json:"status"`
	CurrentPeriodStart      *time.Time         `json:"currentPeriodStart,omitempty"`
	CurrentPeriodEnd        *time.Time         `json:"currentPeriodEnd,omitempty"`
	CancelledAt             *time.Time         `json:"cancelledAt,omitempty"`
	CancellationReason      *string            `json:"cancellationReason,omitempty"`
	PausedAt                *time.Time         `json:"pausedAt,omitempty"`
	CreatedAt               time.Time          `json:"createdAt"`
	WorkerChangeRequestedAt *time.Time         `json:"workerChangeRequestedAt,omitempty"`
	WorkerChangeReason      *string            `json:"workerChangeReason,omitempty"`
	Bookings                []*Booking         `json:"bookings"`
	UpcomingBookings        []*Booking         `json:"upcomingBookings"`
	TotalBookings           int                `json:"totalBookings"`
	CompletedBookings       int                `json:"completedBookings"`
	Extras                  []*BookingExtra    `json:"extras"`
}

type SetupIntentResult struct {
	ClientSecret string `json:"clientSecret"`
}

type StripeConnectStatus struct {
	AccountID        *string                 `json:"accountId,omitempty"`
	OnboardingStatus ConnectOnboardingStatus `json:"onboardingStatus"`
	ChargesEnabled   bool                    `json:"chargesEnabled"`
	PayoutsEnabled   bool                    `json:"payoutsEnabled"`
}

type SubmitReviewInput struct {
	BookingID           string  `json:"bookingId"`
	Rating              int     `json:"rating"`
	RatingPunctuality   *int    `json:"ratingPunctuality,omitempty"`
	RatingQuality       *int    `json:"ratingQuality,omitempty"`
	RatingCommunication *int    `json:"ratingCommunication,omitempty"`
	RatingValue         *int    `json:"ratingValue,omitempty"`
	Comment             *string `json:"comment,omitempty"`
}

type SubscriptionConnection struct {
	Edges      []*ServiceSubscription `json:"edges"`
	PageInfo   *PageInfo              `json:"pageInfo"`
	TotalCount int                    `json:"totalCount"`
}

type SubscriptionPricing struct {
	PerSessionOriginal   float64 `json:"perSessionOriginal"`
	DiscountPct          float64 `json:"discountPct"`
	PerSessionDiscounted float64 `json:"perSessionDiscounted"`
	SessionsPerMonth     int     `json:"sessionsPerMonth"`
	MonthlyAmount        float64 `json:"monthlyAmount"`
}

type SubscriptionStats struct {
	ActiveCount             int `json:"activeCount"`
	PausedCount             int `json:"pausedCount"`
	PastDueCount            int `json:"pastDueCount"`
	CancelledCount          int `json:"cancelledCount"`
	MonthlyRecurringRevenue int `json:"monthlyRecurringRevenue"`
}

type SubscriptionWorkerAvailabilityCheck struct {
	SubscriptionID string                       `json:"subscriptionId"`
	WorkerID       string                       `json:"workerId"`
	WorkerName     string                       `json:"workerName"`
	AllAvailable   bool                         `json:"allAvailable"`
	Bookings       []*BookingAvailabilityStatus `json:"bookings"`
	AvailableCount int                          `json:"availableCount"`
	ConflictCount  int                          `json:"conflictCount"`
}

type SubscriptionWorkerSuggestion struct {
	Worker             *WorkerProfile `json:"worker"`
	Company            *Company       `json:"company"`
	MatchScore         float64        `json:"matchScore"`
	AvailableWeeks     int            `json:"availableWeeks"`
	TotalWeeks         int            `json:"totalWeeks"`
	ConsistencyPct     float64        `json:"consistencyPct"`
	SuggestedTimeStart *string        `json:"suggestedTimeStart,omitempty"`
	SuggestedTimeEnd   *string        `json:"suggestedTimeEnd,omitempty"`
}

type TimeSlotInput struct {
	Date      string `json:"date"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
}

type TopCompany struct {
	ID           string  `json:"id"`
	CompanyName  string  `json:"companyName"`
	BookingCount int     `json:"bookingCount"`
	Revenue      float64 `json:"revenue"`
	Commission   float64 `json:"commission"`
}

type UpdateAddressInput struct {
	Label         *string  `json:"label,omitempty"`
	StreetAddress *string  `json:"streetAddress,omitempty"`
	City          *string  `json:"city,omitempty"`
	County        *string  `json:"county,omitempty"`
	PostalCode    *string  `json:"postalCode,omitempty"`
	Floor         *string  `json:"floor,omitempty"`
	Apartment     *string  `json:"apartment,omitempty"`
	EntryCode     *string  `json:"entryCode,omitempty"`
	Latitude      *float64 `json:"latitude,omitempty"`
	Longitude     *float64 `json:"longitude,omitempty"`
	Notes         *string  `json:"notes,omitempty"`
}

type UpdateCompanyInput struct {
	Description  *string                 `json:"description,omitempty"`
	ContactPhone *string                 `json:"contactPhone,omitempty"`
	ContactEmail *string                 `json:"contactEmail,omitempty"`
	WorkSchedule []*WorkScheduleDayInput `json:"workSchedule,omitempty"`
	RegNumber    *string                 `json:"regNumber,omitempty"`
	IsVatPayer   *bool                   `json:"isVatPayer,omitempty"`
	BankName     *string                 `json:"bankName,omitempty"`
	Iban         *string                 `json:"iban,omitempty"`
}

type UpdateProfileInput struct {
	FullName          *string `json:"fullName,omitempty"`
	Phone             *string `json:"phone,omitempty"`
	AvatarURL         *string `json:"avatarUrl,omitempty"`
	PreferredLanguage *string `json:"preferredLanguage,omitempty"`
}

type UpdatePromoCodeInput struct {
	Description    *string  `json:"description,omitempty"`
	DiscountType   *string  `json:"discountType,omitempty"`
	DiscountValue  *float64 `json:"discountValue,omitempty"`
	MinOrderAmount *float64 `json:"minOrderAmount,omitempty"`
	MaxUses        *int     `json:"maxUses,omitempty"`
	MaxUsesPerUser *int     `json:"maxUsesPerUser,omitempty"`
	ActiveFrom     *string  `json:"activeFrom,omitempty"`
	ActiveUntil    *string  `json:"activeUntil,omitempty"`
	IsActive       *bool    `json:"isActive,omitempty"`
}

type UpdateServiceCategoryInput struct {
	ID            string   `json:"id"`
	NameRo        string   `json:"nameRo"`
	NameEn        string   `json:"nameEn"`
	DescriptionRo *string  `json:"descriptionRo,omitempty"`
	DescriptionEn *string  `json:"descriptionEn,omitempty"`
	Icon          *string  `json:"icon,omitempty"`
	ImageURL      *string  `json:"imageUrl,omitempty"`
	CommissionPct *float64 `json:"commissionPct,omitempty"`
	SortOrder     int      `json:"sortOrder"`
	IsActive      bool     `json:"isActive"`
	FormFields    *string  `json:"formFields,omitempty"`
}

type UpdateServiceDefinitionInput struct {
	ID                 string       `json:"id"`
	NameRo             string       `json:"nameRo"`
	NameEn             string       `json:"nameEn"`
	BasePricePerHour   float64      `json:"basePricePerHour"`
	MinHours           float64      `json:"minHours"`
	HoursPerRoom       float64      `json:"hoursPerRoom"`
	HoursPerBathroom   float64      `json:"hoursPerBathroom"`
	HoursPer100Sqm     float64      `json:"hoursPer100Sqm"`
	HouseMultiplier    float64      `json:"houseMultiplier"`
	PetDurationMinutes int          `json:"petDurationMinutes"`
	IsActive           bool         `json:"isActive"`
	IncludedItems      []string     `json:"includedItems,omitempty"`
	CategoryID         *string      `json:"categoryId,omitempty"`
	PricingModel       PricingModel `json:"pricingModel"`
	PricePerSqm        *float64     `json:"pricePerSqm,omitempty"`
}

type UpdateServiceExtraInput struct {
	ID              string  `json:"id"`
	NameRo          string  `json:"nameRo"`
	NameEn          string  `json:"nameEn"`
	Price           float64 `json:"price"`
	DurationMinutes int     `json:"durationMinutes"`
	IsActive        bool    `json:"isActive"`
	AllowMultiple   bool    `json:"allowMultiple"`
	UnitLabel       *string `json:"unitLabel,omitempty"`
	CategoryID      *string `json:"categoryId,omitempty"`
}

type UpdateWorkerProfileInput struct {
	Bio   *string `json:"bio,omitempty"`
	Phone *string `json:"phone,omitempty"`
}

type UploadResult struct {
	URL      string `json:"url"`
	FileName string `json:"fileName"`
}

type User struct {
	ID                string         `json:"id"`
	Email             string         `json:"email"`
	FullName          string         `json:"fullName"`
	Phone             *string        `json:"phone,omitempty"`
	PhoneVerified     bool           `json:"phoneVerified"`
	AvatarURL         *string        `json:"avatarUrl,omitempty"`
	Role              UserRole       `json:"role"`
	Status            UserStatus     `json:"status"`
	PreferredLanguage string         `json:"preferredLanguage"`
	CreatedAt         time.Time      `json:"createdAt"`
	WorkerProfile     *WorkerProfile `json:"workerProfile,omitempty"`
}

type UserConnection struct {
	Users      []*User `json:"users"`
	TotalCount int     `json:"totalCount"`
}

type WaitlistLead struct {
	ID          string           `json:"id"`
	LeadType    WaitlistLeadType `json:"leadType"`
	Name        string           `json:"name"`
	Email       string           `json:"email"`
	Phone       *string          `json:"phone,omitempty"`
	City        *string          `json:"city,omitempty"`
	CompanyName *string          `json:"companyName,omitempty"`
	Message     *string          `json:"message,omitempty"`
	CreatedAt   time.Time        `json:"createdAt"`
	IsConverted *bool            `json:"isConverted,omitempty"`
}

type WaitlistStats struct {
	ClientCount  int `json:"clientCount"`
	CompanyCount int `json:"companyCount"`
	TotalCount   int `json:"totalCount"`
}

type WorkScheduleDayInput struct {
	DayOfWeek int    `json:"dayOfWeek"`
	StartTime string `json:"startTime"`
	EndTime   string `json:"endTime"`
	IsWorkDay bool   `json:"isWorkDay"`
}

type WorkerAvailabilityCheck struct {
	Available bool     `json:"available"`
	Reason    *string  `json:"reason,omitempty"`
	Conflicts []string `json:"conflicts"`
}

type WorkerDailyEarnings struct {
	Date   string  `json:"date"`
	Amount float64 `json:"amount"`
}

type WorkerDateOverride struct {
	ID          string `json:"id"`
	Date        string `json:"date"`
	IsAvailable bool   `json:"isAvailable"`
	StartTime   string `json:"startTime"`
	EndTime     string `json:"endTime"`
}

type WorkerDocument struct {
	ID              string         `json:"id"`
	DocumentType    string         `json:"documentType"`
	FileURL         string         `json:"fileUrl"`
	FileName        string         `json:"fileName"`
	Status          DocumentStatus `json:"status"`
	UploadedAt      time.Time      `json:"uploadedAt"`
	ReviewedAt      *time.Time     `json:"reviewedAt,omitempty"`
	RejectionReason *string        `json:"rejectionReason,omitempty"`
	Worker          *WorkerProfile `json:"worker"`
}

type WorkerPerformance struct {
	WorkerID           string  `json:"workerId"`
	FullName           string  `json:"fullName"`
	RatingAvg          float64 `json:"ratingAvg"`
	TotalCompletedJobs int     `json:"totalCompletedJobs"`
	ThisMonthCompleted int     `json:"thisMonthCompleted"`
	TotalEarnings      float64 `json:"totalEarnings"`
	ThisMonthEarnings  float64 `json:"thisMonthEarnings"`
}

type WorkerProfile struct {
	ID                    string                 `json:"id"`
	UserID                *string                `json:"userId,omitempty"`
	User                  *User                  `json:"user,omitempty"`
	Company               *Company               `json:"company,omitempty"`
	FullName              string                 `json:"fullName"`
	Phone                 *string                `json:"phone,omitempty"`
	Email                 *string                `json:"email,omitempty"`
	Bio                   *string                `json:"bio,omitempty"`
	Status                WorkerStatus           `json:"status"`
	IsCompanyAdmin        bool                   `json:"isCompanyAdmin"`
	InviteToken           *string                `json:"inviteToken,omitempty"`
	RatingAvg             float64                `json:"ratingAvg"`
	TotalJobsCompleted    int                    `json:"totalJobsCompleted"`
	Documents             []*WorkerDocument      `json:"documents"`
	PersonalityAssessment *PersonalityAssessment `json:"personalityAssessment,omitempty"`
	Availability          []*AvailabilitySlot    `json:"availability"`
	ServiceCategories     []*ServiceCategory     `json:"serviceCategories"`
	CreatedAt             time.Time              `json:"createdAt"`
	MaxDailyBookings      *int                   `json:"maxDailyBookings,omitempty"`
}

type WorkerStats struct {
	TotalJobsCompleted int     `json:"totalJobsCompleted"`
	AverageRating      float64 `json:"averageRating"`
	TotalReviews       int     `json:"totalReviews"`
	ThisMonthJobs      int     `json:"thisMonthJobs"`
	ThisMonthEarnings  float64 `json:"thisMonthEarnings"`
}

type WorkerSuggestion struct {
	Worker             *WorkerProfile `json:"worker"`
	Company            *Company       `json:"company"`
	AvailabilityStatus string         `json:"availabilityStatus"`
	AvailableFrom      *string        `json:"availableFrom,omitempty"`
	AvailableTo        *string        `json:"availableTo,omitempty"`
	SuggestedStartTime *string        `json:"suggestedStartTime,omitempty"`
	SuggestedEndTime   *string        `json:"suggestedEndTime,omitempty"`
	SuggestedSlotIndex *int           `json:"suggestedSlotIndex,omitempty"`
	SuggestedDate      *string        `json:"suggestedDate,omitempty"`
	MatchScore         float64        `json:"matchScore"`
}

type BookingOrderField string

const (
	BookingOrderFieldCreatedAt      BookingOrderField = "CREATED_AT"
	BookingOrderFieldScheduledDate  BookingOrderField = "SCHEDULED_DATE"
	BookingOrderFieldEstimatedTotal BookingOrderField = "ESTIMATED_TOTAL"
)

var AllBookingOrderField = []BookingOrderField{
	BookingOrderFieldCreatedAt,
	BookingOrderFieldScheduledDate,
	BookingOrderFieldEstimatedTotal,
}

func (e BookingOrderField) IsValid() bool {
	switch e {
	case BookingOrderFieldCreatedAt, BookingOrderFieldScheduledDate, BookingOrderFieldEstimatedTotal:
		return true
	}
	return false
}

func (e BookingOrderField) String() string {
	return string(e)
}

func (e *BookingOrderField) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingOrderField", str)
	}
	return nil
}

func (e BookingOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingOrderField) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingOrderField) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingStatus string

const (
	BookingStatusAssigned           BookingStatus = "ASSIGNED"
	BookingStatusConfirmed          BookingStatus = "CONFIRMED"
	BookingStatusInProgress         BookingStatus = "IN_PROGRESS"
	BookingStatusCompleted          BookingStatus = "COMPLETED"
	BookingStatusCancelledByClient  BookingStatus = "CANCELLED_BY_CLIENT"
	BookingStatusCancelledByCompany BookingStatus = "CANCELLED_BY_COMPANY"
	BookingStatusCancelledByAdmin   BookingStatus = "CANCELLED_BY_ADMIN"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusAssigned,
	BookingStatusConfirmed,
	BookingStatusInProgress,
	BookingStatusCompleted,
	BookingStatusCancelledByClient,
	BookingStatusCancelledByCompany,
	BookingStatusCancelledByAdmin,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusAssigned, BookingStatusConfirmed, BookingStatusInProgress, BookingStatusCompleted, BookingStatusCancelledByClient, BookingStatusCancelledByCompany, BookingStatusCancelledByAdmin:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CategoryRequestStatus string

const (
	CategoryRequestStatusPending  CategoryRequestStatus = "PENDING"
	CategoryRequestStatusApproved CategoryRequestStatus = "APPROVED"
	CategoryRequestStatusRejected CategoryRequestStatus = "REJECTED"
)

var AllCategoryRequestStatus = []CategoryRequestStatus{
	CategoryRequestStatusPending,
	CategoryRequestStatusApproved,
	CategoryRequestStatusRejected,
}

func (e CategoryRequestStatus) IsValid() bool {
	switch e {
	case CategoryRequestStatusPending, CategoryRequestStatusApproved, CategoryRequestStatusRejected:
		return true
	}
	return false
}

func (e CategoryRequestStatus) String() string {
	return string(e)
}

func (e *CategoryRequestStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryRequestStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryRequestStatus", str)
	}
	return nil
}

func (e CategoryRequestStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryRequestStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryRequestStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CategoryRequestType string

const (
	CategoryRequestTypeActivate   CategoryRequestType = "ACTIVATE"
	CategoryRequestTypeDeactivate CategoryRequestType = "DEACTIVATE"
)

var AllCategoryRequestType = []CategoryRequestType{
	CategoryRequestTypeActivate,
	CategoryRequestTypeDeactivate,
}

func (e CategoryRequestType) IsValid() bool {
	switch e {
	case CategoryRequestTypeActivate, CategoryRequestTypeDeactivate:
		return true
	}
	return false
}

func (e CategoryRequestType) String() string {
	return string(e)
}

func (e *CategoryRequestType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CategoryRequestType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CategoryRequestType", str)
	}
	return nil
}

func (e CategoryRequestType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CategoryRequestType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CategoryRequestType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyStatus string

const (
	CompanyStatusPendingReview CompanyStatus = "PENDING_REVIEW"
	CompanyStatusApproved      CompanyStatus = "APPROVED"
	CompanyStatusRejected      CompanyStatus = "REJECTED"
	CompanyStatusSuspended     CompanyStatus = "SUSPENDED"
)

var AllCompanyStatus = []CompanyStatus{
	CompanyStatusPendingReview,
	CompanyStatusApproved,
	CompanyStatusRejected,
	CompanyStatusSuspended,
}

func (e CompanyStatus) IsValid() bool {
	switch e {
	case CompanyStatusPendingReview, CompanyStatusApproved, CompanyStatusRejected, CompanyStatusSuspended:
		return true
	}
	return false
}

func (e CompanyStatus) String() string {
	return string(e)
}

func (e *CompanyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyStatus", str)
	}
	return nil
}

func (e CompanyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CompanyType string

const (
	CompanyTypeSrl CompanyType = "SRL"
	CompanyTypePfa CompanyType = "PFA"
	CompanyTypeIi  CompanyType = "II"
)

var AllCompanyType = []CompanyType{
	CompanyTypeSrl,
	CompanyTypePfa,
	CompanyTypeIi,
}

func (e CompanyType) IsValid() bool {
	switch e {
	case CompanyTypeSrl, CompanyTypePfa, CompanyTypeIi:
		return true
	}
	return false
}

func (e CompanyType) String() string {
	return string(e)
}

func (e *CompanyType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CompanyType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CompanyType", str)
	}
	return nil
}

func (e CompanyType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CompanyType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CompanyType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectOnboardingStatus string

const (
	ConnectOnboardingStatusNotStarted ConnectOnboardingStatus = "NOT_STARTED"
	ConnectOnboardingStatusPending    ConnectOnboardingStatus = "PENDING"
	ConnectOnboardingStatusComplete   ConnectOnboardingStatus = "COMPLETE"
	ConnectOnboardingStatusRestricted ConnectOnboardingStatus = "RESTRICTED"
)

var AllConnectOnboardingStatus = []ConnectOnboardingStatus{
	ConnectOnboardingStatusNotStarted,
	ConnectOnboardingStatusPending,
	ConnectOnboardingStatusComplete,
	ConnectOnboardingStatusRestricted,
}

func (e ConnectOnboardingStatus) IsValid() bool {
	switch e {
	case ConnectOnboardingStatusNotStarted, ConnectOnboardingStatusPending, ConnectOnboardingStatusComplete, ConnectOnboardingStatusRestricted:
		return true
	}
	return false
}

func (e ConnectOnboardingStatus) String() string {
	return string(e)
}

func (e *ConnectOnboardingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectOnboardingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectOnboardingStatus", str)
	}
	return nil
}

func (e ConnectOnboardingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectOnboardingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectOnboardingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DisputeReason string

const (
	DisputeReasonPoorQuality    DisputeReason = "POOR_QUALITY"
	DisputeReasonNoShow         DisputeReason = "NO_SHOW"
	DisputeReasonPropertyDamage DisputeReason = "PROPERTY_DAMAGE"
	DisputeReasonIncompleteJob  DisputeReason = "INCOMPLETE_JOB"
	DisputeReasonOvercharge     DisputeReason = "OVERCHARGE"
	DisputeReasonOther          DisputeReason = "OTHER"
)

var AllDisputeReason = []DisputeReason{
	DisputeReasonPoorQuality,
	DisputeReasonNoShow,
	DisputeReasonPropertyDamage,
	DisputeReasonIncompleteJob,
	DisputeReasonOvercharge,
	DisputeReasonOther,
}

func (e DisputeReason) IsValid() bool {
	switch e {
	case DisputeReasonPoorQuality, DisputeReasonNoShow, DisputeReasonPropertyDamage, DisputeReasonIncompleteJob, DisputeReasonOvercharge, DisputeReasonOther:
		return true
	}
	return false
}

func (e DisputeReason) String() string {
	return string(e)
}

func (e *DisputeReason) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DisputeReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DisputeReason", str)
	}
	return nil
}

func (e DisputeReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DisputeReason) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DisputeReason) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DisputeStatus string

const (
	DisputeStatusOpen                  DisputeStatus = "OPEN"
	DisputeStatusCompanyResponded      DisputeStatus = "COMPANY_RESPONDED"
	DisputeStatusUnderReview           DisputeStatus = "UNDER_REVIEW"
	DisputeStatusResolvedRefundFull    DisputeStatus = "RESOLVED_REFUND_FULL"
	DisputeStatusResolvedRefundPartial DisputeStatus = "RESOLVED_REFUND_PARTIAL"
	DisputeStatusResolvedNoRefund      DisputeStatus = "RESOLVED_NO_REFUND"
	DisputeStatusAutoClosed            DisputeStatus = "AUTO_CLOSED"
	DisputeStatusResolvedRemediation   DisputeStatus = "RESOLVED_REMEDIATION"
)

var AllDisputeStatus = []DisputeStatus{
	DisputeStatusOpen,
	DisputeStatusCompanyResponded,
	DisputeStatusUnderReview,
	DisputeStatusResolvedRefundFull,
	DisputeStatusResolvedRefundPartial,
	DisputeStatusResolvedNoRefund,
	DisputeStatusAutoClosed,
	DisputeStatusResolvedRemediation,
}

func (e DisputeStatus) IsValid() bool {
	switch e {
	case DisputeStatusOpen, DisputeStatusCompanyResponded, DisputeStatusUnderReview, DisputeStatusResolvedRefundFull, DisputeStatusResolvedRefundPartial, DisputeStatusResolvedNoRefund, DisputeStatusAutoClosed, DisputeStatusResolvedRemediation:
		return true
	}
	return false
}

func (e DisputeStatus) String() string {
	return string(e)
}

func (e *DisputeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DisputeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DisputeStatus", str)
	}
	return nil
}

func (e DisputeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DisputeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DisputeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DocumentStatus string

const (
	DocumentStatusPending  DocumentStatus = "PENDING"
	DocumentStatusApproved DocumentStatus = "APPROVED"
	DocumentStatusRejected DocumentStatus = "REJECTED"
)

var AllDocumentStatus = []DocumentStatus{
	DocumentStatusPending,
	DocumentStatusApproved,
	DocumentStatusRejected,
}

func (e DocumentStatus) IsValid() bool {
	switch e {
	case DocumentStatusPending, DocumentStatusApproved, DocumentStatusRejected:
		return true
	}
	return false
}

func (e DocumentStatus) String() string {
	return string(e)
}

func (e *DocumentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DocumentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DocumentStatus", str)
	}
	return nil
}

func (e DocumentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DocumentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DocumentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDraft       InvoiceStatus = "DRAFT"
	InvoiceStatusIssued      InvoiceStatus = "ISSUED"
	InvoiceStatusSent        InvoiceStatus = "SENT"
	InvoiceStatusTransmitted InvoiceStatus = "TRANSMITTED"
	InvoiceStatusPaid        InvoiceStatus = "PAID"
	InvoiceStatusCancelled   InvoiceStatus = "CANCELLED"
	InvoiceStatusCreditNote  InvoiceStatus = "CREDIT_NOTE"
)

var AllInvoiceStatus = []InvoiceStatus{
	InvoiceStatusDraft,
	InvoiceStatusIssued,
	InvoiceStatusSent,
	InvoiceStatusTransmitted,
	InvoiceStatusPaid,
	InvoiceStatusCancelled,
	InvoiceStatusCreditNote,
}

func (e InvoiceStatus) IsValid() bool {
	switch e {
	case InvoiceStatusDraft, InvoiceStatusIssued, InvoiceStatusSent, InvoiceStatusTransmitted, InvoiceStatusPaid, InvoiceStatusCancelled, InvoiceStatusCreditNote:
		return true
	}
	return false
}

func (e InvoiceStatus) String() string {
	return string(e)
}

func (e *InvoiceStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceStatus", str)
	}
	return nil
}

func (e InvoiceStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type InvoiceType string

const (
	InvoiceTypeClientService      InvoiceType = "CLIENT_SERVICE"
	InvoiceTypePlatformCommission InvoiceType = "PLATFORM_COMMISSION"
)

var AllInvoiceType = []InvoiceType{
	InvoiceTypeClientService,
	InvoiceTypePlatformCommission,
}

func (e InvoiceType) IsValid() bool {
	switch e {
	case InvoiceTypeClientService, InvoiceTypePlatformCommission:
		return true
	}
	return false
}

func (e InvoiceType) String() string {
	return string(e)
}

func (e *InvoiceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InvoiceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InvoiceType", str)
	}
	return nil
}

func (e InvoiceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *InvoiceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e InvoiceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderDirection string

const (
	OrderDirectionAsc  OrderDirection = "ASC"
	OrderDirectionDesc OrderDirection = "DESC"
)

var AllOrderDirection = []OrderDirection{
	OrderDirectionAsc,
	OrderDirectionDesc,
}

func (e OrderDirection) IsValid() bool {
	switch e {
	case OrderDirectionAsc, OrderDirectionDesc:
		return true
	}
	return false
}

func (e OrderDirection) String() string {
	return string(e)
}

func (e *OrderDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderDirection", str)
	}
	return nil
}

func (e OrderDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentTransactionStatus string

const (
	PaymentTransactionStatusPending           PaymentTransactionStatus = "PENDING"
	PaymentTransactionStatusRequiresAction    PaymentTransactionStatus = "REQUIRES_ACTION"
	PaymentTransactionStatusProcessing        PaymentTransactionStatus = "PROCESSING"
	PaymentTransactionStatusSucceeded         PaymentTransactionStatus = "SUCCEEDED"
	PaymentTransactionStatusFailed            PaymentTransactionStatus = "FAILED"
	PaymentTransactionStatusRefunded          PaymentTransactionStatus = "REFUNDED"
	PaymentTransactionStatusPartiallyRefunded PaymentTransactionStatus = "PARTIALLY_REFUNDED"
	PaymentTransactionStatusCancelled         PaymentTransactionStatus = "CANCELLED"
)

var AllPaymentTransactionStatus = []PaymentTransactionStatus{
	PaymentTransactionStatusPending,
	PaymentTransactionStatusRequiresAction,
	PaymentTransactionStatusProcessing,
	PaymentTransactionStatusSucceeded,
	PaymentTransactionStatusFailed,
	PaymentTransactionStatusRefunded,
	PaymentTransactionStatusPartiallyRefunded,
	PaymentTransactionStatusCancelled,
}

func (e PaymentTransactionStatus) IsValid() bool {
	switch e {
	case PaymentTransactionStatusPending, PaymentTransactionStatusRequiresAction, PaymentTransactionStatusProcessing, PaymentTransactionStatusSucceeded, PaymentTransactionStatusFailed, PaymentTransactionStatusRefunded, PaymentTransactionStatusPartiallyRefunded, PaymentTransactionStatusCancelled:
		return true
	}
	return false
}

func (e PaymentTransactionStatus) String() string {
	return string(e)
}

func (e *PaymentTransactionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentTransactionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentTransactionStatus", str)
	}
	return nil
}

func (e PaymentTransactionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentTransactionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentTransactionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "PENDING"
	PayoutStatusProcessing PayoutStatus = "PROCESSING"
	PayoutStatusPaid       PayoutStatus = "PAID"
	PayoutStatusFailed     PayoutStatus = "FAILED"
	PayoutStatusCancelled  PayoutStatus = "CANCELLED"
)

var AllPayoutStatus = []PayoutStatus{
	PayoutStatusPending,
	PayoutStatusProcessing,
	PayoutStatusPaid,
	PayoutStatusFailed,
	PayoutStatusCancelled,
}

func (e PayoutStatus) IsValid() bool {
	switch e {
	case PayoutStatusPending, PayoutStatusProcessing, PayoutStatusPaid, PayoutStatusFailed, PayoutStatusCancelled:
		return true
	}
	return false
}

func (e PayoutStatus) String() string {
	return string(e)
}

func (e *PayoutStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PayoutStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PayoutStatus", str)
	}
	return nil
}

func (e PayoutStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PayoutStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PayoutStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PricingModel string

const (
	PricingModelHourly PricingModel = "HOURLY"
	PricingModelPerSqm PricingModel = "PER_SQM"
)

var AllPricingModel = []PricingModel{
	PricingModelHourly,
	PricingModelPerSqm,
}

func (e PricingModel) IsValid() bool {
	switch e {
	case PricingModelHourly, PricingModelPerSqm:
		return true
	}
	return false
}

func (e PricingModel) String() string {
	return string(e)
}

func (e *PricingModel) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PricingModel(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PricingModel", str)
	}
	return nil
}

func (e PricingModel) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PricingModel) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PricingModel) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurrenceType string

const (
	RecurrenceTypeWeekly   RecurrenceType = "WEEKLY"
	RecurrenceTypeBiweekly RecurrenceType = "BIWEEKLY"
	RecurrenceTypeMonthly  RecurrenceType = "MONTHLY"
)

var AllRecurrenceType = []RecurrenceType{
	RecurrenceTypeWeekly,
	RecurrenceTypeBiweekly,
	RecurrenceTypeMonthly,
}

func (e RecurrenceType) IsValid() bool {
	switch e {
	case RecurrenceTypeWeekly, RecurrenceTypeBiweekly, RecurrenceTypeMonthly:
		return true
	}
	return false
}

func (e RecurrenceType) String() string {
	return string(e)
}

func (e *RecurrenceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurrenceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurrenceType", str)
	}
	return nil
}

func (e RecurrenceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurrenceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurrenceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RefundStatus string

const (
	RefundStatusRequested RefundStatus = "REQUESTED"
	RefundStatusApproved  RefundStatus = "APPROVED"
	RefundStatusProcessed RefundStatus = "PROCESSED"
	RefundStatusRejected  RefundStatus = "REJECTED"
)

var AllRefundStatus = []RefundStatus{
	RefundStatusRequested,
	RefundStatusApproved,
	RefundStatusProcessed,
	RefundStatusRejected,
}

func (e RefundStatus) IsValid() bool {
	switch e {
	case RefundStatusRequested, RefundStatusApproved, RefundStatusProcessed, RefundStatusRejected:
		return true
	}
	return false
}

func (e RefundStatus) String() string {
	return string(e)
}

func (e *RefundStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RefundStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RefundStatus", str)
	}
	return nil
}

func (e RefundStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RefundStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RefundStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReviewAction string

const (
	ReviewActionApprove ReviewAction = "APPROVE"
	ReviewActionReject  ReviewAction = "REJECT"
)

var AllReviewAction = []ReviewAction{
	ReviewActionApprove,
	ReviewActionReject,
}

func (e ReviewAction) IsValid() bool {
	switch e {
	case ReviewActionApprove, ReviewActionReject:
		return true
	}
	return false
}

func (e ReviewAction) String() string {
	return string(e)
}

func (e *ReviewAction) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReviewAction(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReviewAction", str)
	}
	return nil
}

func (e ReviewAction) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReviewAction) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReviewAction) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ServiceType string

const (
	ServiceTypeStandardCleaning  ServiceType = "STANDARD_CLEANING"
	ServiceTypeDeepCleaning      ServiceType = "DEEP_CLEANING"
	ServiceTypeMoveInOutCleaning ServiceType = "MOVE_IN_OUT_CLEANING"
	ServiceTypePostConstruction  ServiceType = "POST_CONSTRUCTION"
	ServiceTypeOfficeCleaning    ServiceType = "OFFICE_CLEANING"
	ServiceTypeWindowCleaning    ServiceType = "WINDOW_CLEANING"
)

var AllServiceType = []ServiceType{
	ServiceTypeStandardCleaning,
	ServiceTypeDeepCleaning,
	ServiceTypeMoveInOutCleaning,
	ServiceTypePostConstruction,
	ServiceTypeOfficeCleaning,
	ServiceTypeWindowCleaning,
}

func (e ServiceType) IsValid() bool {
	switch e {
	case ServiceTypeStandardCleaning, ServiceTypeDeepCleaning, ServiceTypeMoveInOutCleaning, ServiceTypePostConstruction, ServiceTypeOfficeCleaning, ServiceTypeWindowCleaning:
		return true
	}
	return false
}

func (e ServiceType) String() string {
	return string(e)
}

func (e *ServiceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ServiceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ServiceType", str)
	}
	return nil
}

func (e ServiceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ServiceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ServiceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusActive     SubscriptionStatus = "ACTIVE"
	SubscriptionStatusPaused     SubscriptionStatus = "PAUSED"
	SubscriptionStatusPastDue    SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusCancelled  SubscriptionStatus = "CANCELLED"
	SubscriptionStatusIncomplete SubscriptionStatus = "INCOMPLETE"
)

var AllSubscriptionStatus = []SubscriptionStatus{
	SubscriptionStatusActive,
	SubscriptionStatusPaused,
	SubscriptionStatusPastDue,
	SubscriptionStatusCancelled,
	SubscriptionStatusIncomplete,
}

func (e SubscriptionStatus) IsValid() bool {
	switch e {
	case SubscriptionStatusActive, SubscriptionStatusPaused, SubscriptionStatusPastDue, SubscriptionStatusCancelled, SubscriptionStatusIncomplete:
		return true
	}
	return false
}

func (e SubscriptionStatus) String() string {
	return string(e)
}

func (e *SubscriptionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SubscriptionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SubscriptionStatus", str)
	}
	return nil
}

func (e SubscriptionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SubscriptionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SubscriptionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserRole string

const (
	UserRoleClient       UserRole = "CLIENT"
	UserRoleCompanyAdmin UserRole = "COMPANY_ADMIN"
	UserRoleWorker       UserRole = "WORKER"
	UserRoleGlobalAdmin  UserRole = "GLOBAL_ADMIN"
)

var AllUserRole = []UserRole{
	UserRoleClient,
	UserRoleCompanyAdmin,
	UserRoleWorker,
	UserRoleGlobalAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleClient, UserRoleCompanyAdmin, UserRoleWorker, UserRoleGlobalAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "ACTIVE"
	UserStatusInactive  UserStatus = "INACTIVE"
	UserStatusSuspended UserStatus = "SUSPENDED"
	UserStatusPending   UserStatus = "PENDING"
)

var AllUserStatus = []UserStatus{
	UserStatusActive,
	UserStatusInactive,
	UserStatusSuspended,
	UserStatusPending,
}

func (e UserStatus) IsValid() bool {
	switch e {
	case UserStatusActive, UserStatusInactive, UserStatusSuspended, UserStatusPending:
		return true
	}
	return false
}

func (e UserStatus) String() string {
	return string(e)
}

func (e *UserStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserStatus", str)
	}
	return nil
}

func (e UserStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WaitlistLeadType string

const (
	WaitlistLeadTypeClient  WaitlistLeadType = "CLIENT"
	WaitlistLeadTypeCompany WaitlistLeadType = "COMPANY"
)

var AllWaitlistLeadType = []WaitlistLeadType{
	WaitlistLeadTypeClient,
	WaitlistLeadTypeCompany,
}

func (e WaitlistLeadType) IsValid() bool {
	switch e {
	case WaitlistLeadTypeClient, WaitlistLeadTypeCompany:
		return true
	}
	return false
}

func (e WaitlistLeadType) String() string {
	return string(e)
}

func (e *WaitlistLeadType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WaitlistLeadType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WaitlistLeadType", str)
	}
	return nil
}

func (e WaitlistLeadType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WaitlistLeadType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WaitlistLeadType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WorkerStatus string

const (
	WorkerStatusInvited       WorkerStatus = "INVITED"
	WorkerStatusPendingReview WorkerStatus = "PENDING_REVIEW"
	WorkerStatusActive        WorkerStatus = "ACTIVE"
	WorkerStatusInactive      WorkerStatus = "INACTIVE"
	WorkerStatusSuspended     WorkerStatus = "SUSPENDED"
)

var AllWorkerStatus = []WorkerStatus{
	WorkerStatusInvited,
	WorkerStatusPendingReview,
	WorkerStatusActive,
	WorkerStatusInactive,
	WorkerStatusSuspended,
}

func (e WorkerStatus) IsValid() bool {
	switch e {
	case WorkerStatusInvited, WorkerStatusPendingReview, WorkerStatusActive, WorkerStatusInactive, WorkerStatusSuspended:
		return true
	}
	return false
}

func (e WorkerStatus) String() string {
	return string(e)
}

func (e *WorkerStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WorkerStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WorkerStatus", str)
	}
	return nil
}

func (e WorkerStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WorkerStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WorkerStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
