ALTER TABLE bookings
    ADD COLUMN IF NOT EXISTS start_lat  NUMERIC(10, 7),
    ADD COLUMN IF NOT EXISTS start_lng  NUMERIC(10, 7),
    ADD COLUMN IF NOT EXISTS finish_lat NUMERIC(10, 7),
    ADD COLUMN IF NOT EXISTS finish_lng NUMERIC(10, 7);
